package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.dialog.TabDialog;

    public class ActivityDlgBase extends TabDialog
    {
        public var ui_tanchukuangdi01_jiemian014:Scale9Image;
        public var ui_zhuangshixianquan03_jiemian38216:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian51229:Scale9Image;
        public var btn_close:Button;
        public var Recharge:Button;
        public var box_2:Image;
        public var box_4:Image;
        public var box_5:Image;
        public var box_6:Image;
        public var box_7:Image;
        public var box_8:Image;
        public var box_9:Image;
        public var box_3:Image;
        public var name_2:TextField;
        public var values_2:TextField;
        public var name_4:TextField;
        public var values_4:TextField;
        public var name_5:TextField;
        public var values_5:TextField;
        public var name_6:TextField;
        public var values_6:TextField;
        public var name_7:TextField;
        public var values_7:TextField;
        public var name_8:TextField;
        public var values_8:TextField;
        public var name_9:TextField;
        public var values_9:TextField;
        public var values_3:TextField;
        public var name_3:TextField;

        public function ActivityDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tanchukuangdi01_jiemian');
            var ui_tanchukuangdi01_jiemian014Rect:Rectangle = new Rectangle(420,240,4,4);
            var ui_tanchukuangdi01_jiemian0149ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tanchukuangdi01_jiemian014Rect);
            ui_tanchukuangdi01_jiemian014 = new Scale9Image(ui_tanchukuangdi01_jiemian0149ScaleTexture);
            ui_tanchukuangdi01_jiemian014.y = 14;
            ui_tanchukuangdi01_jiemian014.width = 960;
            ui_tanchukuangdi01_jiemian014.height = 580;
            this.addQuiackChild(ui_tanchukuangdi01_jiemian014);
            texture = assetMgr.getTexture('ui_zhuangshixianquan03_jiemian');
            var ui_zhuangshixianquan03_jiemian38216Rect:Rectangle = new Rectangle(30,30,10,10);
            var ui_zhuangshixianquan03_jiemian382169ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan03_jiemian38216Rect);
            ui_zhuangshixianquan03_jiemian38216 = new Scale9Image(ui_zhuangshixianquan03_jiemian382169ScaleTexture);
            ui_zhuangshixianquan03_jiemian38216.x = 38;
            ui_zhuangshixianquan03_jiemian38216.y = 216;
            ui_zhuangshixianquan03_jiemian38216.width = 730;
            ui_zhuangshixianquan03_jiemian38216.height = 318;
            this.addQuiackChild(ui_zhuangshixianquan03_jiemian38216);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian51229Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian512299ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian51229Rect);
            ui_zhuangshixianquan01_jiemian51229 = new Scale9Image(ui_zhuangshixianquan01_jiemian512299ScaleTexture);
            ui_zhuangshixianquan01_jiemian51229.x = 51;
            ui_zhuangshixianquan01_jiemian51229.y = 229;
            ui_zhuangshixianquan01_jiemian51229.width = 704;
            ui_zhuangshixianquan01_jiemian51229.height = 292;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian51229);
            texture =assetMgr.getTexture('ui_taitoudi01_jiemian');
            image = new Image(texture);
            image.x = 120;
            image.y = 10;
            image.width = 720;
            image.height = 56;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_mingzidi01');
            image = new Image(texture);
            image.x = 254;
            image.y = 20;
            image.width = 452;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_guanbi01_anniu');
            btn_close = new Button(texture);
            btn_close.name= 'btn_close';
            btn_close.x = 866;
            btn_close.width = 72;
            btn_close.height = 76;
            this.addQuiackChild(btn_close);
            texture =assetMgr.getTexture('ui_shouchongjiangli_taitou_wenzi');
            image = new Image(texture);
            image.x = 423;
            image.y = 19;
            image.width = 115;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_8888_wenzi');
            image = new Image(texture);
            image.x = 508;
            image.y = 146;
            image.width = 183;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_chongzhi_wenzi');
            image = new Image(texture);
            image.x = 115;
            image.y = 97;
            image.width = 77;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_haohuadalibao_wenzi');
            image = new Image(texture);
            image.x = 700;
            image.y = 149;
            image.width = 185;
            image.height = 42;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_jiazhi_wenzi');
            image = new Image(texture);
            image.x = 424;
            image.y = 150;
            image.width = 77;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_jikelingqu_wenzi');
            image = new Image(texture);
            image.x = 347;
            image.y = 97;
            image.width = 149;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_renyijine_wenzi');
            image = new Image(texture);
            image.x = 194;
            image.y = 96;
            image.width = 151;
            image.height = 43;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_changjingtouxiangdi01_01');
            image = new Image(texture);
            image.x = 772;
            image.y = 312;
            image.width = 148;
            image.height = 148;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 746;
            image.y = 232;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 746;
            image.y = 518;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 60;
            image.y = 232;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 60;
            image.y = 518;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 744;
            image.y = 237;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 62;
            image.y = 513;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 744;
            image.y = 513;
            image.width = 8;
            image.height = 33;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 62;
            image.y = 237;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_yuanhonganniu01_anniu');
            Recharge = new Button(texture);
            Recharge.name= 'Recharge';
            Recharge.x = 789;
            Recharge.y = 329;
            Recharge.width = 112;
            Recharge.height = 112;
            this.addQuiackChild(Recharge);
            Recharge.text= 'lable';
            Recharge.fontColor= 0xFFFFFF;
            Recharge.fontSize= 24;
            texture = assetMgr.getTexture('ui_daojukuang01')
            box_2 = new Image(texture);
            box_2.x = 293;
            box_2.y = 245;
            box_2.width = 98;
            box_2.height = 98;
            this.addQuiackChild(box_2);
            box_2.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            box_4 = new Image(texture);
            box_4.x = 528;
            box_4.y = 245;
            box_4.width = 98;
            box_4.height = 98;
            this.addQuiackChild(box_4);
            box_4.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            box_5 = new Image(texture);
            box_5.x = 643;
            box_5.y = 245;
            box_5.width = 98;
            box_5.height = 98;
            this.addQuiackChild(box_5);
            box_5.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            box_6 = new Image(texture);
            box_6.x = 293;
            box_6.y = 377;
            box_6.width = 98;
            box_6.height = 98;
            this.addQuiackChild(box_6);
            box_6.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            box_7 = new Image(texture);
            box_7.x = 411;
            box_7.y = 377;
            box_7.width = 98;
            box_7.height = 98;
            this.addQuiackChild(box_7);
            box_7.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            box_8 = new Image(texture);
            box_8.x = 528;
            box_8.y = 377;
            box_8.width = 98;
            box_8.height = 98;
            this.addQuiackChild(box_8);
            box_8.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            box_9 = new Image(texture);
            box_9.x = 643;
            box_9.y = 377;
            box_9.width = 98;
            box_9.height = 98;
            this.addQuiackChild(box_9);
            box_9.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            box_3 = new Image(texture);
            box_3.x = 411;
            box_3.y = 245;
            box_3.width = 98;
            box_3.height = 98;
            this.addQuiackChild(box_3);
            box_3.touchable = false;
            name_2 = new TextField(116,26,'','',18,0x00FF00,false);
            name_2.touchable = false;
            name_2.hAlign= 'center';
            name_2.text= '';
            name_2.x = 284;
            name_2.y = 344;
            this.addQuiackChild(name_2);
            values_2 = new TextField(75,32,'','',21,0xFFFFFF,false);
            values_2.touchable = false;
            values_2.hAlign= 'left';
            values_2.text= '';
            values_2.x = 304;
            values_2.y = 305;
            this.addQuiackChild(values_2);
            name_4 = new TextField(116,26,'','',18,0x00FF00,false);
            name_4.touchable = false;
            name_4.hAlign= 'center';
            name_4.text= '';
            name_4.x = 516;
            name_4.y = 344;
            this.addQuiackChild(name_4);
            values_4 = new TextField(75,32,'','',21,0xFFFFFF,false);
            values_4.touchable = false;
            values_4.hAlign= 'left';
            values_4.text= '';
            values_4.x = 539;
            values_4.y = 305;
            this.addQuiackChild(values_4);
            name_5 = new TextField(116,26,'','',18,0x00FF00,false);
            name_5.touchable = false;
            name_5.hAlign= 'center';
            name_5.text= '';
            name_5.x = 632;
            name_5.y = 344;
            this.addQuiackChild(name_5);
            values_5 = new TextField(75,32,'','',21,0xFFFFFF,false);
            values_5.touchable = false;
            values_5.hAlign= 'left';
            values_5.text= '';
            values_5.x = 654;
            values_5.y = 305;
            this.addQuiackChild(values_5);
            name_6 = new TextField(116,26,'','',18,0x00FF00,false);
            name_6.touchable = false;
            name_6.hAlign= 'center';
            name_6.text= '';
            name_6.x = 284;
            name_6.y = 476;
            this.addQuiackChild(name_6);
            values_6 = new TextField(75,32,'','',21,0xFFFFFF,false);
            values_6.touchable = false;
            values_6.hAlign= 'left';
            values_6.text= '';
            values_6.x = 304;
            values_6.y = 437;
            this.addQuiackChild(values_6);
            name_7 = new TextField(116,26,'','',18,0x00FF00,false);
            name_7.touchable = false;
            name_7.hAlign= 'center';
            name_7.text= '';
            name_7.x = 400;
            name_7.y = 476;
            this.addQuiackChild(name_7);
            values_7 = new TextField(75,32,'','',21,0xFFFFFF,false);
            values_7.touchable = false;
            values_7.hAlign= 'left';
            values_7.text= '';
            values_7.x = 422;
            values_7.y = 437;
            this.addQuiackChild(values_7);
            name_8 = new TextField(116,26,'','',18,0x00FF00,false);
            name_8.touchable = false;
            name_8.hAlign= 'center';
            name_8.text= '';
            name_8.x = 516;
            name_8.y = 476;
            this.addQuiackChild(name_8);
            values_8 = new TextField(75,32,'','',21,0xFFFFFF,false);
            values_8.touchable = false;
            values_8.hAlign= 'left';
            values_8.text= '';
            values_8.x = 539;
            values_8.y = 437;
            this.addQuiackChild(values_8);
            name_9 = new TextField(116,26,'','',18,0x00FF00,false);
            name_9.touchable = false;
            name_9.hAlign= 'center';
            name_9.text= '';
            name_9.x = 632;
            name_9.y = 476;
            this.addQuiackChild(name_9);
            values_9 = new TextField(75,32,'','',21,0xFFFFFF,false);
            values_9.touchable = false;
            values_9.hAlign= 'left';
            values_9.text= '';
            values_9.x = 654;
            values_9.y = 437;
            this.addQuiackChild(values_9);
            values_3 = new TextField(75,32,'','',21,0xFFFFFF,false);
            values_3.touchable = false;
            values_3.hAlign= 'left';
            values_3.text= '';
            values_3.x = 422;
            values_3.y = 305;
            this.addQuiackChild(values_3);
            name_3 = new TextField(116,26,'','',18,0x00FF00,false);
            name_3.touchable = false;
            name_3.hAlign= 'center';
            name_3.text= '';
            name_3.x = 400;
            name_3.y = 344;
            this.addQuiackChild(name_3);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            btn_close.dispose();
            Recharge.dispose();
            super.dispose();
        
}
    }
}
