package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.controls.List;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import feathers.controls.TextInput;
    import game.view.arena.render.ArenaCreateNameRender;
    import com.dialog.Dialog;

    public class ArenaCreateNameDlgBase extends Dialog
    {
        public var ui_tipstanchukuangdi01_jiemian00:Scale9Image;
        public var ui_zhuangshixianquan03_jiemian72296:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian86310:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian4275:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian45261:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian42390:Scale9Image;
        public var txt_input:TextInput;
        public var btnRandom_Scale9Button:Scale9Button;
        public var okBtn_Scale9Button:Scale9Button;
        public var txt_inputBtn:TextField;
        public var ui_zhuangshixianquan02_jiemian42279:Scale9Image;
        public var list_hero:List;
        public var curr_hero:ArenaCreateNameRender;
        public var title:TextField;

        public function ArenaCreateNameDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian00Rect:Rectangle = new Rectangle(48,46,44,43);
            var ui_tipstanchukuangdi01_jiemian009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian00Rect);
            ui_tipstanchukuangdi01_jiemian00 = new Scale9Image(ui_tipstanchukuangdi01_jiemian009ScaleTexture);
            ui_tipstanchukuangdi01_jiemian00.width = 614;
            ui_tipstanchukuangdi01_jiemian00.height = 500;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian00);
            texture = assetMgr.getTexture('ui_zhuangshixianquan03_jiemian');
            var ui_zhuangshixianquan03_jiemian72296Rect:Rectangle = new Rectangle(30,30,10,10);
            var ui_zhuangshixianquan03_jiemian722969ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan03_jiemian72296Rect);
            ui_zhuangshixianquan03_jiemian72296 = new Scale9Image(ui_zhuangshixianquan03_jiemian722969ScaleTexture);
            ui_zhuangshixianquan03_jiemian72296.x = 72;
            ui_zhuangshixianquan03_jiemian72296.y = 296;
            ui_zhuangshixianquan03_jiemian72296.width = 490;
            ui_zhuangshixianquan03_jiemian72296.height = 78;
            this.addQuiackChild(ui_zhuangshixianquan03_jiemian72296);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian86310Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian863109ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian86310Rect);
            ui_zhuangshixianquan01_jiemian86310 = new Scale9Image(ui_zhuangshixianquan01_jiemian863109ScaleTexture);
            ui_zhuangshixianquan01_jiemian86310.x = 86;
            ui_zhuangshixianquan01_jiemian86310.y = 310;
            ui_zhuangshixianquan01_jiemian86310.width = 462;
            ui_zhuangshixianquan01_jiemian86310.height = 50;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian86310);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian4275Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian42759ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian4275Rect);
            ui_zhuangshixianquan02_jiemian4275 = new Scale9Image(ui_zhuangshixianquan02_jiemian42759ScaleTexture);
            ui_zhuangshixianquan02_jiemian4275.x = 42;
            ui_zhuangshixianquan02_jiemian4275.y = 75;
            ui_zhuangshixianquan02_jiemian4275.width = 530;
            ui_zhuangshixianquan02_jiemian4275.height = 2;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian4275);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian45261Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian452619ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian45261Rect);
            ui_zhuangshixianquan02_jiemian45261 = new Scale9Image(ui_zhuangshixianquan02_jiemian452619ScaleTexture);
            ui_zhuangshixianquan02_jiemian45261.x = 45;
            ui_zhuangshixianquan02_jiemian45261.y = 261;
            ui_zhuangshixianquan02_jiemian45261.width = 530;
            ui_zhuangshixianquan02_jiemian45261.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian45261);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian42390Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian423909ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian42390Rect);
            ui_zhuangshixianquan02_jiemian42390 = new Scale9Image(ui_zhuangshixianquan02_jiemian423909ScaleTexture);
            ui_zhuangshixianquan02_jiemian42390.x = 42;
            ui_zhuangshixianquan02_jiemian42390.y = 390;
            ui_zhuangshixianquan02_jiemian42390.width = 530;
            ui_zhuangshixianquan02_jiemian42390.height = 2;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian42390);
            txt_input = new TextInput();
            txt_input.textEditorProperties.fontSize = 24;
            txt_input.text = '';
            txt_input.textEditorProperties.color = 0xFFFFFF;
            txt_input.x = 125;
            txt_input.y = 319;
            txt_input.width = 286;
            txt_input.height = 32;
            this.addQuiackChild(txt_input);
            texture = assetMgr.getTexture('ui_hong02_01_anniu');
            var btnRandom_Scale9ButtonRect:Rectangle = new Rectangle(25,10,50,20);
            btnRandom_Scale9Button = new Scale9Button(texture,btnRandom_Scale9ButtonRect);
            btnRandom_Scale9Button.x = 431;
            btnRandom_Scale9Button.y = 315;
            btnRandom_Scale9Button.width = 99;
            btnRandom_Scale9Button.height = 39;
            this.addQuiackChild(btnRandom_Scale9Button);
            btnRandom_Scale9Button.name = 'btnRandom_Scale9Button';
            btnRandom_Scale9Button.text= 'lable';
            btnRandom_Scale9Button.fontColor= 0xFFFFFFB4;
            btnRandom_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var okBtn_Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            okBtn_Scale9Button = new Scale9Button(texture,okBtn_Scale9ButtonRect);
            okBtn_Scale9Button.x = 214;
            okBtn_Scale9Button.y = 398;
            okBtn_Scale9Button.width = 186;
            okBtn_Scale9Button.height = 70;
            this.addQuiackChild(okBtn_Scale9Button);
            okBtn_Scale9Button.name = 'okBtn_Scale9Button';
            okBtn_Scale9Button.text= 'lable';
            okBtn_Scale9Button.fontColor= 0xFFFFFF;
            okBtn_Scale9Button.fontSize= 24;
            txt_inputBtn = new TextField(286,32,'','',24,0xCCCCCC,false);
            txt_inputBtn.touchable = false;
            txt_inputBtn.hAlign= 'center';
            txt_inputBtn.text= '';
            txt_inputBtn.x = 125;
            txt_inputBtn.y = 319;
            this.addQuiackChild(txt_inputBtn);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian42279Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian422799ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian42279Rect);
            ui_zhuangshixianquan02_jiemian42279 = new Scale9Image(ui_zhuangshixianquan02_jiemian422799ScaleTexture);
            ui_zhuangshixianquan02_jiemian42279.x = 42;
            ui_zhuangshixianquan02_jiemian42279.y = 279;
            ui_zhuangshixianquan02_jiemian42279.width = 530;
            ui_zhuangshixianquan02_jiemian42279.height = 2;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian42279);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 48;
            image.y = 38;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 568;
            image.y = 38;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 48;
            image.y = 457;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1.015869140625;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 568;
            image.y = 457;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1.015869140625;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 539;
            image.y = 313;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 539;
            image.y = 357;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 423;
            image.y = 313;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 423;
            image.y = 357;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            list_hero = new List();
            list_hero.x = 43;
            list_hero.y = 89;
            list_hero.width = 529;
            list_hero.height = 173;
            this.addQuiackChild(list_hero);
            curr_hero = new ArenaCreateNameRender();
            curr_hero.x = 52;
            curr_hero.y = 293;
            this.addQuiackChild(curr_hero);
            title = new TextField(286,36,'','',26,0xFFFFFF,false);
            title.touchable = false;
            title.hAlign= 'center';
            title.text= '';
            title.x = 164;
            title.y = 38;
            this.addQuiackChild(title);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 537;
            image.y = 317;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 566;
            image.y = 43;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 50;
            image.y = 43;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 50;
            image.y = 452;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 424;
            image.y = 352;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 424;
            image.y = 317;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 566;
            image.y = 452;
            image.width = 8;
            image.height = 33;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 537;
            image.y = 352;
            image.width = 8;
            image.height = 33;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            txt_input.dispose();
            list_hero.dispose();
            curr_hero.dispose();
            super.dispose();
        
}
    }
}
