package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import game.view.arena.render.ArenaCreateNameRender;
    import com.dialog.Dialog;

    public class ArenaRoleDialogBase extends Dialog
    {
        public var ui_tipstanchukuangdi01_jiemian00:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian83167:Scale9Image;
        public var ui_zhuangshixianquan03_jiemian65102:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian79116:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian83166:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian4373:Scale9Image;
        public var zltitle:TextField;
        public var txtNameTitle:TextField;
        public var txtGhTitle:TextField;
        public var hero:ArenaCreateNameRender;
        public var txtVip:TextField;
        public var txtRankTitle:TextField;
        public var txtPowerTitle:TextField;
        public var txtRank:TextField;
        public var txtPower:TextField;
        public var txtNumTitle:TextField;
        public var txtNum:TextField;
        public var ui_zhuangshixianquan02_jiemian4374:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian43259:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian43260:Scale9Image;
        public var txtName:TextField;
        public var txtGh:TextField;
        public var embtn_7:Button;
        public var embtn_4:Button;
        public var embtn_1:Button;
        public var embtn_8:Button;
        public var embtn_5:Button;
        public var embtn_2:Button;
        public var embtn_9:Button;
        public var embtn_6:Button;
        public var embtn_3:Button;
        public var single_3:Image;
        public var single_2:Image;
        public var single_1:Image;
        public var single_4:Image;
        public var single_6:Image;
        public var single_5:Image;
        public var single_7:Image;
        public var single_8:Image;
        public var single_9:Image;
        public var emb_7:Image;
        public var emb_9:Image;
        public var emb_2:Image;
        public var emb_5:Image;
        public var emb_8:Image;
        public var emb_1:Image;
        public var emb_4:Image;
        public var emb_3:Image;
        public var emb_6:Image;

        public function ArenaRoleDialogBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian00Rect:Rectangle = new Rectangle(48,46,44,43);
            var ui_tipstanchukuangdi01_jiemian009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian00Rect);
            ui_tipstanchukuangdi01_jiemian00 = new Scale9Image(ui_tipstanchukuangdi01_jiemian009ScaleTexture);
            ui_tipstanchukuangdi01_jiemian00.width = 600;
            ui_tipstanchukuangdi01_jiemian00.height = 600;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian00);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian83167Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian831679ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian83167Rect);
            ui_zhuangshixianquan02_jiemian83167 = new Scale9Image(ui_zhuangshixianquan02_jiemian831679ScaleTexture);
            ui_zhuangshixianquan02_jiemian83167.x = 83;
            ui_zhuangshixianquan02_jiemian83167.y = 167;
            ui_zhuangshixianquan02_jiemian83167.width = 446;
            ui_zhuangshixianquan02_jiemian83167.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian83167);
            texture = assetMgr.getTexture('ui_zhuangshixianquan03_jiemian');
            var ui_zhuangshixianquan03_jiemian65102Rect:Rectangle = new Rectangle(30,30,10,10);
            var ui_zhuangshixianquan03_jiemian651029ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan03_jiemian65102Rect);
            ui_zhuangshixianquan03_jiemian65102 = new Scale9Image(ui_zhuangshixianquan03_jiemian651029ScaleTexture);
            ui_zhuangshixianquan03_jiemian65102.x = 65;
            ui_zhuangshixianquan03_jiemian65102.y = 102;
            ui_zhuangshixianquan03_jiemian65102.width = 484;
            ui_zhuangshixianquan03_jiemian65102.height = 130;
            this.addQuiackChild(ui_zhuangshixianquan03_jiemian65102);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian79116Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian791169ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian79116Rect);
            ui_zhuangshixianquan01_jiemian79116 = new Scale9Image(ui_zhuangshixianquan01_jiemian791169ScaleTexture);
            ui_zhuangshixianquan01_jiemian79116.x = 79;
            ui_zhuangshixianquan01_jiemian79116.y = 116;
            ui_zhuangshixianquan01_jiemian79116.width = 456;
            ui_zhuangshixianquan01_jiemian79116.height = 102;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian79116);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian83166Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian831669ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian83166Rect);
            ui_zhuangshixianquan02_jiemian83166 = new Scale9Image(ui_zhuangshixianquan02_jiemian831669ScaleTexture);
            ui_zhuangshixianquan02_jiemian83166.x = 83;
            ui_zhuangshixianquan02_jiemian83166.y = 166;
            ui_zhuangshixianquan02_jiemian83166.width = 446;
            ui_zhuangshixianquan02_jiemian83166.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian83166);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 526;
            image.y = 119;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 526;
            image.y = 215;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian4373Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian43739ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian4373Rect);
            ui_zhuangshixianquan02_jiemian4373 = new Scale9Image(ui_zhuangshixianquan02_jiemian43739ScaleTexture);
            ui_zhuangshixianquan02_jiemian4373.x = 43;
            ui_zhuangshixianquan02_jiemian4373.y = 73;
            ui_zhuangshixianquan02_jiemian4373.width = 514;
            ui_zhuangshixianquan02_jiemian4373.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian4373);
            zltitle = new TextField(286,33,'','',26,0xFFFFFF,false);
            zltitle.touchable = false;
            zltitle.hAlign= 'center';
            zltitle.text= '';
            zltitle.x = 157;
            zltitle.y = 38;
            this.addQuiackChild(zltitle);
            txtNameTitle = new TextField(72,32,'','',24,0x999999,false);
            txtNameTitle.touchable = false;
            txtNameTitle.hAlign= 'center';
            txtNameTitle.text= '';
            txtNameTitle.x = 150;
            txtNameTitle.y = 126;
            this.addQuiackChild(txtNameTitle);
            txtGhTitle = new TextField(72,32,'','',24,0x999999,false);
            txtGhTitle.touchable = false;
            txtGhTitle.hAlign= 'center';
            txtGhTitle.text= '';
            txtGhTitle.x = 150;
            txtGhTitle.y = 176;
            this.addQuiackChild(txtGhTitle);
            hero = new ArenaCreateNameRender();
            hero.x = 47;
            hero.y = 104;
            this.addQuiackChild(hero);
            texture =assetMgr.getTexture('ui_vipzuoshang01_tubiao');
            image = new Image(texture);
            image.x = 64;
            image.y = 173;
            image.width = 50;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txtVip = new TextField(50,31,'','',24,0xFFFFFF,false);
            txtVip.touchable = false;
            txtVip.hAlign= 'center';
            txtVip.text= '0';
            txtVip.x = 64;
            txtVip.y = 189;
            this.addQuiackChild(txtVip);
            txtRankTitle = new TextField(100,31,'','',24,0xFFCC99,false);
            txtRankTitle.touchable = false;
            txtRankTitle.hAlign= 'left';
            txtRankTitle.text= '';
            txtRankTitle.x = 62;
            txtRankTitle.y = 313;
            this.addQuiackChild(txtRankTitle);
            txtPowerTitle = new TextField(100,31,'','',24,0xFFCC99,false);
            txtPowerTitle.touchable = false;
            txtPowerTitle.hAlign= 'left';
            txtPowerTitle.text= '';
            txtPowerTitle.x = 62;
            txtPowerTitle.y = 395;
            this.addQuiackChild(txtPowerTitle);
            txtRank = new TextField(120,38,'','',30,0xFFFFFF,false);
            txtRank.touchable = false;
            txtRank.hAlign= 'center';
            txtRank.text= '';
            txtRank.x = 160;
            txtRank.y = 310;
            this.addQuiackChild(txtRank);
            txtPower = new TextField(120,38,'','',30,0xFFFFFF,false);
            txtPower.touchable = false;
            txtPower.hAlign= 'center';
            txtPower.text= '';
            txtPower.x = 160;
            txtPower.y = 392;
            this.addQuiackChild(txtPower);
            txtNumTitle = new TextField(100,31,'','',24,0xFFCC99,false);
            txtNumTitle.touchable = false;
            txtNumTitle.hAlign= 'left';
            txtNumTitle.text= '';
            txtNumTitle.x = 62;
            txtNumTitle.y = 477;
            this.addQuiackChild(txtNumTitle);
            txtNum = new TextField(120,38,'','',30,0xFFFFFF,false);
            txtNum.touchable = false;
            txtNum.hAlign= 'center';
            txtNum.text= '';
            txtNum.x = 160;
            txtNum.y = 474;
            this.addQuiackChild(txtNum);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian4374Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian43749ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian4374Rect);
            ui_zhuangshixianquan02_jiemian4374 = new Scale9Image(ui_zhuangshixianquan02_jiemian43749ScaleTexture);
            ui_zhuangshixianquan02_jiemian4374.x = 43;
            ui_zhuangshixianquan02_jiemian4374.y = 74;
            ui_zhuangshixianquan02_jiemian4374.width = 514;
            ui_zhuangshixianquan02_jiemian4374.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian4374);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 48;
            image.y = 38;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 552;
            image.y = 38;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 48;
            image.y = 556;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 552;
            image.y = 556;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian43259Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian432599ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian43259Rect);
            ui_zhuangshixianquan02_jiemian43259 = new Scale9Image(ui_zhuangshixianquan02_jiemian432599ScaleTexture);
            ui_zhuangshixianquan02_jiemian43259.x = 43;
            ui_zhuangshixianquan02_jiemian43259.y = 259;
            ui_zhuangshixianquan02_jiemian43259.width = 514;
            ui_zhuangshixianquan02_jiemian43259.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian43259);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian43260Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian432609ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian43260Rect);
            ui_zhuangshixianquan02_jiemian43260 = new Scale9Image(ui_zhuangshixianquan02_jiemian432609ScaleTexture);
            ui_zhuangshixianquan02_jiemian43260.x = 43;
            ui_zhuangshixianquan02_jiemian43260.y = 260;
            ui_zhuangshixianquan02_jiemian43260.width = 514;
            ui_zhuangshixianquan02_jiemian43260.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian43260);
            txtName = new TextField(234,32,'','',24,0xFFFFFF,false);
            txtName.touchable = false;
            txtName.hAlign= 'center';
            txtName.text= '';
            txtName.x = 240;
            txtName.y = 126;
            this.addQuiackChild(txtName);
            txtGh = new TextField(234,32,'','',24,0xFFFFFF,false);
            txtGh.touchable = false;
            txtGh.hAlign= 'center';
            txtGh.text= '';
            txtGh.x = 240;
            txtGh.y = 176;
            this.addQuiackChild(txtGh);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            embtn_7 = new Button(texture);
            embtn_7.name= 'embtn_7';
            embtn_7.x = 303;
            embtn_7.y = 293;
            embtn_7.width = 74;
            embtn_7.height = 74;
            this.addQuiackChild(embtn_7);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            embtn_4 = new Button(texture);
            embtn_4.name= 'embtn_4';
            embtn_4.x = 385;
            embtn_4.y = 293;
            embtn_4.width = 74;
            embtn_4.height = 74;
            this.addQuiackChild(embtn_4);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            embtn_1 = new Button(texture);
            embtn_1.name= 'embtn_1';
            embtn_1.x = 467;
            embtn_1.y = 293;
            embtn_1.width = 74;
            embtn_1.height = 74;
            this.addQuiackChild(embtn_1);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            embtn_8 = new Button(texture);
            embtn_8.name= 'embtn_8';
            embtn_8.x = 303;
            embtn_8.y = 375;
            embtn_8.width = 74;
            embtn_8.height = 74;
            this.addQuiackChild(embtn_8);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            embtn_5 = new Button(texture);
            embtn_5.name= 'embtn_5';
            embtn_5.x = 385;
            embtn_5.y = 375;
            embtn_5.width = 74;
            embtn_5.height = 74;
            this.addQuiackChild(embtn_5);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            embtn_2 = new Button(texture);
            embtn_2.name= 'embtn_2';
            embtn_2.x = 467;
            embtn_2.y = 375;
            embtn_2.width = 74;
            embtn_2.height = 74;
            this.addQuiackChild(embtn_2);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            embtn_9 = new Button(texture);
            embtn_9.name= 'embtn_9';
            embtn_9.x = 303;
            embtn_9.y = 457;
            embtn_9.width = 74;
            embtn_9.height = 74;
            this.addQuiackChild(embtn_9);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            embtn_6 = new Button(texture);
            embtn_6.name= 'embtn_6';
            embtn_6.x = 385;
            embtn_6.y = 457;
            embtn_6.width = 74;
            embtn_6.height = 74;
            this.addQuiackChild(embtn_6);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            embtn_3 = new Button(texture);
            embtn_3.name= 'embtn_3';
            embtn_3.x = 467;
            embtn_3.y = 457;
            embtn_3.width = 74;
            embtn_3.height = 74;
            this.addQuiackChild(embtn_3);
            texture = assetMgr.getTexture('ui_weizhiqian_wenzi')
            single_3 = new Image(texture);
            single_3.x = 322;
            single_3.y = 476;
            single_3.width = 35;
            single_3.height = 35;
            this.addQuiackChild(single_3);
            single_3.touchable = false;
            texture = assetMgr.getTexture('ui_weizhiqian_wenzi')
            single_2 = new Image(texture);
            single_2.x = 322;
            single_2.y = 394;
            single_2.width = 35;
            single_2.height = 35;
            this.addQuiackChild(single_2);
            single_2.touchable = false;
            texture = assetMgr.getTexture('ui_weizhiqian_wenzi')
            single_1 = new Image(texture);
            single_1.x = 322;
            single_1.y = 312;
            single_1.width = 35;
            single_1.height = 35;
            this.addQuiackChild(single_1);
            single_1.touchable = false;
            texture = assetMgr.getTexture('ui_weizhizhong_wenzi')
            single_4 = new Image(texture);
            single_4.x = 404;
            single_4.y = 312;
            single_4.width = 35;
            single_4.height = 35;
            this.addQuiackChild(single_4);
            single_4.touchable = false;
            texture = assetMgr.getTexture('ui_weizhizhong_wenzi')
            single_6 = new Image(texture);
            single_6.x = 404;
            single_6.y = 476;
            single_6.width = 35;
            single_6.height = 35;
            this.addQuiackChild(single_6);
            single_6.touchable = false;
            texture = assetMgr.getTexture('ui_weizhizhong_wenzi')
            single_5 = new Image(texture);
            single_5.x = 404;
            single_5.y = 394;
            single_5.width = 35;
            single_5.height = 35;
            this.addQuiackChild(single_5);
            single_5.touchable = false;
            texture = assetMgr.getTexture('ui_weizhihou_wenzi')
            single_7 = new Image(texture);
            single_7.x = 486;
            single_7.y = 312;
            single_7.width = 35;
            single_7.height = 35;
            this.addQuiackChild(single_7);
            single_7.touchable = false;
            texture = assetMgr.getTexture('ui_weizhihou_wenzi')
            single_8 = new Image(texture);
            single_8.x = 486;
            single_8.y = 394;
            single_8.width = 35;
            single_8.height = 35;
            this.addQuiackChild(single_8);
            single_8.touchable = false;
            texture = assetMgr.getTexture('ui_weizhihou_wenzi')
            single_9 = new Image(texture);
            single_9.x = 486;
            single_9.y = 476;
            single_9.width = 35;
            single_9.height = 35;
            this.addQuiackChild(single_9);
            single_9.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_01')
            emb_7 = new Image(texture);
            emb_7.x = 302;
            emb_7.y = 292;
            emb_7.width = 75;
            emb_7.height = 75;
            this.addQuiackChild(emb_7);
            emb_7.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_01')
            emb_9 = new Image(texture);
            emb_9.x = 302;
            emb_9.y = 456;
            emb_9.width = 75;
            emb_9.height = 75;
            this.addQuiackChild(emb_9);
            emb_9.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_01')
            emb_2 = new Image(texture);
            emb_2.x = 466;
            emb_2.y = 374;
            emb_2.width = 75;
            emb_2.height = 75;
            this.addQuiackChild(emb_2);
            emb_2.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_01')
            emb_5 = new Image(texture);
            emb_5.x = 384;
            emb_5.y = 374;
            emb_5.width = 75;
            emb_5.height = 75;
            this.addQuiackChild(emb_5);
            emb_5.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_01')
            emb_8 = new Image(texture);
            emb_8.x = 302;
            emb_8.y = 374;
            emb_8.width = 75;
            emb_8.height = 75;
            this.addQuiackChild(emb_8);
            emb_8.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_01')
            emb_1 = new Image(texture);
            emb_1.x = 466;
            emb_1.y = 292;
            emb_1.width = 75;
            emb_1.height = 75;
            this.addQuiackChild(emb_1);
            emb_1.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_01')
            emb_4 = new Image(texture);
            emb_4.x = 384;
            emb_4.y = 292;
            emb_4.width = 75;
            emb_4.height = 75;
            this.addQuiackChild(emb_4);
            emb_4.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_01')
            emb_3 = new Image(texture);
            emb_3.x = 466;
            emb_3.y = 456;
            emb_3.width = 75;
            emb_3.height = 75;
            this.addQuiackChild(emb_3);
            emb_3.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_01')
            emb_6 = new Image(texture);
            emb_6.x = 384;
            emb_6.y = 456;
            emb_6.width = 75;
            emb_6.height = 75;
            this.addQuiackChild(emb_6);
            emb_6.touchable = false;
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 550;
            image.y = 43;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 550;
            image.y = 551;
            image.width = 8;
            image.height = 33;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 49;
            image.y = 43;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 49;
            image.y = 551;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 524;
            image.y = 124;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 524;
            image.y = 210;
            image.width = 8;
            image.height = 33;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            hero.dispose();
            embtn_7.dispose();
            embtn_4.dispose();
            embtn_1.dispose();
            embtn_8.dispose();
            embtn_5.dispose();
            embtn_2.dispose();
            embtn_9.dispose();
            embtn_6.dispose();
            embtn_3.dispose();
            super.dispose();
        
}
    }
}
