package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.controls.List;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import game.view.arena.render.EmbattleShowItem;
    import com.dialog.Dialog;

    public class ArenaEmbattleDialogBase extends Dialog
    {
        public var ui_tipstanchukuangdi01_jiemian00:Scale9Image;
        public var ui_tipstanchukuangdi01_jiemian3800:Scale9Image;
        public var list_hero:List;
        public var ui_zhuangshixianquan02_jiemian3079:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian41079:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian410427:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian410472:Scale9Image;
        public var enter_Scale9Button:Scale9Button;
        public var emb_7:EmbattleShowItem;
        public var emb_4:EmbattleShowItem;
        public var emb_1:EmbattleShowItem;
        public var emb_8:EmbattleShowItem;
        public var emb_5:EmbattleShowItem;
        public var emb_2:EmbattleShowItem;
        public var emb_9:EmbattleShowItem;
        public var emb_6:EmbattleShowItem;
        public var emb_3:EmbattleShowItem;
        public var txtPowerTitle:TextField;
        public var txtPower:TextField;

        public function ArenaEmbattleDialogBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian00Rect:Rectangle = new Rectangle(48,46,44,43);
            var ui_tipstanchukuangdi01_jiemian009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian00Rect);
            ui_tipstanchukuangdi01_jiemian00 = new Scale9Image(ui_tipstanchukuangdi01_jiemian009ScaleTexture);
            ui_tipstanchukuangdi01_jiemian00.width = 408;
            ui_tipstanchukuangdi01_jiemian00.height = 600;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian00);
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian3800Rect:Rectangle = new Rectangle(48,46,44,43);
            var ui_tipstanchukuangdi01_jiemian38009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian3800Rect);
            ui_tipstanchukuangdi01_jiemian3800 = new Scale9Image(ui_tipstanchukuangdi01_jiemian38009ScaleTexture);
            ui_tipstanchukuangdi01_jiemian3800.x = 380;
            ui_tipstanchukuangdi01_jiemian3800.width = 408;
            ui_tipstanchukuangdi01_jiemian3800.height = 600;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian3800);
            texture =assetMgr.getTexture('ui_shangzhenyingxiong_xiaotaitou_wenzi');
            image = new Image(texture);
            image.x = 533;
            image.y = 42;
            image.width = 102;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_kexuanyingxiong_xiaotaitou_wenzi');
            image = new Image(texture);
            image.x = 153;
            image.y = 42;
            image.width = 102;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            list_hero = new List();
            list_hero.x = 44;
            list_hero.y = 102;
            list_hero.width = 320;
            list_hero.height = 420;
            this.addQuiackChild(list_hero);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian3079Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian30799ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian3079Rect);
            ui_zhuangshixianquan02_jiemian3079 = new Scale9Image(ui_zhuangshixianquan02_jiemian30799ScaleTexture);
            ui_zhuangshixianquan02_jiemian3079.x = 30;
            ui_zhuangshixianquan02_jiemian3079.y = 79;
            ui_zhuangshixianquan02_jiemian3079.width = 348;
            ui_zhuangshixianquan02_jiemian3079.height = 3;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian3079);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian41079Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian410799ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian41079Rect);
            ui_zhuangshixianquan02_jiemian41079 = new Scale9Image(ui_zhuangshixianquan02_jiemian410799ScaleTexture);
            ui_zhuangshixianquan02_jiemian41079.x = 410;
            ui_zhuangshixianquan02_jiemian41079.y = 79;
            ui_zhuangshixianquan02_jiemian41079.width = 348;
            ui_zhuangshixianquan02_jiemian41079.height = 3;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian41079);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian410427Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian4104279ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian410427Rect);
            ui_zhuangshixianquan02_jiemian410427 = new Scale9Image(ui_zhuangshixianquan02_jiemian4104279ScaleTexture);
            ui_zhuangshixianquan02_jiemian410427.x = 410;
            ui_zhuangshixianquan02_jiemian410427.y = 427;
            ui_zhuangshixianquan02_jiemian410427.width = 348;
            ui_zhuangshixianquan02_jiemian410427.height = 3;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian410427);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian410472Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian4104729ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian410472Rect);
            ui_zhuangshixianquan02_jiemian410472 = new Scale9Image(ui_zhuangshixianquan02_jiemian4104729ScaleTexture);
            ui_zhuangshixianquan02_jiemian410472.x = 410;
            ui_zhuangshixianquan02_jiemian410472.y = 472;
            ui_zhuangshixianquan02_jiemian410472.width = 348;
            ui_zhuangshixianquan02_jiemian410472.height = 3;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian410472);
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var enter_Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            enter_Scale9Button = new Scale9Button(texture,enter_Scale9ButtonRect);
            enter_Scale9Button.x = 504;
            enter_Scale9Button.y = 491;
            enter_Scale9Button.width = 160;
            enter_Scale9Button.height = 62;
            this.addQuiackChild(enter_Scale9Button);
            enter_Scale9Button.name = 'enter_Scale9Button';
            enter_Scale9Button.text= 'lable';
            enter_Scale9Button.fontColor= 0xFFFFFF;
            enter_Scale9Button.fontSize= 24;
            emb_7 = new EmbattleShowItem();
            emb_7.x = 431;
            emb_7.y = 102;
            this.addQuiackChild(emb_7);
            emb_4 = new EmbattleShowItem();
            emb_4.x = 535;
            emb_4.y = 102;
            this.addQuiackChild(emb_4);
            emb_1 = new EmbattleShowItem();
            emb_1.x = 639;
            emb_1.y = 102;
            this.addQuiackChild(emb_1);
            emb_8 = new EmbattleShowItem();
            emb_8.x = 431;
            emb_8.y = 206;
            this.addQuiackChild(emb_8);
            emb_5 = new EmbattleShowItem();
            emb_5.x = 535;
            emb_5.y = 206;
            this.addQuiackChild(emb_5);
            emb_2 = new EmbattleShowItem();
            emb_2.x = 639;
            emb_2.y = 206;
            this.addQuiackChild(emb_2);
            emb_9 = new EmbattleShowItem();
            emb_9.x = 431;
            emb_9.y = 308;
            this.addQuiackChild(emb_9);
            emb_6 = new EmbattleShowItem();
            emb_6.x = 535;
            emb_6.y = 308;
            this.addQuiackChild(emb_6);
            emb_3 = new EmbattleShowItem();
            emb_3.x = 639;
            emb_3.y = 308;
            this.addQuiackChild(emb_3);
            txtPowerTitle = new TextField(145,32,'','',21,0xFFFFFF,false);
            txtPowerTitle.touchable = false;
            txtPowerTitle.hAlign= 'right';
            txtPowerTitle.text= '';
            txtPowerTitle.x = 410;
            txtPowerTitle.y = 435;
            this.addQuiackChild(txtPowerTitle);
            txtPower = new TextField(190,32,'','',24,0xFF9900,false);
            txtPower.touchable = false;
            txtPower.hAlign= 'center';
            txtPower.text= '';
            txtPower.x = 563;
            txtPower.y = 435;
            this.addQuiackChild(txtPower);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            list_hero.dispose();
            emb_7.dispose();
            emb_4.dispose();
            emb_1.dispose();
            emb_8.dispose();
            emb_5.dispose();
            emb_2.dispose();
            emb_9.dispose();
            emb_6.dispose();
            emb_3.dispose();
            super.dispose();
        
}
    }
}
