package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import com.view.View;

    public class BattleViewBases extends View
    {
        public var heroIcon_1:Image;
        public var heroIcon_4:Image;
        public var heroIcon_3:Image;
        public var heroIcon_0:Image;
        public var heroIcon_2:Image;
        public var angerBar_0:Sprite;
        public var angerBar_2:Sprite;
        public var angerBar_4:Sprite;
        public var angerBar_3:Sprite;
        public var angerBar_1:Sprite;
        public var heroQuality_0:Image;
        public var heroQuality_4:Image;
        public var heroQuality_3:Image;
        public var heroQuality_2:Image;
        public var heroQuality_1:Image;
        public var textPoints_4:TextField;
        public var textPoints_3:TextField;
        public var textPoints_2:TextField;
        public var textPoints_1:TextField;
        public var textPoints_0:TextField;

        public function BattleViewBases()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture =assetMgr.getTexture('ui_zhandouzhongnuqitiaodi');
            image = new Image(texture);
            image.y = 111;
            image.width = 110;
            image.height = 24;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhandouzhongnuqitiaodi');
            image = new Image(texture);
            image.x = 114;
            image.y = 111;
            image.width = 110;
            image.height = 24;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhandouzhongnuqitiaodi');
            image = new Image(texture);
            image.x = 228;
            image.y = 111;
            image.width = 110;
            image.height = 24;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhandouzhongnuqitiaodi');
            image = new Image(texture);
            image.x = 342;
            image.y = 111;
            image.width = 110;
            image.height = 24;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhandouzhongnuqitiaodi');
            image = new Image(texture);
            image.x = 456;
            image.y = 111;
            image.width = 110;
            image.height = 24;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhandouzhongtouxiangdi');
            image = new Image(texture);
            image.width = 110;
            image.height = 110;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhandouzhongtouxiangdi');
            image = new Image(texture);
            image.x = 114;
            image.width = 110;
            image.height = 110;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhandouzhongtouxiangdi');
            image = new Image(texture);
            image.x = 228;
            image.width = 110;
            image.height = 110;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhandouzhongtouxiangdi');
            image = new Image(texture);
            image.x = 342;
            image.width = 110;
            image.height = 110;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhandouzhongtouxiangdi');
            image = new Image(texture);
            image.x = 456;
            image.width = 110;
            image.height = 110;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_daojukuangdi');
            image = new Image(texture);
            image.x = 5;
            image.y = 5;
            image.width = 98;
            image.height = 98;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_daojukuangdi');
            image = new Image(texture);
            image.x = 461;
            image.y = 5;
            image.width = 98;
            image.height = 98;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_daojukuangdi');
            image = new Image(texture);
            image.x = 347;
            image.y = 5;
            image.width = 98;
            image.height = 98;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_daojukuangdi');
            image = new Image(texture);
            image.x = 233;
            image.y = 5;
            image.width = 98;
            image.height = 98;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_daojukuangdi');
            image = new Image(texture);
            image.x = 119;
            image.y = 5;
            image.width = 98;
            image.height = 98;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_100yingxiongkuang_kong')
            heroIcon_1 = new Image(texture);
            heroIcon_1.x = 119;
            heroIcon_1.y = 5;
            heroIcon_1.width = 97;
            heroIcon_1.height = 98;
            this.addQuiackChild(heroIcon_1);
            heroIcon_1.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_100yingxiongkuang_kong')
            heroIcon_4 = new Image(texture);
            heroIcon_4.x = 461;
            heroIcon_4.y = 5;
            heroIcon_4.width = 97;
            heroIcon_4.height = 98;
            this.addQuiackChild(heroIcon_4);
            heroIcon_4.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_100yingxiongkuang_kong')
            heroIcon_3 = new Image(texture);
            heroIcon_3.x = 347;
            heroIcon_3.y = 5;
            heroIcon_3.width = 97;
            heroIcon_3.height = 98;
            this.addQuiackChild(heroIcon_3);
            heroIcon_3.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_100yingxiongkuang_kong')
            heroIcon_0 = new Image(texture);
            heroIcon_0.x = 5;
            heroIcon_0.y = 5;
            heroIcon_0.width = 97;
            heroIcon_0.height = 98;
            this.addQuiackChild(heroIcon_0);
            heroIcon_0.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_100yingxiongkuang_kong')
            heroIcon_2 = new Image(texture);
            heroIcon_2.x = 233;
            heroIcon_2.y = 5;
            heroIcon_2.width = 97;
            heroIcon_2.height = 98;
            this.addQuiackChild(heroIcon_2);
            heroIcon_2.touchable = false;
            angerBar_0 = new Sprite();
            angerBar_0.y = 111;
            angerBar_0.width = 110;
            angerBar_0.height = 24;
            this.addQuiackChild(angerBar_0);
            angerBar_0.name= 'angerBar_0';
            texture = assetMgr.getTexture('ui_zhandouzhongnuqitiaoding')
            image = new Image(texture);
            image.name= 'angerBar';
            image.width = 110;
            image.height = 24;
            angerBar_0.addQuiackChild(image);
            image.touchable = false;
            angerBar_2 = new Sprite();
            angerBar_2.x = 228;
            angerBar_2.y = 111;
            angerBar_2.width = 110;
            angerBar_2.height = 24;
            this.addQuiackChild(angerBar_2);
            angerBar_2.name= 'angerBar_2';
            texture = assetMgr.getTexture('ui_zhandouzhongnuqitiaoding')
            image = new Image(texture);
            image.name= 'angerBar';
            image.width = 110;
            image.height = 24;
            angerBar_2.addQuiackChild(image);
            image.touchable = false;
            angerBar_4 = new Sprite();
            angerBar_4.x = 456;
            angerBar_4.y = 111;
            angerBar_4.width = 110;
            angerBar_4.height = 24;
            this.addQuiackChild(angerBar_4);
            angerBar_4.name= 'angerBar_4';
            texture = assetMgr.getTexture('ui_zhandouzhongnuqitiaoding')
            image = new Image(texture);
            image.name= 'angerBar';
            image.width = 110;
            image.height = 24;
            angerBar_4.addQuiackChild(image);
            image.touchable = false;
            angerBar_3 = new Sprite();
            angerBar_3.x = 342;
            angerBar_3.y = 111;
            angerBar_3.width = 110;
            angerBar_3.height = 24;
            this.addQuiackChild(angerBar_3);
            angerBar_3.name= 'angerBar_3';
            texture = assetMgr.getTexture('ui_zhandouzhongnuqitiaoding')
            image = new Image(texture);
            image.name= 'angerBar';
            image.width = 110;
            image.height = 24;
            angerBar_3.addQuiackChild(image);
            image.touchable = false;
            angerBar_1 = new Sprite();
            angerBar_1.x = 114;
            angerBar_1.y = 111;
            angerBar_1.width = 110;
            angerBar_1.height = 24;
            this.addQuiackChild(angerBar_1);
            angerBar_1.name= 'angerBar_1';
            texture = assetMgr.getTexture('ui_zhandouzhongnuqitiaoding')
            image = new Image(texture);
            image.name= 'angerBar';
            image.width = 110;
            image.height = 24;
            angerBar_1.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_01')
            heroQuality_0 = new Image(texture);
            heroQuality_0.x = 5;
            heroQuality_0.y = 5;
            heroQuality_0.width = 100;
            heroQuality_0.height = 100;
            this.addQuiackChild(heroQuality_0);
            heroQuality_0.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_01')
            heroQuality_4 = new Image(texture);
            heroQuality_4.x = 461;
            heroQuality_4.y = 5;
            heroQuality_4.width = 100;
            heroQuality_4.height = 100;
            this.addQuiackChild(heroQuality_4);
            heroQuality_4.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_01')
            heroQuality_3 = new Image(texture);
            heroQuality_3.x = 347;
            heroQuality_3.y = 5;
            heroQuality_3.width = 100;
            heroQuality_3.height = 100;
            this.addQuiackChild(heroQuality_3);
            heroQuality_3.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_01')
            heroQuality_2 = new Image(texture);
            heroQuality_2.x = 233;
            heroQuality_2.y = 5;
            heroQuality_2.width = 100;
            heroQuality_2.height = 100;
            this.addQuiackChild(heroQuality_2);
            heroQuality_2.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_01')
            heroQuality_1 = new Image(texture);
            heroQuality_1.x = 119;
            heroQuality_1.y = 5;
            heroQuality_1.width = 100;
            heroQuality_1.height = 100;
            this.addQuiackChild(heroQuality_1);
            heroQuality_1.touchable = false;
            textPoints_4 = new TextField(80,80,'','',18,0xFFFFCC,false);
            textPoints_4.touchable = false;
            textPoints_4.hAlign= 'center';
            textPoints_4.text= '';
            textPoints_4.x = 470;
            textPoints_4.y = 15;
            this.addQuiackChild(textPoints_4);
            textPoints_3 = new TextField(80,80,'','',18,0xFFFFCC,false);
            textPoints_3.touchable = false;
            textPoints_3.hAlign= 'center';
            textPoints_3.text= '';
            textPoints_3.x = 358;
            textPoints_3.y = 15;
            this.addQuiackChild(textPoints_3);
            textPoints_2 = new TextField(80,80,'','',18,0xFFFFCC,false);
            textPoints_2.touchable = false;
            textPoints_2.hAlign= 'center';
            textPoints_2.text= '';
            textPoints_2.x = 245;
            textPoints_2.y = 15;
            this.addQuiackChild(textPoints_2);
            textPoints_1 = new TextField(80,80,'','',18,0xFFFFCC,false);
            textPoints_1.touchable = false;
            textPoints_1.hAlign= 'center';
            textPoints_1.text= '';
            textPoints_1.x = 130;
            textPoints_1.y = 15;
            this.addQuiackChild(textPoints_1);
            textPoints_0 = new TextField(80,80,'','',18,0xFFFFCC,false);
            textPoints_0.touchable = false;
            textPoints_0.hAlign= 'center';
            textPoints_0.text= '';
            textPoints_0.x = 16;
            textPoints_0.y = 15;
            this.addQuiackChild(textPoints_0);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            angerBar_0.dispose();
            angerBar_2.dispose();
            angerBar_4.dispose();
            angerBar_3.dispose();
            angerBar_1.dispose();
            super.dispose();
        
}
    }
}
