package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.view.View;

    public class BattleVideoRankBase extends View
    {
        public var btn_menu1:Button;
        public var bgImage:Scale9Image;
        public var bg0:Scale9Image;
        public var bg1:Scale9Image;
        public var bg2:Scale9Image;
        public var bgImage0:Scale9Image;
        public var bgImage1:Scale9Image;
        public var bgImage2:Scale9Image;
        public var look2_Scale9Button:Scale9Button;
        public var look1_Scale9Button:Scale9Button;
        public var look0_Scale9Button:Scale9Button;
        public var btn_menu:Button;
        public var text_Help:TextField;
        public var ico_hero0:Image;
        public var ico_hero2:Image;
        public var ico_hero1:Image;
        public var txt_name0:TextField;
        public var txt_power0:TextField;
        public var txt_name1:TextField;
        public var txt_power1:TextField;
        public var txt_name2:TextField;
        public var txt_power2:TextField;

        public function BattleVideoRankBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_zhuangshixianquan04_jiemian');
            btn_menu1 = new Button(texture);
            btn_menu1.name= 'btn_menu1';
            btn_menu1.x = 511;
            btn_menu1.y = 75;
            btn_menu1.width = 61;
            btn_menu1.height = 174;
            this.addQuiackChild(btn_menu1);
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var bgImageRect:Rectangle = new Rectangle(68,64,6,6);
            var bgImage9ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImageRect);
            bgImage = new Scale9Image(bgImage9ScaleTexture);
            bgImage.x = -50;
            bgImage.width = 592;
            bgImage.height = 428;
            this.addQuiackChild(bgImage);
            texture = assetMgr.getTexture('ui_danxiangkuangdi');
            var bg0Rect:Rectangle = new Rectangle(18,32,34,2);
            var bg09ScaleTexture:Scale9Textures = new Scale9Textures(texture,bg0Rect);
            bg0 = new Scale9Image(bg09ScaleTexture);
            bg0.x = 13;
            bg0.y = 37;
            bg0.width = 489;
            bg0.height = 101;
            this.addQuiackChild(bg0);
            texture = assetMgr.getTexture('ui_danxiangkuangdi');
            var bg1Rect:Rectangle = new Rectangle(18,32,34,2);
            var bg19ScaleTexture:Scale9Textures = new Scale9Textures(texture,bg1Rect);
            bg1 = new Scale9Image(bg19ScaleTexture);
            bg1.x = 13;
            bg1.y = 160;
            bg1.width = 489;
            bg1.height = 101;
            this.addQuiackChild(bg1);
            texture = assetMgr.getTexture('ui_danxiangkuangdi');
            var bg2Rect:Rectangle = new Rectangle(18,32,34,2);
            var bg29ScaleTexture:Scale9Textures = new Scale9Textures(texture,bg2Rect);
            bg2 = new Scale9Image(bg29ScaleTexture);
            bg2.x = 13;
            bg2.y = 283;
            bg2.width = 489;
            bg2.height = 101;
            this.addQuiackChild(bg2);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage0Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage09ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage0Rect);
            bgImage0 = new Scale9Image(bgImage09ScaleTexture);
            bgImage0.x = 121;
            bgImage0.y = 46;
            bgImage0.width = 373;
            bgImage0.height = 41;
            this.addQuiackChild(bgImage0);
            texture =assetMgr.getTexture('ui_dingbuxinxi_01_anniu');
            image = new Image(texture);
            image.x = 168;
            image.y = 93;
            image.width = 166;
            image.height = 38;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhandouli02_tubiao');
            image = new Image(texture);
            image.x = 177;
            image.y = 98;
            image.width = 25;
            image.height = 26;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage1Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage19ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage1Rect);
            bgImage1 = new Scale9Image(bgImage19ScaleTexture);
            bgImage1.x = 121;
            bgImage1.y = 169;
            bgImage1.width = 373;
            bgImage1.height = 41;
            this.addQuiackChild(bgImage1);
            texture =assetMgr.getTexture('ui_dingbuxinxi_01_anniu');
            image = new Image(texture);
            image.x = 168;
            image.y = 216;
            image.width = 166;
            image.height = 38;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhandouli02_tubiao');
            image = new Image(texture);
            image.x = 177;
            image.y = 221;
            image.width = 25;
            image.height = 26;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_dingbuxinxi_01_anniu');
            image = new Image(texture);
            image.x = 168;
            image.y = 339;
            image.width = 166;
            image.height = 38;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhandouli02_tubiao');
            image = new Image(texture);
            image.x = 177;
            image.y = 344;
            image.width = 25;
            image.height = 26;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_touxiangdi01_01');
            image = new Image(texture);
            image.x = 80;
            image.y = 290;
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_touxiangdi01_01');
            image = new Image(texture);
            image.x = 80;
            image.y = 168;
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_touxiangdi01_01');
            image = new Image(texture);
            image.x = 80;
            image.y = 44;
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_paihangshuzi_1');
            image = new Image(texture);
            image.x = 30;
            image.y = 67;
            image.width = 37;
            image.height = 47;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_paihangshuzi_2');
            image = new Image(texture);
            image.x = 30;
            image.y = 190;
            image.width = 37;
            image.height = 47;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage2Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage29ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage2Rect);
            bgImage2 = new Scale9Image(bgImage29ScaleTexture);
            bgImage2.x = 121;
            bgImage2.y = 292;
            bgImage2.width = 373;
            bgImage2.height = 41;
            this.addQuiackChild(bgImage2);
            texture =assetMgr.getTexture('ui_paihangshuzi_3');
            image = new Image(texture);
            image.x = 30;
            image.y = 313;
            image.width = 37;
            image.height = 47;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_hong02_01_anniu');
            var look2_Scale9ButtonRect:Rectangle = new Rectangle(25,10,50,20);
            look2_Scale9Button = new Scale9Button(texture,look2_Scale9ButtonRect);
            look2_Scale9Button.x = 339;
            look2_Scale9Button.y = 338;
            look2_Scale9Button.width = 152;
            look2_Scale9Button.height = 39;
            this.addQuiackChild(look2_Scale9Button);
            look2_Scale9Button.name = 'look2_Scale9Button';
            look2_Scale9Button.text= 'lable';
            look2_Scale9Button.fontColor= 0xFFFFFFB4;
            look2_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_hong02_01_anniu');
            var look1_Scale9ButtonRect:Rectangle = new Rectangle(25,10,50,20);
            look1_Scale9Button = new Scale9Button(texture,look1_Scale9ButtonRect);
            look1_Scale9Button.x = 339;
            look1_Scale9Button.y = 215;
            look1_Scale9Button.width = 152;
            look1_Scale9Button.height = 39;
            this.addQuiackChild(look1_Scale9Button);
            look1_Scale9Button.name = 'look1_Scale9Button';
            look1_Scale9Button.text= 'lable';
            look1_Scale9Button.fontColor= 0xFFFFFFB4;
            look1_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_hong02_01_anniu');
            var look0_Scale9ButtonRect:Rectangle = new Rectangle(25,10,50,20);
            look0_Scale9Button = new Scale9Button(texture,look0_Scale9ButtonRect);
            look0_Scale9Button.x = 339;
            look0_Scale9Button.y = 92;
            look0_Scale9Button.width = 152;
            look0_Scale9Button.height = 39;
            this.addQuiackChild(look0_Scale9Button);
            look0_Scale9Button.name = 'look0_Scale9Button';
            look0_Scale9Button.text= 'lable';
            look0_Scale9Button.fontColor= 0xFFFFFFB4;
            look0_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('icon_huchucaozuolan02_tubiao');
            btn_menu = new Button(texture);
            btn_menu.name= 'btn_menu';
            btn_menu.x = 520;
            btn_menu.y = 55;
            btn_menu.width = 52;
            btn_menu.height = 62;
            this.addQuiackChild(btn_menu);
            text_Help = new TextField(28,119,'','',24,0xFFFFFF,false);
            text_Help.touchable = false;
            text_Help.hAlign= 'center';
            text_Help.text= '';
            text_Help.x = 530;
            text_Help.y = 116;
            this.addQuiackChild(text_Help);
            texture = assetMgr.getTexture('photo_501')
            ico_hero0 = new Image(texture);
            ico_hero0.x = 88;
            ico_hero0.y = 52;
            ico_hero0.width = 72;
            ico_hero0.height = 72;
            this.addQuiackChild(ico_hero0);
            ico_hero0.touchable = false;
            texture = assetMgr.getTexture('photo_501')
            ico_hero2 = new Image(texture);
            ico_hero2.x = 89;
            ico_hero2.y = 297;
            ico_hero2.width = 72;
            ico_hero2.height = 72;
            this.addQuiackChild(ico_hero2);
            ico_hero2.touchable = false;
            texture = assetMgr.getTexture('photo_501')
            ico_hero1 = new Image(texture);
            ico_hero1.x = 90;
            ico_hero1.y = 175;
            ico_hero1.width = 72;
            ico_hero1.height = 72;
            this.addQuiackChild(ico_hero1);
            ico_hero1.touchable = false;
            texture =assetMgr.getTexture('ui_touxiangdi01_02');
            image = new Image(texture);
            image.x = 80;
            image.y = 44;
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_touxiangdi01_02');
            image = new Image(texture);
            image.x = 80;
            image.y = 290;
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_touxiangdi01_02');
            image = new Image(texture);
            image.x = 80;
            image.y = 168;
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_name0 = new TextField(280,31,'','',24,0xFFFFFF,false);
            txt_name0.touchable = false;
            txt_name0.hAlign= 'center';
            txt_name0.text= '';
            txt_name0.x = 173;
            txt_name0.y = 51;
            this.addQuiackChild(txt_name0);
            txt_power0 = new TextField(120,31,'','',20,0xFFFFFF,false);
            txt_power0.touchable = false;
            txt_power0.hAlign= 'center';
            txt_power0.text= '';
            txt_power0.x = 204;
            txt_power0.y = 97;
            this.addQuiackChild(txt_power0);
            txt_name1 = new TextField(280,31,'','',24,0xFFFFFF,false);
            txt_name1.touchable = false;
            txt_name1.hAlign= 'center';
            txt_name1.text= '';
            txt_name1.x = 173;
            txt_name1.y = 173;
            this.addQuiackChild(txt_name1);
            txt_power1 = new TextField(120,31,'','',20,0xFFFFFF,false);
            txt_power1.touchable = false;
            txt_power1.hAlign= 'center';
            txt_power1.text= '';
            txt_power1.x = 204;
            txt_power1.y = 220;
            this.addQuiackChild(txt_power1);
            txt_name2 = new TextField(280,31,'','',24,0xFFFFFF,false);
            txt_name2.touchable = false;
            txt_name2.hAlign= 'center';
            txt_name2.text= '';
            txt_name2.x = 173;
            txt_name2.y = 297;
            this.addQuiackChild(txt_name2);
            txt_power2 = new TextField(120,31,'','',20,0xFFFFFF,false);
            txt_power2.touchable = false;
            txt_power2.hAlign= 'center';
            txt_power2.text= '';
            txt_power2.x = 204;
            txt_power2.y = 343;
            this.addQuiackChild(txt_power2);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            btn_menu1.dispose();
            btn_menu.dispose();
            super.dispose();
        
}
    }
}
