package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.view.View;

    public class DestinyViewBase extends View
    {
        public var fushBtn:Button;
        public var heroIcon_0:Sprite;
        public var heroIcon_7:Sprite;
        public var heroIcon_6:Sprite;
        public var heroIcon_1:Sprite;
        public var heroIcon_5:Sprite;
        public var heroIcon_2:Sprite;
        public var heroIcon_3:Sprite;
        public var heroIcon_4:Sprite;
        public var buyBtn2_Scale9Button:Scale9Button;
        public var buyNum_0:TextField;
        public var buyNum_1:TextField;
        public var buyIcon_0:Image;
        public var buyIcon_1:Image;
        public var buyBtn1_Scale9Button:Scale9Button;
        public var buyBtn0_Scale9Button:Scale9Button;
        public var ui_dicengying01_jiemian618480:Scale9Image;
        public var buyNum_2:TextField;
        public var buyIcon_2:Image;
        public var leftTmies:TextField;
        public var coinFushTime:TextField;
        public var fushTimeTitle:TextField;
        public var fushTime:TextField;

        public function DestinyViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture =assetMgr.getTexture('ui_zhuanpandi03_tietu');
            image = new Image(texture);
            image.x = 187;
            image.y = 83;
            image.width = 445;
            image.height = 445;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_shuaxin02_01_anniu');
            fushBtn = new Button(texture);
            fushBtn.name= 'fushBtn';
            fushBtn.x = 353;
            fushBtn.y = 249;
            fushBtn.width = 113;
            fushBtn.height = 113;
            this.addQuiackChild(fushBtn);
            heroIcon_0 = new Sprite();
            heroIcon_0.x = 226;
            heroIcon_0.y = 143;
            heroIcon_0.width = 104;
            heroIcon_0.height = 104;
            this.addQuiackChild(heroIcon_0);
            heroIcon_0.name= 'heroIcon_0';
            texture =assetMgr.getTexture('ui_touxiangdi01_01');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_0.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_525')
            image = new Image(texture);
            image.name= 'img';
            image.x = 6;
            image.y = 6;
            image.width = 72;
            image.height = 72;
            heroIcon_0.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('yuanxingtouxiangkuangfaguang')
            image = new Image(texture);
            image.name= 'light';
            image.x = -10;
            image.y = -10;
            image.width = 104;
            image.height = 104;
            heroIcon_0.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_touxiangdi01_02');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_0.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yingxionghun_tubiao_02');
            image = new Image(texture);
            image.x = 54;
            image.y = 54;
            image.width = 30;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_0.addQuiackChild(image);
            heroIcon_7 = new Sprite();
            heroIcon_7.x = 177;
            heroIcon_7.y = 263;
            heroIcon_7.width = 104;
            heroIcon_7.height = 104;
            this.addQuiackChild(heroIcon_7);
            heroIcon_7.name= 'heroIcon_7';
            texture =assetMgr.getTexture('ui_touxiangdi01_01');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_7.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_525')
            image = new Image(texture);
            image.name= 'img';
            image.x = 6;
            image.y = 6;
            image.width = 72;
            image.height = 72;
            heroIcon_7.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('yuanxingtouxiangkuangfaguang')
            image = new Image(texture);
            image.name= 'light';
            image.x = -10;
            image.y = -10;
            image.width = 104;
            image.height = 104;
            heroIcon_7.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_touxiangdi01_02');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_7.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yingxionghun_tubiao_02');
            image = new Image(texture);
            image.x = 54;
            image.y = 54;
            image.width = 30;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_7.addQuiackChild(image);
            heroIcon_6 = new Sprite();
            heroIcon_6.x = 227;
            heroIcon_6.y = 385;
            heroIcon_6.width = 104;
            heroIcon_6.height = 104;
            this.addQuiackChild(heroIcon_6);
            heroIcon_6.name= 'heroIcon_6';
            texture =assetMgr.getTexture('ui_touxiangdi01_01');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_6.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_525')
            image = new Image(texture);
            image.name= 'img';
            image.x = 6;
            image.y = 6;
            image.width = 72;
            image.height = 72;
            heroIcon_6.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('yuanxingtouxiangkuangfaguang')
            image = new Image(texture);
            image.name= 'light';
            image.x = -10;
            image.y = -10;
            image.width = 104;
            image.height = 104;
            heroIcon_6.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_touxiangdi01_02');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_6.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yingxionghun_tubiao_02');
            image = new Image(texture);
            image.x = 54;
            image.y = 54;
            image.width = 30;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_6.addQuiackChild(image);
            heroIcon_1 = new Sprite();
            heroIcon_1.x = 359;
            heroIcon_1.y = 85;
            heroIcon_1.width = 104;
            heroIcon_1.height = 104;
            this.addQuiackChild(heroIcon_1);
            heroIcon_1.name= 'heroIcon_1';
            texture =assetMgr.getTexture('ui_touxiangdi01_01');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_1.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_525')
            image = new Image(texture);
            image.name= 'img';
            image.x = 6;
            image.y = 6;
            image.width = 72;
            image.height = 72;
            heroIcon_1.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('yuanxingtouxiangkuangfaguang')
            image = new Image(texture);
            image.name= 'light';
            image.x = -10;
            image.y = -10;
            image.width = 104;
            image.height = 104;
            heroIcon_1.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_touxiangdi01_02');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_1.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yingxionghun_tubiao_02');
            image = new Image(texture);
            image.x = 54;
            image.y = 54;
            image.width = 30;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_1.addQuiackChild(image);
            heroIcon_5 = new Sprite();
            heroIcon_5.x = 360;
            heroIcon_5.y = 443;
            heroIcon_5.width = 104;
            heroIcon_5.height = 104;
            this.addQuiackChild(heroIcon_5);
            heroIcon_5.name= 'heroIcon_5';
            texture =assetMgr.getTexture('ui_touxiangdi01_01');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_5.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_525')
            image = new Image(texture);
            image.name= 'img';
            image.x = 6;
            image.y = 6;
            image.width = 72;
            image.height = 72;
            heroIcon_5.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('yuanxingtouxiangkuangfaguang')
            image = new Image(texture);
            image.name= 'light';
            image.x = -10;
            image.y = -10;
            image.width = 104;
            image.height = 104;
            heroIcon_5.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_touxiangdi01_02');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_5.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yingxionghun_tubiao_02');
            image = new Image(texture);
            image.x = 54;
            image.y = 54;
            image.width = 30;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_5.addQuiackChild(image);
            heroIcon_2 = new Sprite();
            heroIcon_2.x = 488;
            heroIcon_2.y = 143;
            heroIcon_2.width = 104;
            heroIcon_2.height = 104;
            this.addQuiackChild(heroIcon_2);
            heroIcon_2.name= 'heroIcon_2';
            texture =assetMgr.getTexture('ui_touxiangdi01_01');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_2.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_525')
            image = new Image(texture);
            image.name= 'img';
            image.x = 6;
            image.y = 6;
            image.width = 72;
            image.height = 72;
            heroIcon_2.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('yuanxingtouxiangkuangfaguang')
            image = new Image(texture);
            image.name= 'light';
            image.x = -10;
            image.y = -10;
            image.width = 104;
            image.height = 104;
            heroIcon_2.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_touxiangdi01_02');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_2.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yingxionghun_tubiao_02');
            image = new Image(texture);
            image.x = 54;
            image.y = 54;
            image.width = 30;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_2.addQuiackChild(image);
            heroIcon_3 = new Sprite();
            heroIcon_3.x = 535;
            heroIcon_3.y = 262;
            heroIcon_3.width = 104;
            heroIcon_3.height = 104;
            this.addQuiackChild(heroIcon_3);
            heroIcon_3.name= 'heroIcon_3';
            texture =assetMgr.getTexture('ui_touxiangdi01_01');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_3.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_525')
            image = new Image(texture);
            image.name= 'img';
            image.x = 6;
            image.y = 6;
            image.width = 72;
            image.height = 72;
            heroIcon_3.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('yuanxingtouxiangkuangfaguang')
            image = new Image(texture);
            image.name= 'light';
            image.x = -10;
            image.y = -10;
            image.width = 104;
            image.height = 104;
            heroIcon_3.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_touxiangdi01_02');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_3.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yingxionghun_tubiao_02');
            image = new Image(texture);
            image.x = 54;
            image.y = 54;
            image.width = 30;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_3.addQuiackChild(image);
            heroIcon_4 = new Sprite();
            heroIcon_4.x = 489;
            heroIcon_4.y = 386;
            heroIcon_4.width = 104;
            heroIcon_4.height = 104;
            this.addQuiackChild(heroIcon_4);
            heroIcon_4.name= 'heroIcon_4';
            texture =assetMgr.getTexture('ui_touxiangdi01_01');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_4.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_525')
            image = new Image(texture);
            image.name= 'img';
            image.x = 6;
            image.y = 6;
            image.width = 72;
            image.height = 72;
            heroIcon_4.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('yuanxingtouxiangkuangfaguang')
            image = new Image(texture);
            image.name= 'light';
            image.x = -10;
            image.y = -10;
            image.width = 104;
            image.height = 104;
            heroIcon_4.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_touxiangdi01_02');
            image = new Image(texture);
            image.width = 84;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_4.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yingxionghun_tubiao_02');
            image = new Image(texture);
            image.x = 54;
            image.y = 54;
            image.width = 30;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_4.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var buyBtn2_Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            buyBtn2_Scale9Button = new Scale9Button(texture,buyBtn2_Scale9ButtonRect);
            buyBtn2_Scale9Button.x = 681;
            buyBtn2_Scale9Button.y = 371;
            buyBtn2_Scale9Button.width = 200;
            buyBtn2_Scale9Button.height = 70;
            this.addQuiackChild(buyBtn2_Scale9Button);
            buyBtn2_Scale9Button.name = 'buyBtn2_Scale9Button';
            buyBtn2_Scale9Button.text= '0';
            buyBtn2_Scale9Button.fontColor= 0xffffff;
            buyBtn2_Scale9Button.fontSize= 24;
            buyNum_0 = new TextField(75,33,'','',26,0xffffff,false);
            buyNum_0.touchable = false;
            buyNum_0.hAlign= 'center';
            buyNum_0.text= '';
            buyNum_0.x = 726;
            buyNum_0.y = 438;
            this.addQuiackChild(buyNum_0);
            buyNum_1 = new TextField(75,33,'','',26,0xffffff,false);
            buyNum_1.touchable = false;
            buyNum_1.hAlign= 'center';
            buyNum_1.text= '';
            buyNum_1.x = 726;
            buyNum_1.y = 312;
            this.addQuiackChild(buyNum_1);
            texture = assetMgr.getTexture('ui_zuanshi01_tubiao')
            buyIcon_0 = new Image(texture);
            buyIcon_0.x = 805;
            buyIcon_0.y = 441;
            buyIcon_0.width = 25;
            buyIcon_0.height = 26;
            this.addQuiackChild(buyIcon_0);
            buyIcon_0.touchable = false;
            texture = assetMgr.getTexture('ui_zuanshi01_tubiao')
            buyIcon_1 = new Image(texture);
            buyIcon_1.x = 805;
            buyIcon_1.y = 315;
            buyIcon_1.width = 25;
            buyIcon_1.height = 26;
            this.addQuiackChild(buyIcon_1);
            buyIcon_1.touchable = false;
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var buyBtn1_Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            buyBtn1_Scale9Button = new Scale9Button(texture,buyBtn1_Scale9ButtonRect);
            buyBtn1_Scale9Button.x = 681;
            buyBtn1_Scale9Button.y = 245;
            buyBtn1_Scale9Button.width = 200;
            buyBtn1_Scale9Button.height = 70;
            this.addQuiackChild(buyBtn1_Scale9Button);
            buyBtn1_Scale9Button.name = 'buyBtn1_Scale9Button';
            buyBtn1_Scale9Button.text= '0';
            buyBtn1_Scale9Button.fontColor= 0xffffff;
            buyBtn1_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_hong03_01_anniu');
            var buyBtn0_Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            buyBtn0_Scale9Button = new Scale9Button(texture,buyBtn0_Scale9ButtonRect);
            buyBtn0_Scale9Button.x = 681;
            buyBtn0_Scale9Button.y = 119;
            buyBtn0_Scale9Button.width = 200;
            buyBtn0_Scale9Button.height = 70;
            this.addQuiackChild(buyBtn0_Scale9Button);
            buyBtn0_Scale9Button.name = 'buyBtn0_Scale9Button';
            buyBtn0_Scale9Button.text= 'lable';
            buyBtn0_Scale9Button.fontColor= 0xffffff;
            buyBtn0_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_dicengying01_jiemian');
            var ui_dicengying01_jiemian618480Rect:Rectangle = new Rectangle(26,17,12,1);
            var ui_dicengying01_jiemian6184809ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_dicengying01_jiemian618480Rect);
            ui_dicengying01_jiemian618480 = new Scale9Image(ui_dicengying01_jiemian6184809ScaleTexture);
            ui_dicengying01_jiemian618480.x = 618;
            ui_dicengying01_jiemian618480.y = 480;
            ui_dicengying01_jiemian618480.width = 300;
            ui_dicengying01_jiemian618480.height = 48;
            this.addQuiackChild(ui_dicengying01_jiemian618480);
            buyNum_2 = new TextField(75,33,'','',26,0xffffff,false);
            buyNum_2.touchable = false;
            buyNum_2.hAlign= 'center';
            buyNum_2.text= '';
            buyNum_2.x = 726;
            buyNum_2.y = 184;
            this.addQuiackChild(buyNum_2);
            texture = assetMgr.getTexture('ui_jinbi01_tubiao')
            buyIcon_2 = new Image(texture);
            buyIcon_2.x = 805;
            buyIcon_2.y = 187;
            buyIcon_2.width = 25;
            buyIcon_2.height = 26;
            this.addQuiackChild(buyIcon_2);
            buyIcon_2.touchable = false;
            leftTmies = new TextField(80,33,'','',26,0xffffff,false);
            leftTmies.touchable = false;
            leftTmies.hAlign= 'center';
            leftTmies.text= '';
            leftTmies.x = 683;
            leftTmies.y = 84;
            this.addQuiackChild(leftTmies);
            coinFushTime = new TextField(111,34,'','',26,0x00ff00,false);
            coinFushTime.touchable = false;
            coinFushTime.hAlign= 'center';
            coinFushTime.text= '';
            coinFushTime.x = 767;
            coinFushTime.y = 84;
            this.addQuiackChild(coinFushTime);
            fushTimeTitle = new TextField(128,34,'','',26,0xffffff,false);
            fushTimeTitle.touchable = false;
            fushTimeTitle.hAlign= 'right';
            fushTimeTitle.text= '';
            fushTimeTitle.x = 635;
            fushTimeTitle.y = 488;
            this.addQuiackChild(fushTimeTitle);
            fushTime = new TextField(135,34,'','',26,0x00ff00,false);
            fushTime.touchable = false;
            fushTime.hAlign= 'center';
            fushTime.text= '';
            fushTime.x = 766;
            fushTime.y = 488;
            this.addQuiackChild(fushTime);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            fushBtn.dispose();
            heroIcon_0.dispose();
            heroIcon_7.dispose();
            heroIcon_6.dispose();
            heroIcon_1.dispose();
            heroIcon_5.dispose();
            heroIcon_2.dispose();
            heroIcon_3.dispose();
            heroIcon_4.dispose();
            super.dispose();
        
}
    }
}
