package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;

    public class DialogBackground1Base extends Sprite
    {

        public function DialogBackground1Base()
        {
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 72;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 216;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 504;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 432;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 360;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 288;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 144;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 576;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 960;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 960;
            image.y = 72;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 960;
            image.y = 216;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 960;
            image.y = 504;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 960;
            image.y = 432;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 960;
            image.y = 360;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 960;
            image.y = 288;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 960;
            image.y = 144;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 960;
            image.y = 576;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
        }
    }
}
