package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.controls.List;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.dialog.TabDialog;

    public class EmailDlgBase extends TabDialog
    {
        public var ui_tanchukuangdi01_jiemian014:Scale9Image;
        public var btn_close:Button;
        public var bgImage0:Scale9Image;
        public var get__Scale9Button:Scale9Button;
        public var ui_zhuangshixianquan03_jiemian47088:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian484102:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian488146:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian484205:Scale9Image;
        public var txt_des:TextField;
        public var txt_des2:TextField;
        public var txt_sender:TextField;
        public var txt_des1:TextField;
        public var txt_name:TextField;
        public var grid:Scale9Image;
        public var goods0:Sprite;
        public var goods2:Sprite;
        public var goods1:Sprite;
        public var list_mail:List;

        public function EmailDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tanchukuangdi01_jiemian');
            var ui_tanchukuangdi01_jiemian014Rect:Rectangle = new Rectangle(420,240,4,4);
            var ui_tanchukuangdi01_jiemian0149ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tanchukuangdi01_jiemian014Rect);
            ui_tanchukuangdi01_jiemian014 = new Scale9Image(ui_tanchukuangdi01_jiemian0149ScaleTexture);
            ui_tanchukuangdi01_jiemian014.y = 14;
            ui_tanchukuangdi01_jiemian014.width = 960;
            ui_tanchukuangdi01_jiemian014.height = 580;
            this.addQuiackChild(ui_tanchukuangdi01_jiemian014);
            texture =assetMgr.getTexture('ui_taitoudi01_jiemian');
            image = new Image(texture);
            image.x = 120;
            image.y = 10;
            image.width = 720;
            image.height = 56;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_mingzidi01');
            image = new Image(texture);
            image.x = 254;
            image.y = 20;
            image.width = 452;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_guanbi01_anniu');
            btn_close = new Button(texture);
            btn_close.name= 'btn_close';
            btn_close.x = 866;
            btn_close.width = 72;
            btn_close.height = 76;
            this.addQuiackChild(btn_close);
            texture =assetMgr.getTexture('ui_youxiang_taitou_wenzi');
            image = new Image(texture);
            image.x = 423;
            image.y = 20;
            image.width = 115;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage0Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage09ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage0Rect);
            bgImage0 = new Scale9Image(bgImage09ScaleTexture);
            bgImage0.x = 45;
            bgImage0.y = 92;
            bgImage0.width = 422;
            bgImage0.height = 450;
            this.addQuiackChild(bgImage0);
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var get__Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            get__Scale9Button = new Scale9Button(texture,get__Scale9ButtonRect);
            get__Scale9Button.x = 609;
            get__Scale9Button.y = 475;
            get__Scale9Button.width = 186;
            get__Scale9Button.height = 70;
            this.addQuiackChild(get__Scale9Button);
            get__Scale9Button.name = 'get__Scale9Button';
            get__Scale9Button.text= 'label';
            get__Scale9Button.fontColor= 0xFFFFFF;
            get__Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_zhuangshixianquan03_jiemian');
            var ui_zhuangshixianquan03_jiemian47088Rect:Rectangle = new Rectangle(30,30,10,10);
            var ui_zhuangshixianquan03_jiemian470889ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan03_jiemian47088Rect);
            ui_zhuangshixianquan03_jiemian47088 = new Scale9Image(ui_zhuangshixianquan03_jiemian470889ScaleTexture);
            ui_zhuangshixianquan03_jiemian47088.x = 470;
            ui_zhuangshixianquan03_jiemian47088.y = 88;
            ui_zhuangshixianquan03_jiemian47088.width = 462;
            ui_zhuangshixianquan03_jiemian47088.height = 118;
            this.addQuiackChild(ui_zhuangshixianquan03_jiemian47088);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian484102Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian4841029ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian484102Rect);
            ui_zhuangshixianquan01_jiemian484102 = new Scale9Image(ui_zhuangshixianquan01_jiemian4841029ScaleTexture);
            ui_zhuangshixianquan01_jiemian484102.x = 484;
            ui_zhuangshixianquan01_jiemian484102.y = 102;
            ui_zhuangshixianquan01_jiemian484102.width = 434;
            ui_zhuangshixianquan01_jiemian484102.height = 90;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian484102);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian488146Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian4881469ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian488146Rect);
            ui_zhuangshixianquan02_jiemian488146 = new Scale9Image(ui_zhuangshixianquan02_jiemian4881469ScaleTexture);
            ui_zhuangshixianquan02_jiemian488146.x = 488;
            ui_zhuangshixianquan02_jiemian488146.y = 146;
            ui_zhuangshixianquan02_jiemian488146.width = 426;
            ui_zhuangshixianquan02_jiemian488146.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian488146);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 909;
            image.y = 105;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 909;
            image.y = 189;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 493;
            image.y = 105;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 493;
            image.y = 189;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 495;
            image.y = 110;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 907;
            image.y = 110;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 495;
            image.y = 184;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 907;
            image.y = 184;
            image.width = 8;
            image.height = 33;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian484205Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian4842059ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian484205Rect);
            ui_zhuangshixianquan01_jiemian484205 = new Scale9Image(ui_zhuangshixianquan01_jiemian4842059ScaleTexture);
            ui_zhuangshixianquan01_jiemian484205.x = 484;
            ui_zhuangshixianquan01_jiemian484205.y = 205;
            ui_zhuangshixianquan01_jiemian484205.width = 435;
            ui_zhuangshixianquan01_jiemian484205.height = 260;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian484205);
            txt_des = new TextField(409,140,'','',21,0xFFFFFF,false);
            txt_des.touchable = false;
            txt_des.hAlign= 'left';
            txt_des.text= '';
            txt_des.x = 497;
            txt_des.y = 213;
            this.addQuiackChild(txt_des);
            txt_des2 = new TextField(110,31,'','',24,0x999999,false);
            txt_des2.touchable = false;
            txt_des2.hAlign= 'right';
            txt_des2.text= '';
            txt_des2.x = 519;
            txt_des2.y = 153;
            this.addQuiackChild(txt_des2);
            txt_sender = new TextField(250,31,'','',24,0xFFFFFF,false);
            txt_sender.touchable = false;
            txt_sender.hAlign= 'center';
            txt_sender.text= '';
            txt_sender.x = 633;
            txt_sender.y = 153;
            this.addQuiackChild(txt_sender);
            txt_des1 = new TextField(110,31,'','',24,0x999999,false);
            txt_des1.touchable = false;
            txt_des1.hAlign= 'right';
            txt_des1.text= '';
            txt_des1.x = 519;
            txt_des1.y = 110;
            this.addQuiackChild(txt_des1);
            txt_name = new TextField(250,31,'','',24,0xFFFFFF,false);
            txt_name.touchable = false;
            txt_name.hAlign= 'center';
            txt_name.text= '';
            txt_name.x = 633;
            txt_name.y = 110;
            this.addQuiackChild(txt_name);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var gridRect:Rectangle = new Rectangle(12,12,20,20);
            var grid9ScaleTexture:Scale9Textures = new Scale9Textures(texture,gridRect);
            grid = new Scale9Image(grid9ScaleTexture);
            grid.x = 486;
            grid.y = 358;
            grid.width = 431;
            grid.height = 105;
            this.addQuiackChild(grid);
            goods0 = new Sprite();
            goods0.x = 518;
            goods0.y = 361;
            goods0.width = 98;
            goods0.height = 98;
            this.addQuiackChild(goods0);
            goods0.name= 'goods0';
            texture = assetMgr.getTexture('ui_daojukuangdi');
            button = new Button(texture);
            button.name= 'bg';
            button.width = 98;
            button.height = 98;
            goods0.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_button_mail')
            image = new Image(texture);
            image.name= 'icon';
            image.x = 5;
            image.y = 5;
            image.width = 89;
            image.height = 89;
            goods0.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            image = new Image(texture);
            image.name= 'quality';
            image.width = 98;
            image.height = 98;
            goods0.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxionghun_tubiao_02')
            image = new Image(texture);
            image.name= 'hun';
            image.x = 58;
            image.y = 10;
            image.width = 30;
            image.height = 30;
            goods0.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(86,30,'','',21,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 9;
            textField.y = 62;
            textField.hAlign= 'left';
            textField.text= '';
            textField.name= 'txt_num';
            goods0.addQuiackChild(textField);
            goods2 = new Sprite();
            goods2.x = 786;
            goods2.y = 361;
            goods2.width = 98;
            goods2.height = 98;
            this.addQuiackChild(goods2);
            goods2.name= 'goods2';
            texture = assetMgr.getTexture('ui_daojukuangdi');
            button = new Button(texture);
            button.name= 'bg';
            button.width = 98;
            button.height = 98;
            goods2.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_button_mail')
            image = new Image(texture);
            image.name= 'icon';
            image.x = 5;
            image.y = 5;
            image.width = 89;
            image.height = 89;
            goods2.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            image = new Image(texture);
            image.name= 'quality';
            image.width = 98;
            image.height = 98;
            goods2.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxionghun_tubiao_02')
            image = new Image(texture);
            image.name= 'hun';
            image.x = 58;
            image.y = 10;
            image.width = 30;
            image.height = 30;
            goods2.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(86,30,'','',21,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 9;
            textField.y = 62;
            textField.hAlign= 'left';
            textField.text= '';
            textField.name= 'txt_num';
            goods2.addQuiackChild(textField);
            goods1 = new Sprite();
            goods1.x = 652;
            goods1.y = 361;
            goods1.width = 98;
            goods1.height = 98;
            this.addQuiackChild(goods1);
            goods1.name= 'goods1';
            texture = assetMgr.getTexture('ui_daojukuangdi');
            button = new Button(texture);
            button.name= 'bg';
            button.width = 98;
            button.height = 98;
            goods1.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_button_mail')
            image = new Image(texture);
            image.name= 'icon';
            image.x = 5;
            image.y = 5;
            image.width = 89;
            image.height = 89;
            goods1.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            image = new Image(texture);
            image.name= 'quality';
            image.width = 98;
            image.height = 98;
            goods1.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxionghun_tubiao_02')
            image = new Image(texture);
            image.name= 'hun';
            image.x = 58;
            image.y = 10;
            image.width = 30;
            image.height = 30;
            goods1.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(86,30,'','',21,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 9;
            textField.y = 62;
            textField.hAlign= 'left';
            textField.text= '';
            textField.name= 'txt_num';
            goods1.addQuiackChild(textField);
            list_mail = new List();
            list_mail.x = 48;
            list_mail.y = 99;
            list_mail.width = 416;
            list_mail.height = 437;
            this.addQuiackChild(list_mail);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            btn_close.dispose();
            goods0.dispose();
            goods2.dispose();
            goods1.dispose();
            list_mail.dispose();
            super.dispose();
        
}
    }
}
