package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.dialog.Dialog;

    public class EquipDlgBase extends Dialog
    {
        public var ui_tipstanchukuangdi01_jiemian00:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian4173:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian41197:Scale9Image;
        public var bgImage3:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian41360:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian47105:Scale9Image;
        public var bgImage0:Scale9Image;
        public var bgImage1:Scale9Image;
        public var bgImage2:Scale9Image;
        public var embed_Scale9Button:Scale9Button;
        public var strengthen_Scale9Button:Scale9Button;
        public var fall_Scale9Button:Scale9Button;
        public var replace_Scale9Button:Scale9Button;
        public var icon:Image;
        public var quality:Image;
        public var nameTxt:TextField;
        public var attack:TextField;
        public var addattackValue:TextField;
        public var addattack:TextField;
        public var hp:TextField;
        public var addhpValue:TextField;
        public var addhp:TextField;
        public var defend:TextField;
        public var adddefendValue:TextField;
        public var adddefend:TextField;
        public var defendName:TextField;
        public var hit:TextField;
        public var addhitValue:TextField;
        public var addhit:TextField;
        public var hitName:TextField;
        public var crit:TextField;
        public var addcritValue:TextField;
        public var addcrit:TextField;
        public var critName:TextField;
        public var anitCrit:TextField;
        public var addanitCritValue:TextField;
        public var addanitCrit:TextField;
        public var anitCritName:TextField;
        public var puncture:TextField;
        public var addpunctureValue:TextField;
        public var addpuncture:TextField;
        public var punctureName:TextField;
        public var dodge:TextField;
        public var adddodgeValue:TextField;
        public var adddodge:TextField;
        public var dodgeName:TextField;
        public var critPercentage:TextField;
        public var addcritPercentageValue:TextField;
        public var addcritPercentage:TextField;
        public var critPercentageName:TextField;
        public var toughness:TextField;
        public var addtoughnessValue:TextField;
        public var addtoughness:TextField;
        public var toughnessName:TextField;

        public function EquipDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian00Rect:Rectangle = new Rectangle(68,64,6,6);
            var ui_tipstanchukuangdi01_jiemian009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian00Rect);
            ui_tipstanchukuangdi01_jiemian00 = new Scale9Image(ui_tipstanchukuangdi01_jiemian009ScaleTexture);
            ui_tipstanchukuangdi01_jiemian00.width = 620;
            ui_tipstanchukuangdi01_jiemian00.height = 600;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian00);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 47;
            image.y = 38;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 572;
            image.y = 38;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 47;
            image.y = 557;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 572;
            image.y = 557;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian4173Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian41739ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian4173Rect);
            ui_zhuangshixianquan02_jiemian4173 = new Scale9Image(ui_zhuangshixianquan02_jiemian41739ScaleTexture);
            ui_zhuangshixianquan02_jiemian4173.x = 41;
            ui_zhuangshixianquan02_jiemian4173.y = 73;
            ui_zhuangshixianquan02_jiemian4173.width = 534;
            ui_zhuangshixianquan02_jiemian4173.height = 2;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian4173);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian41197Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian411979ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian41197Rect);
            ui_zhuangshixianquan02_jiemian41197 = new Scale9Image(ui_zhuangshixianquan02_jiemian411979ScaleTexture);
            ui_zhuangshixianquan02_jiemian41197.x = 41;
            ui_zhuangshixianquan02_jiemian41197.y = 197;
            ui_zhuangshixianquan02_jiemian41197.width = 534;
            ui_zhuangshixianquan02_jiemian41197.height = 2;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian41197);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage3Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage39ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage3Rect);
            bgImage3 = new Scale9Image(bgImage39ScaleTexture);
            bgImage3.x = 70;
            bgImage3.y = 210;
            bgImage3.width = 480;
            bgImage3.height = 140;
            this.addQuiackChild(bgImage3);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian41360Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian413609ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian41360Rect);
            ui_zhuangshixianquan02_jiemian41360 = new Scale9Image(ui_zhuangshixianquan02_jiemian413609ScaleTexture);
            ui_zhuangshixianquan02_jiemian41360.x = 41;
            ui_zhuangshixianquan02_jiemian41360.y = 360;
            ui_zhuangshixianquan02_jiemian41360.width = 534;
            ui_zhuangshixianquan02_jiemian41360.height = 2;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian41360);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian47105Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian471059ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian47105Rect);
            ui_zhuangshixianquan01_jiemian47105 = new Scale9Image(ui_zhuangshixianquan01_jiemian471059ScaleTexture);
            ui_zhuangshixianquan01_jiemian47105.x = 47;
            ui_zhuangshixianquan01_jiemian47105.y = 105;
            ui_zhuangshixianquan01_jiemian47105.width = 174;
            ui_zhuangshixianquan01_jiemian47105.height = 50;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian47105);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage0Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage09ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage0Rect);
            bgImage0 = new Scale9Image(bgImage09ScaleTexture);
            bgImage0.x = 49;
            bgImage0.y = 111;
            bgImage0.width = 170;
            bgImage0.height = 39;
            this.addQuiackChild(bgImage0);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage1Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage19ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage1Rect);
            bgImage1 = new Scale9Image(bgImage19ScaleTexture);
            bgImage1.x = 357;
            bgImage1.y = 94;
            bgImage1.width = 220;
            bgImage1.height = 34;
            this.addQuiackChild(bgImage1);
            texture =assetMgr.getTexture('ui_gongji01_tubiao');
            image = new Image(texture);
            image.x = 341;
            image.y = 91;
            image.width = 38;
            image.height = 38;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage2Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage29ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage2Rect);
            bgImage2 = new Scale9Image(bgImage29ScaleTexture);
            bgImage2.x = 357;
            bgImage2.y = 140;
            bgImage2.width = 220;
            bgImage2.height = 34;
            this.addQuiackChild(bgImage2);
            texture =assetMgr.getTexture('ui_shengming01_tubiao');
            image = new Image(texture);
            image.x = 341;
            image.y = 139;
            image.width = 38;
            image.height = 38;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_hong03_01_anniu');
            var embed_Scale9ButtonRect:Rectangle = new Rectangle(29,16,58,31);
            embed_Scale9Button = new Scale9Button(texture,embed_Scale9ButtonRect);
            embed_Scale9Button.x = 95;
            embed_Scale9Button.y = 465;
            embed_Scale9Button.width = 186;
            embed_Scale9Button.height = 70;
            this.addQuiackChild(embed_Scale9Button);
            embed_Scale9Button.name = 'embed_Scale9Button';
            embed_Scale9Button.text= 'lable';
            embed_Scale9Button.fontColor= 0xFFFFFF;
            embed_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_hong03_01_anniu');
            var strengthen_Scale9ButtonRect:Rectangle = new Rectangle(29,16,58,31);
            strengthen_Scale9Button = new Scale9Button(texture,strengthen_Scale9ButtonRect);
            strengthen_Scale9Button.x = 340;
            strengthen_Scale9Button.y = 380;
            strengthen_Scale9Button.width = 186;
            strengthen_Scale9Button.height = 70;
            this.addQuiackChild(strengthen_Scale9Button);
            strengthen_Scale9Button.name = 'strengthen_Scale9Button';
            strengthen_Scale9Button.text= 'lable';
            strengthen_Scale9Button.fontColor= 0xFFFFFF;
            strengthen_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_hong03_01_anniu');
            var fall_Scale9ButtonRect:Rectangle = new Rectangle(29,16,58,31);
            fall_Scale9Button = new Scale9Button(texture,fall_Scale9ButtonRect);
            fall_Scale9Button.x = 340;
            fall_Scale9Button.y = 465;
            fall_Scale9Button.width = 186;
            fall_Scale9Button.height = 70;
            this.addQuiackChild(fall_Scale9Button);
            fall_Scale9Button.name = 'fall_Scale9Button';
            fall_Scale9Button.text= 'lable';
            fall_Scale9Button.fontColor= 0xFFFFFF;
            fall_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_hong03_01_anniu');
            var replace_Scale9ButtonRect:Rectangle = new Rectangle(29,16,58,31);
            replace_Scale9Button = new Scale9Button(texture,replace_Scale9ButtonRect);
            replace_Scale9Button.x = 95;
            replace_Scale9Button.y = 380;
            replace_Scale9Button.width = 186;
            replace_Scale9Button.height = 70;
            this.addQuiackChild(replace_Scale9Button);
            replace_Scale9Button.name = 'replace_Scale9Button';
            replace_Scale9Button.text= 'lable';
            replace_Scale9Button.fontColor= 0xFFFFFF;
            replace_Scale9Button.fontSize= 24;
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 570;
            image.y = 43;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 49;
            image.y = 43;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 570;
            image.y = 552;
            image.width = 8;
            image.height = 33;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 49;
            image.y = 552;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_daojukuangdi');
            image = new Image(texture);
            image.x = 234;
            image.y = 86;
            image.width = 98;
            image.height = 98;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('icon_101001')
            icon = new Image(texture);
            icon.x = 239;
            icon.y = 90;
            icon.width = 89;
            icon.height = 89;
            this.addQuiackChild(icon);
            icon.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            quality = new Image(texture);
            quality.x = 234;
            quality.y = 86;
            quality.width = 98;
            quality.height = 98;
            this.addQuiackChild(quality);
            quality.touchable = false;
            nameTxt = new TextField(198,32,'','',24,0xFF00FF,false);
            nameTxt.touchable = false;
            nameTxt.hAlign= 'center';
            nameTxt.text= '';
            nameTxt.x = 211;
            nameTxt.y = 38;
            this.addQuiackChild(nameTxt);
            attack = new TextField(90,32,'','',24,0xFFFFFF,false);
            attack.touchable = false;
            attack.hAlign= 'center';
            attack.text= '';
            attack.x = 375;
            attack.y = 95;
            this.addQuiackChild(attack);
            addattackValue = new TextField(90,32,'','',24,0x00FF00,false);
            addattackValue.touchable = false;
            addattackValue.hAlign= 'center';
            addattackValue.text= '';
            addattackValue.x = 483;
            addattackValue.y = 95;
            this.addQuiackChild(addattackValue);
            addattack = new TextField(20,32,'','',24,0x00FF00,false);
            addattack.touchable = false;
            addattack.hAlign= 'center';
            addattack.text= '+';
            addattack.x = 464;
            addattack.y = 95;
            this.addQuiackChild(addattack);
            hp = new TextField(90,32,'','',24,0xFFFFFF,false);
            hp.touchable = false;
            hp.hAlign= 'center';
            hp.text= '';
            hp.x = 375;
            hp.y = 141;
            this.addQuiackChild(hp);
            addhpValue = new TextField(90,32,'','',24,0x00FF00,false);
            addhpValue.touchable = false;
            addhpValue.hAlign= 'center';
            addhpValue.text= '';
            addhpValue.x = 483;
            addhpValue.y = 141;
            this.addQuiackChild(addhpValue);
            addhp = new TextField(20,32,'','',24,0x00FF00,false);
            addhp.touchable = false;
            addhp.hAlign= 'center';
            addhp.text= '+';
            addhp.x = 464;
            addhp.y = 141;
            this.addQuiackChild(addhp);
            defend = new TextField(60,31,'','',24,0xFFFFFF,false);
            defend.touchable = false;
            defend.hAlign= 'center';
            defend.text= '';
            defend.x = 155;
            defend.y = 215;
            this.addQuiackChild(defend);
            adddefendValue = new TextField(60,31,'','',24,0x00FF00,false);
            adddefendValue.touchable = false;
            adddefendValue.hAlign= 'center';
            adddefendValue.text= '';
            adddefendValue.x = 247;
            adddefendValue.y = 215;
            this.addQuiackChild(adddefendValue);
            adddefend = new TextField(20,31,'','',24,0x00FF00,false);
            adddefend.touchable = false;
            adddefend.hAlign= 'center';
            adddefend.text= '';
            adddefend.x = 220;
            adddefend.y = 215;
            this.addQuiackChild(adddefend);
            defendName = new TextField(80,31,'','',24,0xFFCC99,false);
            defendName.touchable = false;
            defendName.hAlign= 'center';
            defendName.text= '';
            defendName.x = 84;
            defendName.y = 215;
            this.addQuiackChild(defendName);
            hit = new TextField(60,31,'','',24,0xFFFFFF,false);
            hit.touchable = false;
            hit.hAlign= 'center';
            hit.text= '';
            hit.x = 155;
            hit.y = 247;
            this.addQuiackChild(hit);
            addhitValue = new TextField(60,31,'','',24,0x00FF00,false);
            addhitValue.touchable = false;
            addhitValue.hAlign= 'center';
            addhitValue.text= '';
            addhitValue.x = 247;
            addhitValue.y = 247;
            this.addQuiackChild(addhitValue);
            addhit = new TextField(20,31,'','',24,0x00FF00,false);
            addhit.touchable = false;
            addhit.hAlign= 'center';
            addhit.text= '';
            addhit.x = 220;
            addhit.y = 247;
            this.addQuiackChild(addhit);
            hitName = new TextField(80,31,'','',24,0xFFCC99,false);
            hitName.touchable = false;
            hitName.hAlign= 'center';
            hitName.text= '';
            hitName.x = 84;
            hitName.y = 247;
            this.addQuiackChild(hitName);
            crit = new TextField(60,31,'','',24,0xFFFFFF,false);
            crit.touchable = false;
            crit.hAlign= 'center';
            crit.text= '';
            crit.x = 155;
            crit.y = 279;
            this.addQuiackChild(crit);
            addcritValue = new TextField(60,31,'','',24,0x00FF00,false);
            addcritValue.touchable = false;
            addcritValue.hAlign= 'center';
            addcritValue.text= '';
            addcritValue.x = 247;
            addcritValue.y = 279;
            this.addQuiackChild(addcritValue);
            addcrit = new TextField(20,31,'','',24,0x00FF00,false);
            addcrit.touchable = false;
            addcrit.hAlign= 'center';
            addcrit.text= '';
            addcrit.x = 220;
            addcrit.y = 279;
            this.addQuiackChild(addcrit);
            critName = new TextField(80,31,'','',24,0xFFCC99,false);
            critName.touchable = false;
            critName.hAlign= 'center';
            critName.text= '';
            critName.x = 84;
            critName.y = 279;
            this.addQuiackChild(critName);
            anitCrit = new TextField(60,31,'','',24,0xFFFFFF,false);
            anitCrit.touchable = false;
            anitCrit.hAlign= 'center';
            anitCrit.text= '';
            anitCrit.x = 155;
            anitCrit.y = 312;
            this.addQuiackChild(anitCrit);
            addanitCritValue = new TextField(60,31,'','',24,0x00FF00,false);
            addanitCritValue.touchable = false;
            addanitCritValue.hAlign= 'center';
            addanitCritValue.text= '';
            addanitCritValue.x = 247;
            addanitCritValue.y = 312;
            this.addQuiackChild(addanitCritValue);
            addanitCrit = new TextField(20,31,'','',24,0x00FF00,false);
            addanitCrit.touchable = false;
            addanitCrit.hAlign= 'center';
            addanitCrit.text= '';
            addanitCrit.x = 220;
            addanitCrit.y = 312;
            this.addQuiackChild(addanitCrit);
            anitCritName = new TextField(80,31,'','',24,0xFFCC99,false);
            anitCritName.touchable = false;
            anitCritName.hAlign= 'center';
            anitCritName.text= '';
            anitCritName.x = 84;
            anitCritName.y = 312;
            this.addQuiackChild(anitCritName);
            puncture = new TextField(60,31,'','',24,0xFFFFFF,false);
            puncture.touchable = false;
            puncture.hAlign= 'center';
            puncture.text= '';
            puncture.x = 384;
            puncture.y = 215;
            this.addQuiackChild(puncture);
            addpunctureValue = new TextField(60,31,'','',24,0x00FF00,false);
            addpunctureValue.touchable = false;
            addpunctureValue.hAlign= 'center';
            addpunctureValue.text= '';
            addpunctureValue.x = 476;
            addpunctureValue.y = 215;
            this.addQuiackChild(addpunctureValue);
            addpuncture = new TextField(20,31,'','',24,0x00FF00,false);
            addpuncture.touchable = false;
            addpuncture.hAlign= 'center';
            addpuncture.text= '';
            addpuncture.x = 449;
            addpuncture.y = 215;
            this.addQuiackChild(addpuncture);
            punctureName = new TextField(80,31,'','',24,0xFFCC99,false);
            punctureName.touchable = false;
            punctureName.hAlign= 'center';
            punctureName.text= '';
            punctureName.x = 313;
            punctureName.y = 215;
            this.addQuiackChild(punctureName);
            dodge = new TextField(60,31,'','',24,0xFFFFFF,false);
            dodge.touchable = false;
            dodge.hAlign= 'center';
            dodge.text= '';
            dodge.x = 384;
            dodge.y = 247;
            this.addQuiackChild(dodge);
            adddodgeValue = new TextField(60,31,'','',24,0x00FF00,false);
            adddodgeValue.touchable = false;
            adddodgeValue.hAlign= 'center';
            adddodgeValue.text= '';
            adddodgeValue.x = 476;
            adddodgeValue.y = 247;
            this.addQuiackChild(adddodgeValue);
            adddodge = new TextField(20,31,'','',24,0x00FF00,false);
            adddodge.touchable = false;
            adddodge.hAlign= 'center';
            adddodge.text= '';
            adddodge.x = 449;
            adddodge.y = 247;
            this.addQuiackChild(adddodge);
            dodgeName = new TextField(80,31,'','',24,0xFFCC99,false);
            dodgeName.touchable = false;
            dodgeName.hAlign= 'center';
            dodgeName.text= '';
            dodgeName.x = 313;
            dodgeName.y = 247;
            this.addQuiackChild(dodgeName);
            critPercentage = new TextField(60,31,'','',24,0xFFFFFF,false);
            critPercentage.touchable = false;
            critPercentage.hAlign= 'center';
            critPercentage.text= '';
            critPercentage.x = 384;
            critPercentage.y = 279;
            this.addQuiackChild(critPercentage);
            addcritPercentageValue = new TextField(60,31,'','',24,0x00FF00,false);
            addcritPercentageValue.touchable = false;
            addcritPercentageValue.hAlign= 'center';
            addcritPercentageValue.text= '';
            addcritPercentageValue.x = 476;
            addcritPercentageValue.y = 279;
            this.addQuiackChild(addcritPercentageValue);
            addcritPercentage = new TextField(20,31,'','',24,0x00FF00,false);
            addcritPercentage.touchable = false;
            addcritPercentage.hAlign= 'center';
            addcritPercentage.text= '';
            addcritPercentage.x = 449;
            addcritPercentage.y = 279;
            this.addQuiackChild(addcritPercentage);
            critPercentageName = new TextField(80,31,'','',24,0xFFCC99,false);
            critPercentageName.touchable = false;
            critPercentageName.hAlign= 'center';
            critPercentageName.text= '';
            critPercentageName.x = 313;
            critPercentageName.y = 279;
            this.addQuiackChild(critPercentageName);
            toughness = new TextField(60,31,'','',24,0xFFFFFF,false);
            toughness.touchable = false;
            toughness.hAlign= 'center';
            toughness.text= '';
            toughness.x = 384;
            toughness.y = 312;
            this.addQuiackChild(toughness);
            addtoughnessValue = new TextField(60,31,'','',24,0x00FF00,false);
            addtoughnessValue.touchable = false;
            addtoughnessValue.hAlign= 'center';
            addtoughnessValue.text= '';
            addtoughnessValue.x = 476;
            addtoughnessValue.y = 312;
            this.addQuiackChild(addtoughnessValue);
            addtoughness = new TextField(20,31,'','',24,0x00FF00,false);
            addtoughness.touchable = false;
            addtoughness.hAlign= 'center';
            addtoughness.text= '';
            addtoughness.x = 449;
            addtoughness.y = 312;
            this.addQuiackChild(addtoughness);
            toughnessName = new TextField(80,31,'','',24,0xFFCC99,false);
            toughnessName.touchable = false;
            toughnessName.hAlign= 'center';
            toughnessName.text= '';
            toughnessName.x = 313;
            toughnessName.y = 312;
            this.addQuiackChild(toughnessName);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
    }
}
