package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.controls.List;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.view.View;

    public class EquimentViewBase extends View
    {
        public var ui_zhuangshixianquan01_jiemian500160:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian504193:Scale9Image;
        public var textSkill_1:TextField;
        public var ui_zhuangshixianquan01_jiemian160358:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian701137:Scale9Image;
        public var list_equip:List;
        public var list_exp:List;
        public var btn_equip:Button;
        public var cion_equip:Image;
        public var tag_add:Image;
        public var ui_zhuangshixianquan01_jiemian507105:Scale9Image;
        public var figthNum:TextField;
        public var skill_1:Button;
        public var expTxt:TextField;
        public var expBar:Sprite;
        public var zbBtn_Scale9Button:Scale9Button;
        public var ziliao_Scale9Button:Scale9Button;
        public var textSkill_0:TextField;
        public var skill_0:Button;
        public var textSkill_2:TextField;
        public var skill_2:Button;

        public function EquimentViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture =assetMgr.getTexture('ui_yingxiongzhijia_taitou_wenzi');
            image = new Image(texture);
            image.x = 483;
            image.y = 20;
            image.width = 115;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian500160Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian5001609ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian500160Rect);
            ui_zhuangshixianquan01_jiemian500160 = new Scale9Image(ui_zhuangshixianquan01_jiemian5001609ScaleTexture);
            ui_zhuangshixianquan01_jiemian500160.x = 500;
            ui_zhuangshixianquan01_jiemian500160.y = 160;
            ui_zhuangshixianquan01_jiemian500160.width = 168;
            ui_zhuangshixianquan01_jiemian500160.height = 188;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian500160);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian504193Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian5041939ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian504193Rect);
            ui_zhuangshixianquan02_jiemian504193 = new Scale9Image(ui_zhuangshixianquan02_jiemian5041939ScaleTexture);
            ui_zhuangshixianquan02_jiemian504193.x = 504;
            ui_zhuangshixianquan02_jiemian504193.y = 193;
            ui_zhuangshixianquan02_jiemian504193.width = 160;
            ui_zhuangshixianquan02_jiemian504193.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian504193);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 509;
            image.y = 163;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 659;
            image.y = 163;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_jineng_xiaotaitou_wenzi');
            image = new Image(texture);
            image.x = 559;
            image.y = 163;
            image.width = 53;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 548;
            image.y = 192;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 620;
            image.y = 192;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            textSkill_1 = new TextField(112,31,'','',21,0xFFFFFF,false);
            textSkill_1.touchable = false;
            textSkill_1.hAlign= 'center';
            textSkill_1.text= '';
            textSkill_1.x = 552;
            textSkill_1.y = 254;
            this.addQuiackChild(textSkill_1);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian160358Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian1603589ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian160358Rect);
            ui_zhuangshixianquan01_jiemian160358 = new Scale9Image(ui_zhuangshixianquan01_jiemian1603589ScaleTexture);
            ui_zhuangshixianquan01_jiemian160358.x = 160;
            ui_zhuangshixianquan01_jiemian160358.y = 358;
            ui_zhuangshixianquan01_jiemian160358.width = 300;
            ui_zhuangshixianquan01_jiemian160358.height = 60;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian160358);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian701137Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian7011379ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian701137Rect);
            ui_zhuangshixianquan01_jiemian701137 = new Scale9Image(ui_zhuangshixianquan01_jiemian7011379ScaleTexture);
            ui_zhuangshixianquan01_jiemian701137.x = 701;
            ui_zhuangshixianquan01_jiemian701137.y = 137;
            ui_zhuangshixianquan01_jiemian701137.width = 220;
            ui_zhuangshixianquan01_jiemian701137.height = 215;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian701137);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 705;
            image.y = 135;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 916;
            image.y = 135;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 782;
            image.y = 135;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 840;
            image.y = 135;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 691;
            image.y = 138;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 931;
            image.y = 140;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            list_equip = new List();
            list_equip.x = 706;
            list_equip.y = 142;
            list_equip.width = 210;
            list_equip.height = 205;
            this.addQuiackChild(list_equip);
            list_exp = new List();
            list_exp.x = 706;
            list_exp.y = 142;
            list_exp.width = 210;
            list_exp.height = 205;
            this.addQuiackChild(list_exp);
            texture = assetMgr.getTexture('ui_chenghaodi01');
            btn_equip = new Button(texture);
            btn_equip.name= 'btn_equip';
            btn_equip.x = 785;
            btn_equip.y = 82;
            btn_equip.width = 52;
            btn_equip.height = 52;
            this.addQuiackChild(btn_equip);
            texture = assetMgr.getTexture('icon_300000')
            cion_equip = new Image(texture);
            cion_equip.x = 787;
            cion_equip.y = 84;
            cion_equip.width = 48;
            cion_equip.height = 48;
            this.addQuiackChild(cion_equip);
            cion_equip.touchable = false;
            texture = assetMgr.getTexture('ui_xiaojiahao_anniu')
            tag_add = new Image(texture);
            tag_add.x = 820;
            tag_add.y = 117;
            tag_add.width = 12;
            tag_add.height = 12;
            this.addQuiackChild(tag_add);
            tag_add.touchable = false;
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian507105Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian5071059ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian507105Rect);
            ui_zhuangshixianquan01_jiemian507105 = new Scale9Image(ui_zhuangshixianquan01_jiemian5071059ScaleTexture);
            ui_zhuangshixianquan01_jiemian507105.x = 507;
            ui_zhuangshixianquan01_jiemian507105.y = 105;
            ui_zhuangshixianquan01_jiemian507105.width = 156;
            ui_zhuangshixianquan01_jiemian507105.height = 50;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian507105);
            texture =assetMgr.getTexture('ui_zhandouli01_tubiao');
            image = new Image(texture);
            image.x = 486;
            image.y = 82;
            image.width = 195;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            figthNum = new TextField(149,38,'','',30,0xFFFFFF,false);
            figthNum.touchable = false;
            figthNum.hAlign= 'center';
            figthNum.text= '';
            figthNum.x = 510;
            figthNum.y = 114;
            this.addQuiackChild(figthNum);
            texture = assetMgr.getTexture('ui_jinengkuangdi01');
            skill_1 = new Button(texture);
            skill_1.name= 'skill_1';
            skill_1.x = 506;
            skill_1.y = 247;
            skill_1.width = 46;
            skill_1.height = 46;
            this.addQuiackChild(skill_1);
            expTxt = new TextField(160,31,'','',24,0xFFFFFF,false);
            expTxt.touchable = false;
            expTxt.hAlign= 'center';
            expTxt.text= '';
            expTxt.x = 276;
            expTxt.y = 384;
            this.addQuiackChild(expTxt);
            texture =assetMgr.getTexture('ui_jingyan_01_jindutiao');
            image = new Image(texture);
            image.x = 276;
            image.y = 364;
            image.width = 160;
            image.height = 21;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            expBar = new Sprite();
            expBar.x = 276;
            expBar.y = 364;
            expBar.width = 160;
            expBar.height = 21;
            this.addQuiackChild(expBar);
            expBar.name= 'expBar';
            texture =assetMgr.getTexture('ui_jingyan_02_jindutiao');
            image = new Image(texture);
            image.width = 160;
            image.height = 21;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            expBar.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var zbBtn_Scale9ButtonRect:Rectangle = new Rectangle(29,16,58,31);
            zbBtn_Scale9Button = new Scale9Button(texture,zbBtn_Scale9ButtonRect);
            zbBtn_Scale9Button.x = 711;
            zbBtn_Scale9Button.y = 355;
            zbBtn_Scale9Button.width = 200;
            zbBtn_Scale9Button.height = 70;
            this.addQuiackChild(zbBtn_Scale9Button);
            zbBtn_Scale9Button.name = 'zbBtn_Scale9Button';
            zbBtn_Scale9Button.text= 'lable';
            zbBtn_Scale9Button.fontColor= 0xFFFFFF;
            zbBtn_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var ziliao_Scale9ButtonRect:Rectangle = new Rectangle(29,16,58,31);
            ziliao_Scale9Button = new Scale9Button(texture,ziliao_Scale9ButtonRect);
            ziliao_Scale9Button.x = 484;
            ziliao_Scale9Button.y = 355;
            ziliao_Scale9Button.width = 200;
            ziliao_Scale9Button.height = 70;
            this.addQuiackChild(ziliao_Scale9Button);
            ziliao_Scale9Button.name = 'ziliao_Scale9Button';
            ziliao_Scale9Button.text= 'lable';
            ziliao_Scale9Button.fontColor= 0xFFFFFF;
            ziliao_Scale9Button.fontSize= 24;
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 657;
            image.y = 168;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 511;
            image.y = 168;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            textSkill_0 = new TextField(112,31,'','',21,0xFFFFFF,false);
            textSkill_0.touchable = false;
            textSkill_0.hAlign= 'center';
            textSkill_0.text= '';
            textSkill_0.x = 552;
            textSkill_0.y = 205;
            this.addQuiackChild(textSkill_0);
            texture = assetMgr.getTexture('ui_jinengkuangdi01');
            skill_0 = new Button(texture);
            skill_0.name= 'skill_0';
            skill_0.x = 506;
            skill_0.y = 198;
            skill_0.width = 46;
            skill_0.height = 46;
            this.addQuiackChild(skill_0);
            textSkill_2 = new TextField(112,31,'','',21,0xFFFFFF,false);
            textSkill_2.touchable = false;
            textSkill_2.hAlign= 'center';
            textSkill_2.text= '';
            textSkill_2.x = 552;
            textSkill_2.y = 303;
            this.addQuiackChild(textSkill_2);
            texture = assetMgr.getTexture('ui_jinengkuangdi01');
            skill_2 = new Button(texture);
            skill_2.name= 'skill_2';
            skill_2.x = 506;
            skill_2.y = 296;
            skill_2.width = 46;
            skill_2.height = 46;
            this.addQuiackChild(skill_2);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            list_equip.dispose();
            list_exp.dispose();
            btn_equip.dispose();
            skill_1.dispose();
            expBar.dispose();
            skill_0.dispose();
            skill_2.dispose();
            super.dispose();
        
}
    }
}
