package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import game.view.goodsGuide.render.GoodsGuideListRender;
    import com.view.View;

    public class GoodsGuideInfoViewBase extends View
    {
        public var ui_tipstanchukuangdi01_jiemian00:Scale9Image;
        public var bgImage:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian54160:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian54210:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian54450:Scale9Image;
        public var btnok_Scale9Button:Scale9Button;
        public var btnSwallow_Scale9Button:Scale9Button;
        public var grid:GoodsGuideListRender;
        public var view_equip:Sprite;
        public var txt_get:TextField;
        public var txt_des:TextField;

        public function GoodsGuideInfoViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian00Rect:Rectangle = new Rectangle(48,46,44,43);
            var ui_tipstanchukuangdi01_jiemian009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian00Rect);
            ui_tipstanchukuangdi01_jiemian00 = new Scale9Image(ui_tipstanchukuangdi01_jiemian009ScaleTexture);
            ui_tipstanchukuangdi01_jiemian00.width = 408;
            ui_tipstanchukuangdi01_jiemian00.height = 570;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian00);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImageRect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage9ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImageRect);
            bgImage = new Scale9Image(bgImage9ScaleTexture);
            bgImage.x = 32;
            bgImage.y = 215;
            bgImage.width = 344;
            bgImage.height = 232;
            this.addQuiackChild(bgImage);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian54160Rect:Rectangle = new Rectangle(3,0,3,2);
            var ui_zhuangshixianquan02_jiemian541609ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian54160Rect);
            ui_zhuangshixianquan02_jiemian54160 = new Scale9Image(ui_zhuangshixianquan02_jiemian541609ScaleTexture);
            ui_zhuangshixianquan02_jiemian54160.x = 54;
            ui_zhuangshixianquan02_jiemian54160.y = 160;
            ui_zhuangshixianquan02_jiemian54160.width = 300;
            ui_zhuangshixianquan02_jiemian54160.height = 3;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian54160);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian54210Rect:Rectangle = new Rectangle(3,0,3,2);
            var ui_zhuangshixianquan02_jiemian542109ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian54210Rect);
            ui_zhuangshixianquan02_jiemian54210 = new Scale9Image(ui_zhuangshixianquan02_jiemian542109ScaleTexture);
            ui_zhuangshixianquan02_jiemian54210.x = 54;
            ui_zhuangshixianquan02_jiemian54210.y = 210;
            ui_zhuangshixianquan02_jiemian54210.width = 300;
            ui_zhuangshixianquan02_jiemian54210.height = 3;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian54210);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian54450Rect:Rectangle = new Rectangle(3,0,3,2);
            var ui_zhuangshixianquan02_jiemian544509ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian54450Rect);
            ui_zhuangshixianquan02_jiemian54450 = new Scale9Image(ui_zhuangshixianquan02_jiemian544509ScaleTexture);
            ui_zhuangshixianquan02_jiemian54450.x = 54;
            ui_zhuangshixianquan02_jiemian54450.y = 450;
            ui_zhuangshixianquan02_jiemian54450.width = 300;
            ui_zhuangshixianquan02_jiemian54450.height = 3;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian54450);
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var btnok_Scale9ButtonRect:Rectangle = new Rectangle(37,18,45,22);
            btnok_Scale9Button = new Scale9Button(texture,btnok_Scale9ButtonRect);
            btnok_Scale9Button.x = 47;
            btnok_Scale9Button.y = 464;
            btnok_Scale9Button.width = 150;
            btnok_Scale9Button.height = 62;
            this.addQuiackChild(btnok_Scale9Button);
            btnok_Scale9Button.name = 'btnok_Scale9Button';
            btnok_Scale9Button.text= 'lable';
            btnok_Scale9Button.fontColor= 0xFFFFFF;
            btnok_Scale9Button.fontSize= 22;
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var btnSwallow_Scale9ButtonRect:Rectangle = new Rectangle(37,18,45,22);
            btnSwallow_Scale9Button = new Scale9Button(texture,btnSwallow_Scale9ButtonRect);
            btnSwallow_Scale9Button.x = 211;
            btnSwallow_Scale9Button.y = 464;
            btnSwallow_Scale9Button.width = 150;
            btnSwallow_Scale9Button.height = 62;
            this.addQuiackChild(btnSwallow_Scale9Button);
            btnSwallow_Scale9Button.name = 'btnSwallow_Scale9Button';
            btnSwallow_Scale9Button.text= 'lable';
            btnSwallow_Scale9Button.fontColor= 0xFFFFFF;
            btnSwallow_Scale9Button.fontSize= 22;
            grid = new GoodsGuideListRender();
            grid.x = 41;
            grid.y = 27;
            this.addQuiackChild(grid);
            view_equip = new Sprite();
            view_equip.x = 60;
            view_equip.y = 226;
            view_equip.width = 289;
            view_equip.height = 210;
            this.addQuiackChild(view_equip);
            view_equip.name= 'view_equip';
            textField = new TextField(100,32,'','',24,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 38;
            textField.y = 6;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'txt_attack';
            view_equip.addQuiackChild(textField);
            textField = new TextField(100,32,'','',24,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 189;
            textField.y = 6;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'txt_hp';
            view_equip.addQuiackChild(textField);
            textField = new TextField(80,32,'','',24,0xFFCC99,false);
            textField.touchable = false;
            textField.y = 48;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'defend';
            view_equip.addQuiackChild(textField);
            textField = new TextField(68,32,'','',24,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 70;
            textField.y = 48;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_defend';
            view_equip.addQuiackChild(textField);
            textField = new TextField(80,30,'','',24,0xFFCC99,false);
            textField.touchable = false;
            textField.x = 148;
            textField.y = 48;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'puncture';
            view_equip.addQuiackChild(textField);
            textField = new TextField(68,32,'','',24,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 221;
            textField.y = 48;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_puncture';
            view_equip.addQuiackChild(textField);
            textField = new TextField(80,32,'','',24,0xFFCC99,false);
            textField.touchable = false;
            textField.y = 90;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'hit';
            view_equip.addQuiackChild(textField);
            textField = new TextField(68,32,'','',24,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 70;
            textField.y = 90;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_hit';
            view_equip.addQuiackChild(textField);
            textField = new TextField(80,32,'','',24,0xFFCC99,false);
            textField.touchable = false;
            textField.x = 148;
            textField.y = 90;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'dodge';
            view_equip.addQuiackChild(textField);
            textField = new TextField(68,32,'','',24,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 221;
            textField.y = 90;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_dodge';
            view_equip.addQuiackChild(textField);
            textField = new TextField(80,32,'','',24,0xFFCC99,false);
            textField.touchable = false;
            textField.y = 134;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'crit';
            view_equip.addQuiackChild(textField);
            textField = new TextField(68,32,'','',24,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 70;
            textField.y = 134;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_crit';
            view_equip.addQuiackChild(textField);
            textField = new TextField(80,32,'','',24,0xFFCC99,false);
            textField.touchable = false;
            textField.x = 148;
            textField.y = 134;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'critPercentage';
            view_equip.addQuiackChild(textField);
            textField = new TextField(68,32,'','',24,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 221;
            textField.y = 134;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_critPercentage';
            view_equip.addQuiackChild(textField);
            textField = new TextField(80,32,'','',24,0xFFCC99,false);
            textField.touchable = false;
            textField.y = 178;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'anitCrit';
            view_equip.addQuiackChild(textField);
            textField = new TextField(80,32,'','',24,0xFFCC99,false);
            textField.touchable = false;
            textField.x = 148;
            textField.y = 178;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'toughness';
            view_equip.addQuiackChild(textField);
            textField = new TextField(68,32,'','',24,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 70;
            textField.y = 178;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_anitCrit';
            view_equip.addQuiackChild(textField);
            textField = new TextField(68,32,'','',24,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 221;
            textField.y = 178;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_toughness';
            view_equip.addQuiackChild(textField);
            texture =assetMgr.getTexture('ui_gongji01_tubiao');
            image = new Image(texture);
            image.x = 2;
            image.width = 38;
            image.height = 38;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_equip.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_shengming01_tubiao');
            image = new Image(texture);
            image.x = 150;
            image.width = 38;
            image.height = 38;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_equip.addQuiackChild(image);
            txt_get = new TextField(283,36,'','',24,0xFFFFFF,false);
            txt_get.touchable = false;
            txt_get.hAlign= 'center';
            txt_get.text= '';
            txt_get.x = 61;
            txt_get.y = 168;
            this.addQuiackChild(txt_get);
            txt_des = new TextField(306,180,'','',24,0xFFFFFF,false);
            txt_des.touchable = false;
            txt_des.hAlign= 'left';
            txt_des.text= '';
            txt_des.x = 51;
            txt_des.y = 241;
            this.addQuiackChild(txt_des);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            grid.dispose();
            view_equip.dispose();
            super.dispose();
        
}
    }
}
