package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.dialog.Dialog;

    public class HeroSkillsBase extends Dialog
    {
        public var ui_tipstanchukuangdi01_jiemian00:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian42331:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian42466:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian42289:Scale9Image;
        public var ui_zhuangshixianquan03_jiemian72205:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian42332:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian42467:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian42290:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian18291:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian186124:Scale9Image;
        public var textSkill_0:TextField;
        public var textSkill_1:TextField;
        public var textSkill_2:TextField;
        public var text_heroInfo:TextField;
        public var text_expert:TextField;
        public var text_HabitWeapon:TextField;
        public var text_HabitWeaponValue:TextField;
        public var text_expertValue:TextField;
        public var text_heroName:TextField;
        public var heroSkill_0:Button;
        public var heroSkill_2:Button;
        public var heroSkill_1:Button;
        public var heroIcon:Image;
        public var jobIcon:Image;
        public var quality:Image;

        public function HeroSkillsBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian00Rect:Rectangle = new Rectangle(68,64,6,6);
            var ui_tipstanchukuangdi01_jiemian009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian00Rect);
            ui_tipstanchukuangdi01_jiemian00 = new Scale9Image(ui_tipstanchukuangdi01_jiemian009ScaleTexture);
            ui_tipstanchukuangdi01_jiemian00.width = 400;
            ui_tipstanchukuangdi01_jiemian00.height = 600;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian00);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 47;
            image.y = 292;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 354;
            image.y = 292;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_mingzidi01');
            image = new Image(texture);
            image.x = 119;
            image.y = 42;
            image.width = 156;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yingxiongjianjie_xiaotaitou_wenzi');
            image = new Image(texture);
            image.x = 147;
            image.y = 302;
            image.width = 102;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian42331Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian423319ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian42331Rect);
            ui_zhuangshixianquan02_jiemian42331 = new Scale9Image(ui_zhuangshixianquan02_jiemian423319ScaleTexture);
            ui_zhuangshixianquan02_jiemian42331.x = 42;
            ui_zhuangshixianquan02_jiemian42331.y = 331;
            ui_zhuangshixianquan02_jiemian42331.width = 316;
            ui_zhuangshixianquan02_jiemian42331.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian42331);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 146;
            image.y = 330;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 246;
            image.y = 330;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian42466Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian424669ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian42466Rect);
            ui_zhuangshixianquan02_jiemian42466 = new Scale9Image(ui_zhuangshixianquan02_jiemian424669ScaleTexture);
            ui_zhuangshixianquan02_jiemian42466.x = 42;
            ui_zhuangshixianquan02_jiemian42466.y = 466;
            ui_zhuangshixianquan02_jiemian42466.width = 316;
            ui_zhuangshixianquan02_jiemian42466.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian42466);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian42289Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian422899ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian42289Rect);
            ui_zhuangshixianquan02_jiemian42289 = new Scale9Image(ui_zhuangshixianquan02_jiemian422899ScaleTexture);
            ui_zhuangshixianquan02_jiemian42289.x = 42;
            ui_zhuangshixianquan02_jiemian42289.y = 289;
            ui_zhuangshixianquan02_jiemian42289.width = 316;
            ui_zhuangshixianquan02_jiemian42289.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian42289);
            texture = assetMgr.getTexture('ui_zhuangshixianquan03_jiemian');
            var ui_zhuangshixianquan03_jiemian72205Rect:Rectangle = new Rectangle(30,30,10,10);
            var ui_zhuangshixianquan03_jiemian722059ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan03_jiemian72205Rect);
            ui_zhuangshixianquan03_jiemian72205 = new Scale9Image(ui_zhuangshixianquan03_jiemian722059ScaleTexture);
            ui_zhuangshixianquan03_jiemian72205.x = 72;
            ui_zhuangshixianquan03_jiemian72205.y = 205;
            ui_zhuangshixianquan03_jiemian72205.width = 68;
            ui_zhuangshixianquan03_jiemian72205.height = 68;
            this.addQuiackChild(ui_zhuangshixianquan03_jiemian72205);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian42332Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian423329ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian42332Rect);
            ui_zhuangshixianquan02_jiemian42332 = new Scale9Image(ui_zhuangshixianquan02_jiemian423329ScaleTexture);
            ui_zhuangshixianquan02_jiemian42332.x = 42;
            ui_zhuangshixianquan02_jiemian42332.y = 332;
            ui_zhuangshixianquan02_jiemian42332.width = 316;
            ui_zhuangshixianquan02_jiemian42332.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian42332);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian42467Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian424679ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian42467Rect);
            ui_zhuangshixianquan02_jiemian42467 = new Scale9Image(ui_zhuangshixianquan02_jiemian424679ScaleTexture);
            ui_zhuangshixianquan02_jiemian42467.x = 42;
            ui_zhuangshixianquan02_jiemian42467.y = 467;
            ui_zhuangshixianquan02_jiemian42467.width = 316;
            ui_zhuangshixianquan02_jiemian42467.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian42467);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian42290Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian422909ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian42290Rect);
            ui_zhuangshixianquan02_jiemian42290 = new Scale9Image(ui_zhuangshixianquan02_jiemian422909ScaleTexture);
            ui_zhuangshixianquan02_jiemian42290.x = 42;
            ui_zhuangshixianquan02_jiemian42290.y = 290;
            ui_zhuangshixianquan02_jiemian42290.width = 316;
            ui_zhuangshixianquan02_jiemian42290.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian42290);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian18291Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian182919ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian18291Rect);
            ui_zhuangshixianquan01_jiemian18291 = new Scale9Image(ui_zhuangshixianquan01_jiemian182919ScaleTexture);
            ui_zhuangshixianquan01_jiemian18291.x = 182;
            ui_zhuangshixianquan01_jiemian18291.y = 91;
            ui_zhuangshixianquan01_jiemian18291.width = 168;
            ui_zhuangshixianquan01_jiemian18291.height = 188;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian18291);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian186124Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian1861249ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian186124Rect);
            ui_zhuangshixianquan02_jiemian186124 = new Scale9Image(ui_zhuangshixianquan02_jiemian1861249ScaleTexture);
            ui_zhuangshixianquan02_jiemian186124.x = 186;
            ui_zhuangshixianquan02_jiemian186124.y = 124;
            ui_zhuangshixianquan02_jiemian186124.width = 160;
            ui_zhuangshixianquan02_jiemian186124.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian186124);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 191;
            image.y = 94;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 341;
            image.y = 94;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_jineng_xiaotaitou_wenzi');
            image = new Image(texture);
            image.x = 241;
            image.y = 94;
            image.width = 53;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 230;
            image.y = 123;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 302;
            image.y = 123;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            textSkill_0 = new TextField(109,31,'','',21,0xFFFFFF,false);
            textSkill_0.touchable = false;
            textSkill_0.hAlign= 'center';
            textSkill_0.text= '';
            textSkill_0.x = 234;
            textSkill_0.y = 136;
            this.addQuiackChild(textSkill_0);
            textSkill_1 = new TextField(109,31,'','',21,0xFFFFFF,false);
            textSkill_1.touchable = false;
            textSkill_1.hAlign= 'center';
            textSkill_1.text= '';
            textSkill_1.x = 234;
            textSkill_1.y = 185;
            this.addQuiackChild(textSkill_1);
            textSkill_2 = new TextField(109,31,'','',21,0xFFFFFF,false);
            textSkill_2.touchable = false;
            textSkill_2.hAlign= 'center';
            textSkill_2.text= '';
            textSkill_2.x = 234;
            textSkill_2.y = 234;
            this.addQuiackChild(textSkill_2);
            text_heroInfo = new TextField(320,118,'','',24,0xFFFFFF,false);
            text_heroInfo.touchable = false;
            text_heroInfo.hAlign= 'center';
            text_heroInfo.text= '';
            text_heroInfo.x = 40;
            text_heroInfo.y = 341;
            this.addQuiackChild(text_heroInfo);
            text_expert = new TextField(132,31,'','',24,0xFFFFFF,false);
            text_expert.touchable = false;
            text_expert.hAlign= 'center';
            text_expert.text= '';
            text_expert.x = 65;
            text_expert.y = 481;
            this.addQuiackChild(text_expert);
            text_HabitWeapon = new TextField(132,31,'','',24,0xFFFFFF,false);
            text_HabitWeapon.touchable = false;
            text_HabitWeapon.hAlign= 'center';
            text_HabitWeapon.text= '';
            text_HabitWeapon.x = 65;
            text_HabitWeapon.y = 516;
            this.addQuiackChild(text_HabitWeapon);
            text_HabitWeaponValue = new TextField(158,31,'','',24,0xFF33FF,false);
            text_HabitWeaponValue.touchable = false;
            text_HabitWeaponValue.hAlign= 'center';
            text_HabitWeaponValue.text= '';
            text_HabitWeaponValue.x = 180;
            text_HabitWeaponValue.y = 516;
            this.addQuiackChild(text_HabitWeaponValue);
            text_expertValue = new TextField(158,31,'','',24,0xFF6600,false);
            text_expertValue.touchable = false;
            text_expertValue.hAlign= 'center';
            text_expertValue.text= '';
            text_expertValue.x = 180;
            text_expertValue.y = 481;
            this.addQuiackChild(text_expertValue);
            text_heroName = new TextField(200,32,'','',24,0xFFFFFF,false);
            text_heroName.touchable = false;
            text_heroName.hAlign= 'center';
            text_heroName.text= '';
            text_heroName.x = 100;
            text_heroName.y = 44;
            this.addQuiackChild(text_heroName);
            texture = assetMgr.getTexture('ui_jinengkuangdi01');
            heroSkill_0 = new Button(texture);
            heroSkill_0.name= 'heroSkill_0';
            heroSkill_0.x = 188;
            heroSkill_0.y = 129;
            heroSkill_0.width = 46;
            heroSkill_0.height = 46;
            this.addQuiackChild(heroSkill_0);
            texture = assetMgr.getTexture('ui_jinengkuangdi01');
            heroSkill_2 = new Button(texture);
            heroSkill_2.name= 'heroSkill_2';
            heroSkill_2.x = 188;
            heroSkill_2.y = 227;
            heroSkill_2.width = 46;
            heroSkill_2.height = 46;
            this.addQuiackChild(heroSkill_2);
            texture = assetMgr.getTexture('ui_jinengkuangdi01');
            heroSkill_1 = new Button(texture);
            heroSkill_1.name= 'heroSkill_1';
            heroSkill_1.x = 188;
            heroSkill_1.y = 178;
            heroSkill_1.width = 46;
            heroSkill_1.height = 46;
            this.addQuiackChild(heroSkill_1);
            texture =assetMgr.getTexture('ui_daojukuangdi');
            image = new Image(texture);
            image.x = 58;
            image.y = 91;
            image.width = 98;
            image.height = 98;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_504')
            heroIcon = new Image(texture);
            heroIcon.x = 57;
            heroIcon.y = 90;
            heroIcon.width = 100;
            heroIcon.height = 100;
            this.addQuiackChild(heroIcon);
            heroIcon.touchable = false;
            texture = assetMgr.getTexture('ui_texingtubiao_01')
            jobIcon = new Image(texture);
            jobIcon.x = 92;
            jobIcon.y = 225;
            jobIcon.width = 28;
            jobIcon.height = 28;
            this.addQuiackChild(jobIcon);
            jobIcon.touchable = false;
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 339;
            image.y = 99;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 352;
            image.y = 297;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 193;
            image.y = 99;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 49;
            image.y = 297;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_touxiangkuang_13')
            quality = new Image(texture);
            quality.x = 57;
            quality.y = 90;
            quality.width = 100;
            quality.height = 100;
            this.addQuiackChild(quality);
            quality.touchable = false;
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            heroSkill_0.dispose();
            heroSkill_2.dispose();
            heroSkill_1.dispose();
            super.dispose();
        
}
    }
}
