package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.dialog.Dialog;

    public class HeroPriceDialogBase extends Dialog
    {
        public var ui_tipstanchukuangdi01_jiemian00:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian41204:Scale9Image;
        public var bgImage0:Scale9Image;
        public var bgImage1:Scale9Image;
        public var bgImage2:Scale9Image;
        public var attackValue:TextField;
        public var attackAddValue:TextField;
        public var add_1:TextField;
        public var hpValue:TextField;
        public var hpAddValue:TextField;
        public var add_2:TextField;
        public var defendValue:TextField;
        public var defendAddValue:TextField;
        public var add_3:TextField;
        public var defend:TextField;
        public var hitValue:TextField;
        public var hitAddValue:TextField;
        public var add_4:TextField;
        public var hit:TextField;
        public var critValue:TextField;
        public var critAddValue:TextField;
        public var add_5:TextField;
        public var crit:TextField;
        public var anitCritValue:TextField;
        public var anitCritAddValue:TextField;
        public var add_6:TextField;
        public var anitCrit:TextField;
        public var punctureValue:TextField;
        public var punctureAddValue:TextField;
        public var add_7:TextField;
        public var puncture:TextField;
        public var dodgeValue:TextField;
        public var dodgeAddValue:TextField;
        public var add_8:TextField;
        public var dodge:TextField;
        public var critPercentageValue:TextField;
        public var critPercentageAddValue:TextField;
        public var add_9:TextField;
        public var critPercentage:TextField;
        public var toughnessValue:TextField;
        public var toughnessAddValue:TextField;
        public var add_10:TextField;
        public var toughness:TextField;
        public var view_evo:Sprite;

        public function HeroPriceDialogBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian00Rect:Rectangle = new Rectangle(68,64,6,6);
            var ui_tipstanchukuangdi01_jiemian009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian00Rect);
            ui_tipstanchukuangdi01_jiemian00 = new Scale9Image(ui_tipstanchukuangdi01_jiemian009ScaleTexture);
            ui_tipstanchukuangdi01_jiemian00.width = 400;
            ui_tipstanchukuangdi01_jiemian00.height = 600;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian00);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian41204Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian412049ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian41204Rect);
            ui_zhuangshixianquan02_jiemian41204 = new Scale9Image(ui_zhuangshixianquan02_jiemian412049ScaleTexture);
            ui_zhuangshixianquan02_jiemian41204.x = 41;
            ui_zhuangshixianquan02_jiemian41204.y = 204;
            ui_zhuangshixianquan02_jiemian41204.width = 322;
            ui_zhuangshixianquan02_jiemian41204.height = 2;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian41204);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage0Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage09ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage0Rect);
            bgImage0 = new Scale9Image(bgImage09ScaleTexture);
            bgImage0.x = 70;
            bgImage0.y = 215;
            bgImage0.width = 265;
            bgImage0.height = 34;
            this.addQuiackChild(bgImage0);
            texture =assetMgr.getTexture('ui_gongji01_tubiao');
            image = new Image(texture);
            image.x = 52;
            image.y = 212;
            image.width = 38;
            image.height = 38;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage1Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage19ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage1Rect);
            bgImage1 = new Scale9Image(bgImage19ScaleTexture);
            bgImage1.x = 70;
            bgImage1.y = 252;
            bgImage1.width = 265;
            bgImage1.height = 34;
            this.addQuiackChild(bgImage1);
            texture =assetMgr.getTexture('ui_shengming01_tubiao');
            image = new Image(texture);
            image.x = 52;
            image.y = 250;
            image.width = 38;
            image.height = 38;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage2Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage29ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage2Rect);
            bgImage2 = new Scale9Image(bgImage29ScaleTexture);
            bgImage2.x = 33;
            bgImage2.y = 297;
            bgImage2.width = 334;
            bgImage2.height = 250;
            this.addQuiackChild(bgImage2);
            attackValue = new TextField(100,32,'','',24,0xFFFFFF,false);
            attackValue.touchable = false;
            attackValue.hAlign= 'center';
            attackValue.text= '';
            attackValue.x = 100;
            attackValue.y = 216;
            this.addQuiackChild(attackValue);
            attackAddValue = new TextField(100,32,'','',24,0x00FF00,false);
            attackAddValue.touchable = false;
            attackAddValue.hAlign= 'center';
            attackAddValue.text= '';
            attackAddValue.x = 231;
            attackAddValue.y = 217;
            this.addQuiackChild(attackAddValue);
            add_1 = new TextField(20,32,'','',24,0x00FF00,false);
            add_1.touchable = false;
            add_1.hAlign= 'center';
            add_1.text= '+';
            add_1.x = 206;
            add_1.y = 217;
            this.addQuiackChild(add_1);
            hpValue = new TextField(100,32,'','',24,0xFFFFFF,false);
            hpValue.touchable = false;
            hpValue.hAlign= 'center';
            hpValue.text= '';
            hpValue.x = 100;
            hpValue.y = 252;
            this.addQuiackChild(hpValue);
            hpAddValue = new TextField(100,32,'','',24,0x00FF00,false);
            hpAddValue.touchable = false;
            hpAddValue.hAlign= 'center';
            hpAddValue.text= '';
            hpAddValue.x = 231;
            hpAddValue.y = 252;
            this.addQuiackChild(hpAddValue);
            add_2 = new TextField(20,32,'','',24,0x00FF00,false);
            add_2.touchable = false;
            add_2.hAlign= 'center';
            add_2.text= '+';
            add_2.x = 206;
            add_2.y = 252;
            this.addQuiackChild(add_2);
            defendValue = new TextField(80,32,'','',24,0xFFFFFF,false);
            defendValue.touchable = false;
            defendValue.hAlign= 'center';
            defendValue.text= '';
            defendValue.x = 142;
            defendValue.y = 300;
            this.addQuiackChild(defendValue);
            defendAddValue = new TextField(80,32,'','',24,0x00FF00,false);
            defendAddValue.touchable = false;
            defendAddValue.hAlign= 'center';
            defendAddValue.text= '';
            defendAddValue.x = 266;
            defendAddValue.y = 300;
            this.addQuiackChild(defendAddValue);
            add_3 = new TextField(20,31,'','',24,0x00FF00,false);
            add_3.touchable = false;
            add_3.hAlign= 'center';
            add_3.text= '+';
            add_3.x = 235;
            add_3.y = 298;
            this.addQuiackChild(add_3);
            defend = new TextField(80,32,'','',24,0xFFCC99,false);
            defend.touchable = false;
            defend.hAlign= 'center';
            defend.text= '';
            defend.x = 64;
            defend.y = 300;
            this.addQuiackChild(defend);
            hitValue = new TextField(80,32,'','',24,0xFFFFFF,false);
            hitValue.touchable = false;
            hitValue.hAlign= 'center';
            hitValue.text= '';
            hitValue.x = 142;
            hitValue.y = 330;
            this.addQuiackChild(hitValue);
            hitAddValue = new TextField(80,32,'','',24,0x00FF00,false);
            hitAddValue.touchable = false;
            hitAddValue.hAlign= 'center';
            hitAddValue.text= '';
            hitAddValue.x = 266;
            hitAddValue.y = 330;
            this.addQuiackChild(hitAddValue);
            add_4 = new TextField(20,31,'','',24,0x00FF00,false);
            add_4.touchable = false;
            add_4.hAlign= 'center';
            add_4.text= '+';
            add_4.x = 235;
            add_4.y = 328;
            this.addQuiackChild(add_4);
            hit = new TextField(80,32,'','',24,0xFFCC99,false);
            hit.touchable = false;
            hit.hAlign= 'center';
            hit.text= '';
            hit.x = 64;
            hit.y = 330;
            this.addQuiackChild(hit);
            critValue = new TextField(80,32,'','',24,0xFFFFFF,false);
            critValue.touchable = false;
            critValue.hAlign= 'center';
            critValue.text= '';
            critValue.x = 142;
            critValue.y = 360;
            this.addQuiackChild(critValue);
            critAddValue = new TextField(80,32,'','',24,0x00FF00,false);
            critAddValue.touchable = false;
            critAddValue.hAlign= 'center';
            critAddValue.text= '';
            critAddValue.x = 266;
            critAddValue.y = 360;
            this.addQuiackChild(critAddValue);
            add_5 = new TextField(20,31,'','',24,0x00FF00,false);
            add_5.touchable = false;
            add_5.hAlign= 'center';
            add_5.text= '+';
            add_5.x = 235;
            add_5.y = 358;
            this.addQuiackChild(add_5);
            crit = new TextField(80,32,'','',24,0xFFCC99,false);
            crit.touchable = false;
            crit.hAlign= 'center';
            crit.text= '';
            crit.x = 64;
            crit.y = 360;
            this.addQuiackChild(crit);
            anitCritValue = new TextField(80,32,'','',24,0xFFFFFF,false);
            anitCritValue.touchable = false;
            anitCritValue.hAlign= 'center';
            anitCritValue.text= '';
            anitCritValue.x = 142;
            anitCritValue.y = 390;
            this.addQuiackChild(anitCritValue);
            anitCritAddValue = new TextField(80,32,'','',24,0x00FF00,false);
            anitCritAddValue.touchable = false;
            anitCritAddValue.hAlign= 'center';
            anitCritAddValue.text= '';
            anitCritAddValue.x = 266;
            anitCritAddValue.y = 390;
            this.addQuiackChild(anitCritAddValue);
            add_6 = new TextField(20,31,'','',24,0x00FF00,false);
            add_6.touchable = false;
            add_6.hAlign= 'center';
            add_6.text= '+';
            add_6.x = 235;
            add_6.y = 388;
            this.addQuiackChild(add_6);
            anitCrit = new TextField(80,32,'','',24,0xFFCC99,false);
            anitCrit.touchable = false;
            anitCrit.hAlign= 'center';
            anitCrit.text= '';
            anitCrit.x = 64;
            anitCrit.y = 390;
            this.addQuiackChild(anitCrit);
            punctureValue = new TextField(80,32,'','',24,0xFFFFFF,false);
            punctureValue.touchable = false;
            punctureValue.hAlign= 'center';
            punctureValue.text= '';
            punctureValue.x = 142;
            punctureValue.y = 420;
            this.addQuiackChild(punctureValue);
            punctureAddValue = new TextField(80,32,'','',24,0x00FF00,false);
            punctureAddValue.touchable = false;
            punctureAddValue.hAlign= 'center';
            punctureAddValue.text= '';
            punctureAddValue.x = 266;
            punctureAddValue.y = 420;
            this.addQuiackChild(punctureAddValue);
            add_7 = new TextField(20,31,'','',24,0x00FF00,false);
            add_7.touchable = false;
            add_7.hAlign= 'center';
            add_7.text= '+';
            add_7.x = 235;
            add_7.y = 418;
            this.addQuiackChild(add_7);
            puncture = new TextField(80,32,'','',24,0xFFCC99,false);
            puncture.touchable = false;
            puncture.hAlign= 'center';
            puncture.text= '';
            puncture.x = 64;
            puncture.y = 420;
            this.addQuiackChild(puncture);
            dodgeValue = new TextField(80,32,'','',24,0xFFFFFF,false);
            dodgeValue.touchable = false;
            dodgeValue.hAlign= 'center';
            dodgeValue.text= '';
            dodgeValue.x = 142;
            dodgeValue.y = 450;
            this.addQuiackChild(dodgeValue);
            dodgeAddValue = new TextField(80,32,'','',24,0x00FF00,false);
            dodgeAddValue.touchable = false;
            dodgeAddValue.hAlign= 'center';
            dodgeAddValue.text= '';
            dodgeAddValue.x = 266;
            dodgeAddValue.y = 450;
            this.addQuiackChild(dodgeAddValue);
            add_8 = new TextField(20,31,'','',24,0x00FF00,false);
            add_8.touchable = false;
            add_8.hAlign= 'center';
            add_8.text= '+';
            add_8.x = 235;
            add_8.y = 448;
            this.addQuiackChild(add_8);
            dodge = new TextField(80,32,'','',24,0xFFCC99,false);
            dodge.touchable = false;
            dodge.hAlign= 'center';
            dodge.text= '';
            dodge.x = 64;
            dodge.y = 450;
            this.addQuiackChild(dodge);
            critPercentageValue = new TextField(80,32,'','',24,0xFFFFFF,false);
            critPercentageValue.touchable = false;
            critPercentageValue.hAlign= 'center';
            critPercentageValue.text= '';
            critPercentageValue.x = 142;
            critPercentageValue.y = 480;
            this.addQuiackChild(critPercentageValue);
            critPercentageAddValue = new TextField(80,32,'','',24,0x00FF00,false);
            critPercentageAddValue.touchable = false;
            critPercentageAddValue.hAlign= 'center';
            critPercentageAddValue.text= '';
            critPercentageAddValue.x = 266;
            critPercentageAddValue.y = 480;
            this.addQuiackChild(critPercentageAddValue);
            add_9 = new TextField(20,31,'','',24,0x00FF00,false);
            add_9.touchable = false;
            add_9.hAlign= 'center';
            add_9.text= '+';
            add_9.x = 235;
            add_9.y = 478;
            this.addQuiackChild(add_9);
            critPercentage = new TextField(80,32,'','',24,0xFFCC99,false);
            critPercentage.touchable = false;
            critPercentage.hAlign= 'center';
            critPercentage.text= '';
            critPercentage.x = 64;
            critPercentage.y = 480;
            this.addQuiackChild(critPercentage);
            toughnessValue = new TextField(80,32,'','',24,0xFFFFFF,false);
            toughnessValue.touchable = false;
            toughnessValue.hAlign= 'center';
            toughnessValue.text= '';
            toughnessValue.x = 142;
            toughnessValue.y = 510;
            this.addQuiackChild(toughnessValue);
            toughnessAddValue = new TextField(80,32,'','',24,0x00FF00,false);
            toughnessAddValue.touchable = false;
            toughnessAddValue.hAlign= 'center';
            toughnessAddValue.text= '';
            toughnessAddValue.x = 266;
            toughnessAddValue.y = 510;
            this.addQuiackChild(toughnessAddValue);
            add_10 = new TextField(20,31,'','',24,0x00FF00,false);
            add_10.touchable = false;
            add_10.hAlign= 'center';
            add_10.text= '+';
            add_10.x = 235;
            add_10.y = 508;
            this.addQuiackChild(add_10);
            toughness = new TextField(80,32,'','',24,0xFFCC99,false);
            toughness.touchable = false;
            toughness.hAlign= 'center';
            toughness.text= '';
            toughness.x = 64;
            toughness.y = 510;
            this.addQuiackChild(toughness);
            view_evo = new Sprite();
            view_evo.x = 41;
            view_evo.y = 38;
            view_evo.width = 318;
            view_evo.height = 157;
            this.addQuiackChild(view_evo);
            view_evo.name= 'view_evo';
            texture =assetMgr.getTexture('ui_zhishijiantou01_tubiao');
            image = new Image(texture);
            image.x = 131;
            image.y = 80;
            image.width = 61;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_evo.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_mingzidi01');
            image = new Image(texture);
            image.x = 81;
            image.y = 9;
            image.width = 156;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_evo.addQuiackChild(image);
            textField = new TextField(114,31,'','',24,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 102;
            textField.y = 12;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'text_Title';
            view_evo.addQuiackChild(textField);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 6;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_evo.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 312;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_evo.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_daojukuangdi');
            image = new Image(texture);
            image.x = 212;
            image.y = 58;
            image.width = 98;
            image.height = 98;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_evo.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_daojukuangdi');
            image = new Image(texture);
            image.x = 11;
            image.y = 58;
            image.width = 98;
            image.height = 98;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_evo.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 310;
            image.y = 5;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_evo.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 8;
            image.y = 5;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_evo.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_525')
            image = new Image(texture);
            image.name= 'icon';
            image.x = 12;
            image.y = 59;
            image.width = 96;
            image.height = 96;
            view_evo.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('photo_525')
            image = new Image(texture);
            image.name= 'icon1';
            image.x = 213;
            image.y = 59;
            image.width = 96;
            image.height = 96;
            view_evo.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_07')
            image = new Image(texture);
            image.name= 'quality';
            image.x = 10;
            image.y = 57;
            image.width = 100;
            image.height = 100;
            view_evo.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangkuang_07')
            image = new Image(texture);
            image.name= 'quality1';
            image.x = 211;
            image.y = 57;
            image.width = 100;
            image.height = 100;
            view_evo.addQuiackChild(image);
            image.touchable = false;
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            view_evo.dispose();
            super.dispose();
        
}
    }
}
