package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.controls.List;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import game.view.blacksmith.render.BallPane;
    import game.view.blacksmith.render.EmbedBallItem;
    import game.view.blacksmith.render.EquipContainer;
    import com.view.View;

    public class InsetViewBase extends View
    {
        public var list_equip:List;
        public var ui_zhuangshixianquan03_jiemian51486:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian528100:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian543148:Scale9Image;
        public var bgImage:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian532410:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian532136:Scale9Image;
        public var strenthenScale9Button:Scale9Button;
        public var ballPane:BallPane;
        public var item0:EmbedBallItem;
        public var item1:EmbedBallItem;
        public var item2:EmbedBallItem;
        public var item3:EmbedBallItem;
        public var item4:EmbedBallItem;
        public var equip:EquipContainer;
        public var equipName:TextField;
        public var spend:TextField;
        public var text_useup:TextField;
        public var hero:TextField;
        public var heroName:TextField;

        public function InsetViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            list_equip = new List();
            list_equip.x = 171;
            list_equip.y = 90;
            list_equip.width = 340;
            list_equip.height = 437;
            this.addQuiackChild(list_equip);
            texture = assetMgr.getTexture('ui_zhuangshixianquan03_jiemian');
            var ui_zhuangshixianquan03_jiemian51486Rect:Rectangle = new Rectangle(30,30,10,10);
            var ui_zhuangshixianquan03_jiemian514869ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan03_jiemian51486Rect);
            ui_zhuangshixianquan03_jiemian51486 = new Scale9Image(ui_zhuangshixianquan03_jiemian514869ScaleTexture);
            ui_zhuangshixianquan03_jiemian51486.x = 514;
            ui_zhuangshixianquan03_jiemian51486.y = 86;
            ui_zhuangshixianquan03_jiemian51486.width = 422;
            ui_zhuangshixianquan03_jiemian51486.height = 384;
            this.addQuiackChild(ui_zhuangshixianquan03_jiemian51486);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian528100Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian5281009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian528100Rect);
            ui_zhuangshixianquan01_jiemian528100 = new Scale9Image(ui_zhuangshixianquan01_jiemian5281009ScaleTexture);
            ui_zhuangshixianquan01_jiemian528100.x = 528;
            ui_zhuangshixianquan01_jiemian528100.y = 100;
            ui_zhuangshixianquan01_jiemian528100.width = 394;
            ui_zhuangshixianquan01_jiemian528100.height = 356;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian528100);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian543148Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian5431489ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian543148Rect);
            ui_zhuangshixianquan01_jiemian543148 = new Scale9Image(ui_zhuangshixianquan01_jiemian5431489ScaleTexture);
            ui_zhuangshixianquan01_jiemian543148.x = 543;
            ui_zhuangshixianquan01_jiemian543148.y = 148;
            ui_zhuangshixianquan01_jiemian543148.width = 174;
            ui_zhuangshixianquan01_jiemian543148.height = 250;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian543148);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImageRect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage9ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImageRect);
            bgImage = new Scale9Image(bgImage9ScaleTexture);
            bgImage.x = 545;
            bgImage.y = 160;
            bgImage.width = 170;
            bgImage.height = 39;
            this.addQuiackChild(bgImage);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian532410Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian5324109ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian532410Rect);
            ui_zhuangshixianquan02_jiemian532410 = new Scale9Image(ui_zhuangshixianquan02_jiemian5324109ScaleTexture);
            ui_zhuangshixianquan02_jiemian532410.x = 532;
            ui_zhuangshixianquan02_jiemian532410.y = 410;
            ui_zhuangshixianquan02_jiemian532410.width = 386;
            ui_zhuangshixianquan02_jiemian532410.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian532410);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian532136Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian5321369ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian532136Rect);
            ui_zhuangshixianquan02_jiemian532136 = new Scale9Image(ui_zhuangshixianquan02_jiemian5321369ScaleTexture);
            ui_zhuangshixianquan02_jiemian532136.x = 532;
            ui_zhuangshixianquan02_jiemian532136.y = 136;
            ui_zhuangshixianquan02_jiemian532136.width = 386;
            ui_zhuangshixianquan02_jiemian532136.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian532136);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 630;
            image.y = 159;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 630;
            image.y = 159;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_xiangqian_xiaotaitou_wenzi');
            image = new Image(texture);
            image.x = 698;
            image.y = 105;
            image.width = 54;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var strenthenScale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            strenthenScale9Button = new Scale9Button(texture,strenthenScale9ButtonRect);
            strenthenScale9Button.x = 730;
            strenthenScale9Button.y = 472;
            strenthenScale9Button.width = 186;
            strenthenScale9Button.height = 62;
            this.addQuiackChild(strenthenScale9Button);
            strenthenScale9Button.name = 'strenthenScale9Button';
            strenthenScale9Button.text= 'lable';
            strenthenScale9Button.fontColor= 0xffffff;
            strenthenScale9Button.fontSize= 24;
            ballPane = new BallPane();
            ballPane.x = 173;
            ballPane.y = 99;
            this.addQuiackChild(ballPane);
            item0 = new EmbedBallItem();
            item0.x = 735;
            item0.y = 142;
            this.addQuiackChild(item0);
            item1 = new EmbedBallItem();
            item1.x = 735;
            item1.y = 195;
            this.addQuiackChild(item1);
            item2 = new EmbedBallItem();
            item2.x = 735;
            item2.y = 248;
            this.addQuiackChild(item2);
            item3 = new EmbedBallItem();
            item3.x = 735;
            item3.y = 301;
            this.addQuiackChild(item3);
            item4 = new EmbedBallItem();
            item4.x = 735;
            item4.y = 354;
            this.addQuiackChild(item4);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 551;
            image.y = 200;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 707;
            image.y = 200;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 552;
            image.y = 395;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 708;
            image.y = 395;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            equip = new EquipContainer();
            equip.x = 584;
            equip.y = 236;
            this.addQuiackChild(equip);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 537;
            image.y = 103;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 913;
            image.y = 103;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 911;
            image.y = 108;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 539;
            image.y = 108;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 553;
            image.y = 205;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 705;
            image.y = 205;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 553;
            image.y = 386;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 705;
            image.y = 386;
            image.width = 8;
            image.height = 33;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_jinbi01_tubiao');
            image = new Image(texture);
            image.x = 588;
            image.y = 490;
            image.width = 25;
            image.height = 26;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            equipName = new TextField(162,32,'','',21,0xffffff,false);
            equipName.touchable = false;
            equipName.hAlign= 'center';
            equipName.text= '';
            equipName.x = 549;
            equipName.y = 163;
            this.addQuiackChild(equipName);
            spend = new TextField(112,36,'','',24,0xffffff,false);
            spend.touchable = false;
            spend.hAlign= 'center';
            spend.text= '';
            spend.x = 615;
            spend.y = 485;
            this.addQuiackChild(spend);
            text_useup = new TextField(60,36,'','',24,0xff0000,false);
            text_useup.touchable = false;
            text_useup.hAlign= 'center';
            text_useup.text= '';
            text_useup.x = 526;
            text_useup.y = 485;
            this.addQuiackChild(text_useup);
            hero = new TextField(116,28,'','',21,0xffffff,false);
            hero.touchable = false;
            hero.hAlign= 'center';
            hero.text= '';
            hero.x = 586;
            hero.y = 418;
            this.addQuiackChild(hero);
            heroName = new TextField(159,29,'','',21,0xff00ff,false);
            heroName.touchable = false;
            heroName.hAlign= 'left';
            heroName.text= '';
            heroName.x = 706;
            heroName.y = 418;
            this.addQuiackChild(heroName);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            list_equip.dispose();
            ballPane.dispose();
            item0.dispose();
            item1.dispose();
            item2.dispose();
            item3.dispose();
            item4.dispose();
            equip.dispose();
            super.dispose();
        
}
    }
}
