package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.dialog.TabDialog;

    public class JTUIFastBuyBase extends TabDialog
    {
        public var ui_tipstanchukuangdi01_jiemian00:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian43257:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian5371:Scale9Image;
        public var price_1:TextField;
        public var caption_1:TextField;
        public var ui_zhuangshixianquan01_jiemian20471:Scale9Image;
        public var price_2:TextField;
        public var caption_2:TextField;
        public var ui_zhuangshixianquan01_jiemian35571:Scale9Image;
        public var price_3:TextField;
        public var caption_3:TextField;
        public var title:TextField;
        public var back_Scale9Button:Scale9Button;

        public function JTUIFastBuyBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian00Rect:Rectangle = new Rectangle(68,64,6,6);
            var ui_tipstanchukuangdi01_jiemian009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian00Rect);
            ui_tipstanchukuangdi01_jiemian00 = new Scale9Image(ui_tipstanchukuangdi01_jiemian009ScaleTexture);
            ui_tipstanchukuangdi01_jiemian00.width = 542;
            ui_tipstanchukuangdi01_jiemian00.height = 376;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian00);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian43257Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian432579ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian43257Rect);
            ui_zhuangshixianquan02_jiemian43257 = new Scale9Image(ui_zhuangshixianquan02_jiemian432579ScaleTexture);
            ui_zhuangshixianquan02_jiemian43257.x = 43;
            ui_zhuangshixianquan02_jiemian43257.y = 257;
            ui_zhuangshixianquan02_jiemian43257.width = 456;
            ui_zhuangshixianquan02_jiemian43257.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian43257);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 49;
            image.y = 40;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 495;
            image.y = 40;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian5371Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian53719ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian5371Rect);
            ui_zhuangshixianquan01_jiemian5371 = new Scale9Image(ui_zhuangshixianquan01_jiemian53719ScaleTexture);
            ui_zhuangshixianquan01_jiemian5371.x = 53;
            ui_zhuangshixianquan01_jiemian5371.y = 71;
            ui_zhuangshixianquan01_jiemian5371.width = 136;
            ui_zhuangshixianquan01_jiemian5371.height = 139;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian5371);
            price_1 = new TextField(120,31,'','',24,0xFFFFFF,false);
            price_1.touchable = false;
            price_1.hAlign= 'center';
            price_1.text= '';
            price_1.x = 76;
            price_1.y = 217;
            this.addQuiackChild(price_1);
            texture =assetMgr.getTexture('ui_zuanshi01_tubiao');
            image = new Image(texture);
            image.x = 52;
            image.y = 219;
            image.width = 25;
            image.height = 26;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            caption_1 = new TextField(150,32,'','',24,0xFFFFFF,false);
            caption_1.touchable = false;
            caption_1.hAlign= 'center';
            caption_1.text= '';
            caption_1.x = 45;
            caption_1.y = 175;
            this.addQuiackChild(caption_1);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian20471Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian204719ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian20471Rect);
            ui_zhuangshixianquan01_jiemian20471 = new Scale9Image(ui_zhuangshixianquan01_jiemian204719ScaleTexture);
            ui_zhuangshixianquan01_jiemian20471.x = 204;
            ui_zhuangshixianquan01_jiemian20471.y = 71;
            ui_zhuangshixianquan01_jiemian20471.width = 136;
            ui_zhuangshixianquan01_jiemian20471.height = 139;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian20471);
            price_2 = new TextField(120,31,'','',24,0xFFFFFF,false);
            price_2.touchable = false;
            price_2.hAlign= 'center';
            price_2.text= '';
            price_2.x = 227;
            price_2.y = 217;
            this.addQuiackChild(price_2);
            texture =assetMgr.getTexture('ui_zuanshi01_tubiao');
            image = new Image(texture);
            image.x = 203;
            image.y = 219;
            image.width = 25;
            image.height = 26;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            caption_2 = new TextField(150,32,'','',24,0xFFFFFF,false);
            caption_2.touchable = false;
            caption_2.hAlign= 'center';
            caption_2.text= '';
            caption_2.x = 196;
            caption_2.y = 175;
            this.addQuiackChild(caption_2);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian35571Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian355719ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian35571Rect);
            ui_zhuangshixianquan01_jiemian35571 = new Scale9Image(ui_zhuangshixianquan01_jiemian355719ScaleTexture);
            ui_zhuangshixianquan01_jiemian35571.x = 355;
            ui_zhuangshixianquan01_jiemian35571.y = 71;
            ui_zhuangshixianquan01_jiemian35571.width = 136;
            ui_zhuangshixianquan01_jiemian35571.height = 139;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian35571);
            price_3 = new TextField(120,31,'','',24,0xFFFFFF,false);
            price_3.touchable = false;
            price_3.hAlign= 'center';
            price_3.text= '';
            price_3.x = 379;
            price_3.y = 217;
            this.addQuiackChild(price_3);
            texture =assetMgr.getTexture('ui_zuanshi01_tubiao');
            image = new Image(texture);
            image.x = 355;
            image.y = 219;
            image.width = 25;
            image.height = 26;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            caption_3 = new TextField(150,32,'','',24,0xFFFFFF,false);
            caption_3.touchable = false;
            caption_3.hAlign= 'center';
            caption_3.text= '';
            caption_3.x = 348;
            caption_3.y = 175;
            this.addQuiackChild(caption_3);
            title = new TextField(360,38,'','',30,0xFFFF00,false);
            title.touchable = false;
            title.hAlign= 'center';
            title.text= '';
            title.x = 91;
            title.y = 31;
            this.addQuiackChild(title);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 51;
            image.y = 45;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 493;
            image.y = 45;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_lan03_01_anniu');
            var back_Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            back_Scale9Button = new Scale9Button(texture,back_Scale9ButtonRect);
            back_Scale9Button.x = 178;
            back_Scale9Button.y = 270;
            back_Scale9Button.width = 186;
            back_Scale9Button.height = 70;
            this.addQuiackChild(back_Scale9Button);
            back_Scale9Button.name = 'back_Scale9Button';
            back_Scale9Button.text= 'lable';
            back_Scale9Button.fontColor= 0xFFFFC9;
            back_Scale9Button.fontSize= 28;
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
    }
}
