package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.dialog.Dialog;

    public class LuckyDlgBase extends Dialog
    {
        public var ui_zhuangshixianquan02_jiemian6184:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian6183:Scale9Image;
        public var ui_zhuangshixianquan03_jiemian43442:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian297457:Scale9Image;
        public var run:Button;
        public var bgImage:Scale9Image;
        public var but_lucky:Button;
        public var closeBtn:Button;
        public var star_Icon:Image;
        public var bg_0:Button;
        public var bg_16:Button;
        public var bg_19:Button;
        public var bg_18:Button;
        public var bg_17:Button;
        public var bg_15:Button;
        public var bg_14:Button;
        public var bg_13:Button;
        public var bg_12:Button;
        public var bg_11:Button;
        public var bg_10:Button;
        public var bg_9:Button;
        public var bg_8:Button;
        public var bg_7:Button;
        public var bg_6:Button;
        public var bg_5:Button;
        public var bg_4:Button;
        public var bg_3:Button;
        public var bg_2:Button;
        public var bg_1:Button;
        public var rankScale9Button:Scale9Button;
        public var icon_0:Image;
        public var icon_10:Image;
        public var icon_9:Image;
        public var icon_8:Image;
        public var icon_7:Image;
        public var icon_6:Image;
        public var icon_5:Image;
        public var icon_4:Image;
        public var icon_3:Image;
        public var icon_2:Image;
        public var icon_1:Image;
        public var icon_19:Image;
        public var icon_18:Image;
        public var icon_17:Image;
        public var icon_16:Image;
        public var icon_15:Image;
        public var icon_14:Image;
        public var icon_13:Image;
        public var icon_12:Image;
        public var icon_11:Image;
        public var item1:Image;
        public var item0:Image;
        public var item2:Image;
        public var item3:Image;
        public var item4:Image;
        public var item5:Image;
        public var item6:Image;
        public var item8:Image;
        public var item7:Image;
        public var item9:Image;
        public var item10:Image;
        public var item11:Image;
        public var item12:Image;
        public var item14:Image;
        public var item13:Image;
        public var item15:Image;
        public var item16:Image;
        public var item17:Image;
        public var item18:Image;
        public var item19:Image;
        public var turnMC:Scale9Image;
        public var text_0:TextField;
        public var text_6:TextField;
        public var text_18:TextField;
        public var text_17:TextField;
        public var text_16:TextField;
        public var text_15:TextField;
        public var text_14:TextField;
        public var text_13:TextField;
        public var text_12:TextField;
        public var text_11:TextField;
        public var text_10:TextField;
        public var text_9:TextField;
        public var text_8:TextField;
        public var text_7:TextField;
        public var text_19:TextField;
        public var text_5:TextField;
        public var text_4:TextField;
        public var text_3:TextField;
        public var text_2:TextField;
        public var text_1:TextField;
        public var text_rebateDes:TextField;
        public var text_diamand:TextField;
        public var diamond:TextField;
        public var star:TextField;

        public function LuckyDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture =assetMgr.getTexture('ui_tanchukuangdi02_jiemian');
            image = new Image(texture);
            image.y = 10;
            image.width = 972;
            image.height = 652;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian6184Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian61849ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian6184Rect);
            ui_zhuangshixianquan02_jiemian6184 = new Scale9Image(ui_zhuangshixianquan02_jiemian61849ScaleTexture);
            ui_zhuangshixianquan02_jiemian6184.x = 61;
            ui_zhuangshixianquan02_jiemian6184.y = 84;
            ui_zhuangshixianquan02_jiemian6184.width = 850;
            ui_zhuangshixianquan02_jiemian6184.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian6184);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian6183Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian61839ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian6183Rect);
            ui_zhuangshixianquan02_jiemian6183 = new Scale9Image(ui_zhuangshixianquan02_jiemian61839ScaleTexture);
            ui_zhuangshixianquan02_jiemian6183.x = 61;
            ui_zhuangshixianquan02_jiemian6183.y = 83;
            ui_zhuangshixianquan02_jiemian6183.width = 850;
            ui_zhuangshixianquan02_jiemian6183.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian6183);
            texture = assetMgr.getTexture('ui_zhuangshixianquan03_jiemian');
            var ui_zhuangshixianquan03_jiemian43442Rect:Rectangle = new Rectangle(30,30,10,10);
            var ui_zhuangshixianquan03_jiemian434429ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan03_jiemian43442Rect);
            ui_zhuangshixianquan03_jiemian43442 = new Scale9Image(ui_zhuangshixianquan03_jiemian434429ScaleTexture);
            ui_zhuangshixianquan03_jiemian43442.x = 43;
            ui_zhuangshixianquan03_jiemian43442.y = 442;
            ui_zhuangshixianquan03_jiemian43442.width = 884;
            ui_zhuangshixianquan03_jiemian43442.height = 170;
            this.addQuiackChild(ui_zhuangshixianquan03_jiemian43442);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian297457Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian2974579ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian297457Rect);
            ui_zhuangshixianquan01_jiemian297457 = new Scale9Image(ui_zhuangshixianquan01_jiemian2974579ScaleTexture);
            ui_zhuangshixianquan01_jiemian297457.x = 297;
            ui_zhuangshixianquan01_jiemian297457.y = 457;
            ui_zhuangshixianquan01_jiemian297457.width = 414;
            ui_zhuangshixianquan01_jiemian297457.height = 140;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian297457);
            texture = assetMgr.getTexture('ui_yuanhonganniu01_anniu');
            run = new Button(texture);
            run.name= 'run';
            run.x = 429;
            run.y = 211;
            run.width = 113;
            run.height = 113;
            this.addQuiackChild(run);
            run.text= 'lable';
            run.fontColor= 0xFFFFFF;
            run.fontSize= 24;
            texture =assetMgr.getTexture('ui_xingyunxing_beijingtu');
            image = new Image(texture);
            image.x = 64;
            image.y = 463;
            image.width = 222;
            image.height = 128;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 61;
            image.y = 454;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 289;
            image.y = 454;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 62;
            image.y = 599;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1.015869140625;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 285;
            image.y = 599;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1.015869140625;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImageRect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage9ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImageRect);
            bgImage = new Scale9Image(bgImage9ScaleTexture);
            bgImage.x = 63;
            bgImage.y = 499;
            bgImage.width = 224;
            bgImage.height = 56;
            this.addQuiackChild(bgImage);
            texture =assetMgr.getTexture('ui_xingyunxingtaitou_01');
            image = new Image(texture);
            image.x = 272;
            image.width = 429;
            image.height = 101;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_dingbuxinxi_01_anniu');
            but_lucky = new Button(texture);
            but_lucky.name= 'but_lucky';
            but_lucky.x = 721;
            but_lucky.y = 466;
            but_lucky.width = 184;
            but_lucky.height = 56;
            this.addQuiackChild(but_lucky);
            texture = assetMgr.getTexture('ui_guanbi01_anniu');
            closeBtn = new Button(texture);
            closeBtn.name= 'closeBtn';
            closeBtn.x = 885;
            closeBtn.y = 11;
            closeBtn.width = 72;
            closeBtn.height = 76;
            this.addQuiackChild(closeBtn);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 287;
            image.y = 459;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 63;
            image.y = 594;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 63;
            image.y = 459;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 287;
            image.y = 594;
            image.width = 8;
            image.height = 33;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            star_Icon = new Image(texture);
            star_Icon.x = 750;
            star_Icon.y = 481;
            star_Icon.width = 25;
            star_Icon.height = 26;
            this.addQuiackChild(star_Icon);
            star_Icon.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_0 = new Button(texture);
            bg_0.name= 'bg_0';
            bg_0.x = 73;
            bg_0.y = 99;
            bg_0.width = 98;
            bg_0.height = 98;
            this.addQuiackChild(bg_0);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_16 = new Button(texture);
            bg_16.name= 'bg_16';
            bg_16.x = 436;
            bg_16.y = 334;
            bg_16.width = 98;
            bg_16.height = 98;
            this.addQuiackChild(bg_16);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_19 = new Button(texture);
            bg_19.name= 'bg_19';
            bg_19.x = 799;
            bg_19.y = 334;
            bg_19.width = 98;
            bg_19.height = 98;
            this.addQuiackChild(bg_19);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_18 = new Button(texture);
            bg_18.name= 'bg_18';
            bg_18.x = 678;
            bg_18.y = 334;
            bg_18.width = 98;
            bg_18.height = 98;
            this.addQuiackChild(bg_18);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_17 = new Button(texture);
            bg_17.name= 'bg_17';
            bg_17.x = 557;
            bg_17.y = 334;
            bg_17.width = 98;
            bg_17.height = 98;
            this.addQuiackChild(bg_17);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_15 = new Button(texture);
            bg_15.name= 'bg_15';
            bg_15.x = 315;
            bg_15.y = 334;
            bg_15.width = 98;
            bg_15.height = 98;
            this.addQuiackChild(bg_15);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_14 = new Button(texture);
            bg_14.name= 'bg_14';
            bg_14.x = 194;
            bg_14.y = 334;
            bg_14.width = 98;
            bg_14.height = 98;
            this.addQuiackChild(bg_14);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_13 = new Button(texture);
            bg_13.name= 'bg_13';
            bg_13.x = 73;
            bg_13.y = 334;
            bg_13.width = 98;
            bg_13.height = 98;
            this.addQuiackChild(bg_13);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_12 = new Button(texture);
            bg_12.name= 'bg_12';
            bg_12.x = 799;
            bg_12.y = 218;
            bg_12.width = 98;
            bg_12.height = 98;
            this.addQuiackChild(bg_12);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_11 = new Button(texture);
            bg_11.name= 'bg_11';
            bg_11.x = 678;
            bg_11.y = 218;
            bg_11.width = 98;
            bg_11.height = 98;
            this.addQuiackChild(bg_11);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_10 = new Button(texture);
            bg_10.name= 'bg_10';
            bg_10.x = 557;
            bg_10.y = 218;
            bg_10.width = 98;
            bg_10.height = 98;
            this.addQuiackChild(bg_10);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_9 = new Button(texture);
            bg_9.name= 'bg_9';
            bg_9.x = 315;
            bg_9.y = 218;
            bg_9.width = 98;
            bg_9.height = 98;
            this.addQuiackChild(bg_9);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_8 = new Button(texture);
            bg_8.name= 'bg_8';
            bg_8.x = 194;
            bg_8.y = 218;
            bg_8.width = 98;
            bg_8.height = 98;
            this.addQuiackChild(bg_8);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_7 = new Button(texture);
            bg_7.name= 'bg_7';
            bg_7.x = 73;
            bg_7.y = 218;
            bg_7.width = 98;
            bg_7.height = 98;
            this.addQuiackChild(bg_7);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_6 = new Button(texture);
            bg_6.name= 'bg_6';
            bg_6.x = 799;
            bg_6.y = 99;
            bg_6.width = 98;
            bg_6.height = 98;
            this.addQuiackChild(bg_6);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_5 = new Button(texture);
            bg_5.name= 'bg_5';
            bg_5.x = 678;
            bg_5.y = 99;
            bg_5.width = 98;
            bg_5.height = 98;
            this.addQuiackChild(bg_5);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_4 = new Button(texture);
            bg_4.name= 'bg_4';
            bg_4.x = 557;
            bg_4.y = 99;
            bg_4.width = 98;
            bg_4.height = 98;
            this.addQuiackChild(bg_4);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_3 = new Button(texture);
            bg_3.name= 'bg_3';
            bg_3.x = 436;
            bg_3.y = 99;
            bg_3.width = 98;
            bg_3.height = 98;
            this.addQuiackChild(bg_3);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_2 = new Button(texture);
            bg_2.name= 'bg_2';
            bg_2.x = 315;
            bg_2.y = 99;
            bg_2.width = 98;
            bg_2.height = 98;
            this.addQuiackChild(bg_2);
            texture = assetMgr.getTexture('ui_daojukuangdi');
            bg_1 = new Button(texture);
            bg_1.name= 'bg_1';
            bg_1.x = 194;
            bg_1.y = 99;
            bg_1.width = 98;
            bg_1.height = 98;
            this.addQuiackChild(bg_1);
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var rankScale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            rankScale9Button = new Scale9Button(texture,rankScale9ButtonRect);
            rankScale9Button.x = 720;
            rankScale9Button.y = 528;
            rankScale9Button.width = 186;
            rankScale9Button.height = 70;
            this.addQuiackChild(rankScale9Button);
            rankScale9Button.name = 'rankScale9Button';
            rankScale9Button.text= 'lable';
            rankScale9Button.fontColor= 0xFFFFFF;
            rankScale9Button.fontSize= 24;
            texture = assetMgr.getTexture('icon_1201')
            icon_0 = new Image(texture);
            icon_0.x = 78;
            icon_0.y = 104;
            icon_0.width = 89;
            icon_0.height = 89;
            this.addQuiackChild(icon_0);
            icon_0.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_10 = new Image(texture);
            icon_10.x = 562;
            icon_10.y = 223;
            icon_10.width = 89;
            icon_10.height = 89;
            this.addQuiackChild(icon_10);
            icon_10.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_9 = new Image(texture);
            icon_9.x = 320;
            icon_9.y = 223;
            icon_9.width = 89;
            icon_9.height = 89;
            this.addQuiackChild(icon_9);
            icon_9.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_8 = new Image(texture);
            icon_8.x = 199;
            icon_8.y = 223;
            icon_8.width = 89;
            icon_8.height = 89;
            this.addQuiackChild(icon_8);
            icon_8.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_7 = new Image(texture);
            icon_7.x = 78;
            icon_7.y = 223;
            icon_7.width = 89;
            icon_7.height = 89;
            this.addQuiackChild(icon_7);
            icon_7.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_6 = new Image(texture);
            icon_6.x = 804;
            icon_6.y = 104;
            icon_6.width = 89;
            icon_6.height = 89;
            this.addQuiackChild(icon_6);
            icon_6.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_5 = new Image(texture);
            icon_5.x = 683;
            icon_5.y = 104;
            icon_5.width = 89;
            icon_5.height = 89;
            this.addQuiackChild(icon_5);
            icon_5.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_4 = new Image(texture);
            icon_4.x = 562;
            icon_4.y = 104;
            icon_4.width = 89;
            icon_4.height = 89;
            this.addQuiackChild(icon_4);
            icon_4.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_3 = new Image(texture);
            icon_3.x = 441;
            icon_3.y = 104;
            icon_3.width = 89;
            icon_3.height = 89;
            this.addQuiackChild(icon_3);
            icon_3.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_2 = new Image(texture);
            icon_2.x = 320;
            icon_2.y = 104;
            icon_2.width = 89;
            icon_2.height = 89;
            this.addQuiackChild(icon_2);
            icon_2.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_1 = new Image(texture);
            icon_1.x = 199;
            icon_1.y = 104;
            icon_1.width = 89;
            icon_1.height = 89;
            this.addQuiackChild(icon_1);
            icon_1.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_19 = new Image(texture);
            icon_19.x = 804;
            icon_19.y = 339;
            icon_19.width = 89;
            icon_19.height = 89;
            this.addQuiackChild(icon_19);
            icon_19.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_18 = new Image(texture);
            icon_18.x = 683;
            icon_18.y = 339;
            icon_18.width = 89;
            icon_18.height = 89;
            this.addQuiackChild(icon_18);
            icon_18.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_17 = new Image(texture);
            icon_17.x = 562;
            icon_17.y = 339;
            icon_17.width = 89;
            icon_17.height = 89;
            this.addQuiackChild(icon_17);
            icon_17.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_16 = new Image(texture);
            icon_16.x = 441;
            icon_16.y = 339;
            icon_16.width = 89;
            icon_16.height = 89;
            this.addQuiackChild(icon_16);
            icon_16.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_15 = new Image(texture);
            icon_15.x = 320;
            icon_15.y = 339;
            icon_15.width = 89;
            icon_15.height = 89;
            this.addQuiackChild(icon_15);
            icon_15.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_14 = new Image(texture);
            icon_14.x = 199;
            icon_14.y = 339;
            icon_14.width = 89;
            icon_14.height = 89;
            this.addQuiackChild(icon_14);
            icon_14.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_13 = new Image(texture);
            icon_13.x = 78;
            icon_13.y = 339;
            icon_13.width = 89;
            icon_13.height = 89;
            this.addQuiackChild(icon_13);
            icon_13.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_12 = new Image(texture);
            icon_12.x = 804;
            icon_12.y = 223;
            icon_12.width = 89;
            icon_12.height = 89;
            this.addQuiackChild(icon_12);
            icon_12.touchable = false;
            texture = assetMgr.getTexture('icon_1201')
            icon_11 = new Image(texture);
            icon_11.x = 683;
            icon_11.y = 223;
            icon_11.width = 89;
            icon_11.height = 89;
            this.addQuiackChild(icon_11);
            icon_11.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item1 = new Image(texture);
            item1.x = 194;
            item1.y = 99;
            item1.width = 98;
            item1.height = 98;
            this.addQuiackChild(item1);
            item1.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item0 = new Image(texture);
            item0.x = 73;
            item0.y = 99;
            item0.width = 98;
            item0.height = 98;
            this.addQuiackChild(item0);
            item0.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item2 = new Image(texture);
            item2.x = 315;
            item2.y = 99;
            item2.width = 98;
            item2.height = 98;
            this.addQuiackChild(item2);
            item2.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item3 = new Image(texture);
            item3.x = 436;
            item3.y = 99;
            item3.width = 98;
            item3.height = 98;
            this.addQuiackChild(item3);
            item3.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item4 = new Image(texture);
            item4.x = 557;
            item4.y = 99;
            item4.width = 98;
            item4.height = 98;
            this.addQuiackChild(item4);
            item4.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item5 = new Image(texture);
            item5.x = 678;
            item5.y = 99;
            item5.width = 98;
            item5.height = 98;
            this.addQuiackChild(item5);
            item5.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item6 = new Image(texture);
            item6.x = 799;
            item6.y = 99;
            item6.width = 98;
            item6.height = 98;
            this.addQuiackChild(item6);
            item6.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item8 = new Image(texture);
            item8.x = 194;
            item8.y = 218;
            item8.width = 98;
            item8.height = 98;
            this.addQuiackChild(item8);
            item8.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item7 = new Image(texture);
            item7.x = 73;
            item7.y = 218;
            item7.width = 98;
            item7.height = 98;
            this.addQuiackChild(item7);
            item7.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item9 = new Image(texture);
            item9.x = 315;
            item9.y = 218;
            item9.width = 98;
            item9.height = 98;
            this.addQuiackChild(item9);
            item9.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item10 = new Image(texture);
            item10.x = 557;
            item10.y = 218;
            item10.width = 98;
            item10.height = 98;
            this.addQuiackChild(item10);
            item10.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item11 = new Image(texture);
            item11.x = 678;
            item11.y = 218;
            item11.width = 98;
            item11.height = 98;
            this.addQuiackChild(item11);
            item11.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item12 = new Image(texture);
            item12.x = 799;
            item12.y = 218;
            item12.width = 98;
            item12.height = 98;
            this.addQuiackChild(item12);
            item12.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item14 = new Image(texture);
            item14.x = 194;
            item14.y = 334;
            item14.width = 98;
            item14.height = 98;
            this.addQuiackChild(item14);
            item14.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item13 = new Image(texture);
            item13.x = 73;
            item13.y = 334;
            item13.width = 98;
            item13.height = 98;
            this.addQuiackChild(item13);
            item13.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item15 = new Image(texture);
            item15.x = 315;
            item15.y = 334;
            item15.width = 98;
            item15.height = 98;
            this.addQuiackChild(item15);
            item15.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item16 = new Image(texture);
            item16.x = 436;
            item16.y = 334;
            item16.width = 98;
            item16.height = 98;
            this.addQuiackChild(item16);
            item16.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item17 = new Image(texture);
            item17.x = 557;
            item17.y = 334;
            item17.width = 98;
            item17.height = 98;
            this.addQuiackChild(item17);
            item17.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item18 = new Image(texture);
            item18.x = 678;
            item18.y = 334;
            item18.width = 98;
            item18.height = 98;
            this.addQuiackChild(item18);
            item18.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            item19 = new Image(texture);
            item19.x = 799;
            item19.y = 334;
            item19.width = 98;
            item19.height = 98;
            this.addQuiackChild(item19);
            item19.touchable = false;
            texture = assetMgr.getTexture('ui_xuanzhongfaguang01_jiemian');
            var turnMCRect:Rectangle = new Rectangle(30,30,10,10);
            var turnMC9ScaleTexture:Scale9Textures = new Scale9Textures(texture,turnMCRect);
            turnMC = new Scale9Image(turnMC9ScaleTexture);
            turnMC.x = 68;
            turnMC.y = 92;
            turnMC.width = 108;
            turnMC.height = 108;
            this.addQuiackChild(turnMC);
            text_0 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_0.touchable = false;
            text_0.hAlign= 'left';
            text_0.text= '';
            text_0.x = 84;
            text_0.y = 159;
            this.addQuiackChild(text_0);
            text_6 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_6.touchable = false;
            text_6.hAlign= 'left';
            text_6.text= '';
            text_6.x = 811;
            text_6.y = 159;
            this.addQuiackChild(text_6);
            text_18 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_18.touchable = false;
            text_18.hAlign= 'left';
            text_18.text= '';
            text_18.x = 691;
            text_18.y = 393;
            this.addQuiackChild(text_18);
            text_17 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_17.touchable = false;
            text_17.hAlign= 'left';
            text_17.text= '';
            text_17.x = 569;
            text_17.y = 393;
            this.addQuiackChild(text_17);
            text_16 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_16.touchable = false;
            text_16.hAlign= 'left';
            text_16.text= '';
            text_16.x = 449;
            text_16.y = 393;
            this.addQuiackChild(text_16);
            text_15 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_15.touchable = false;
            text_15.hAlign= 'left';
            text_15.text= '';
            text_15.x = 328;
            text_15.y = 393;
            this.addQuiackChild(text_15);
            text_14 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_14.touchable = false;
            text_14.hAlign= 'left';
            text_14.text= '';
            text_14.x = 206;
            text_14.y = 393;
            this.addQuiackChild(text_14);
            text_13 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_13.touchable = false;
            text_13.hAlign= 'left';
            text_13.text= '';
            text_13.x = 84;
            text_13.y = 393;
            this.addQuiackChild(text_13);
            text_12 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_12.touchable = false;
            text_12.hAlign= 'left';
            text_12.text= '';
            text_12.x = 811;
            text_12.y = 278;
            this.addQuiackChild(text_12);
            text_11 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_11.touchable = false;
            text_11.hAlign= 'left';
            text_11.text= '';
            text_11.x = 691;
            text_11.y = 278;
            this.addQuiackChild(text_11);
            text_10 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_10.touchable = false;
            text_10.hAlign= 'left';
            text_10.text= '';
            text_10.x = 569;
            text_10.y = 278;
            this.addQuiackChild(text_10);
            text_9 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_9.touchable = false;
            text_9.hAlign= 'left';
            text_9.text= '';
            text_9.x = 328;
            text_9.y = 278;
            this.addQuiackChild(text_9);
            text_8 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_8.touchable = false;
            text_8.hAlign= 'left';
            text_8.text= '';
            text_8.x = 206;
            text_8.y = 278;
            this.addQuiackChild(text_8);
            text_7 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_7.touchable = false;
            text_7.hAlign= 'left';
            text_7.text= '';
            text_7.x = 84;
            text_7.y = 278;
            this.addQuiackChild(text_7);
            text_19 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_19.touchable = false;
            text_19.hAlign= 'left';
            text_19.text= '';
            text_19.x = 811;
            text_19.y = 393;
            this.addQuiackChild(text_19);
            text_5 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_5.touchable = false;
            text_5.hAlign= 'left';
            text_5.text= '';
            text_5.x = 691;
            text_5.y = 159;
            this.addQuiackChild(text_5);
            text_4 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_4.touchable = false;
            text_4.hAlign= 'left';
            text_4.text= '';
            text_4.x = 569;
            text_4.y = 159;
            this.addQuiackChild(text_4);
            text_3 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_3.touchable = false;
            text_3.hAlign= 'left';
            text_3.text= '';
            text_3.x = 449;
            text_3.y = 159;
            this.addQuiackChild(text_3);
            text_2 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_2.touchable = false;
            text_2.hAlign= 'left';
            text_2.text= '';
            text_2.x = 328;
            text_2.y = 159;
            this.addQuiackChild(text_2);
            text_1 = new TextField(75,31,'','',24,0xFFFFFF,false);
            text_1.touchable = false;
            text_1.hAlign= 'left';
            text_1.text= '';
            text_1.x = 206;
            text_1.y = 159;
            this.addQuiackChild(text_1);
            text_rebateDes = new TextField(402,130,'','',24,0xFFFFFF,false);
            text_rebateDes.touchable = false;
            text_rebateDes.hAlign= 'left';
            text_rebateDes.text= '';
            text_rebateDes.x = 303;
            text_rebateDes.y = 461;
            this.addQuiackChild(text_rebateDes);
            text_diamand = new TextField(135,64,'','',38,0xFF6633,false);
            text_diamand.touchable = false;
            text_diamand.hAlign= 'center';
            text_diamand.text= '';
            text_diamand.x = 66;
            text_diamand.y = 497;
            this.addQuiackChild(text_diamand);
            diamond = new TextField(85,32,'','',25,0x00FF00,false);
            diamond.touchable = false;
            diamond.hAlign= 'center';
            diamond.text= '';
            diamond.x = 200;
            diamond.y = 512;
            this.addQuiackChild(diamond);
            star = new TextField(93,38,'','',30,0xFFFFFF,false);
            star.touchable = false;
            star.hAlign= 'center';
            star.text= '';
            star.x = 784;
            star.y = 476;
            this.addQuiackChild(star);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            run.dispose();
            but_lucky.dispose();
            closeBtn.dispose();
            bg_0.dispose();
            bg_16.dispose();
            bg_19.dispose();
            bg_18.dispose();
            bg_17.dispose();
            bg_15.dispose();
            bg_14.dispose();
            bg_13.dispose();
            bg_12.dispose();
            bg_11.dispose();
            bg_10.dispose();
            bg_9.dispose();
            bg_8.dispose();
            bg_7.dispose();
            bg_6.dispose();
            bg_5.dispose();
            bg_4.dispose();
            bg_3.dispose();
            bg_2.dispose();
            bg_1.dispose();
            super.dispose();
        
}
    }
}
