package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import game.view.luckyStar.LastItemRender;
    import game.view.luckyStar.RichItemRender;
    import com.dialog.Dialog;

    public class LuckyRankBase extends Dialog
    {
        public var ui_tipstanchukuangdi01_jiemian00:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian44332:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian4465:Scale9Image;
        public var nameListTxt:TextField;
        public var ui_zhuangshixianquan01_jiemian4472:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian46365:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian46103:Scale9Image;
        public var view_2:Sprite;
        public var bg_1:LastItemRender;
        public var bg_2:LastItemRender;
        public var bg_3:LastItemRender;
        public var bg_4:LastItemRender;
        public var bg_5:LastItemRender;
        public var view_1:Sprite;
        public var bg1:RichItemRender;
        public var bg2:RichItemRender;
        public var bg3:RichItemRender;
        public var bg4:RichItemRender;
        public var bg5:RichItemRender;
        public var userNameTxt:TextField;
        public var starTxt:TextField;
        public var valueTxt:TextField;
        public var nTxt:TextField;
        public var rewardTxt:TextField;

        public function LuckyRankBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian00Rect:Rectangle = new Rectangle(68,64,6,6);
            var ui_tipstanchukuangdi01_jiemian009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian00Rect);
            ui_tipstanchukuangdi01_jiemian00 = new Scale9Image(ui_tipstanchukuangdi01_jiemian009ScaleTexture);
            ui_tipstanchukuangdi01_jiemian00.width = 600;
            ui_tipstanchukuangdi01_jiemian00.height = 604;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian00);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian44332Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian443329ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian44332Rect);
            ui_zhuangshixianquan01_jiemian44332 = new Scale9Image(ui_zhuangshixianquan01_jiemian443329ScaleTexture);
            ui_zhuangshixianquan01_jiemian44332.x = 44;
            ui_zhuangshixianquan01_jiemian44332.y = 332;
            ui_zhuangshixianquan01_jiemian44332.width = 512;
            ui_zhuangshixianquan01_jiemian44332.height = 225;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian44332);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian4465Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian44659ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian4465Rect);
            ui_zhuangshixianquan02_jiemian4465 = new Scale9Image(ui_zhuangshixianquan02_jiemian44659ScaleTexture);
            ui_zhuangshixianquan02_jiemian4465.x = 44;
            ui_zhuangshixianquan02_jiemian4465.y = 65;
            ui_zhuangshixianquan02_jiemian4465.width = 512;
            ui_zhuangshixianquan02_jiemian4465.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian4465);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 50;
            image.y = 41;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 550;
            image.y = 41;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 257;
            image.y = 64;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 343;
            image.y = 64;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            nameListTxt = new TextField(204,32,'','',24,0xFFFFFF,false);
            nameListTxt.touchable = false;
            nameListTxt.hAlign= 'center';
            nameListTxt.text= '';
            nameListTxt.x = 198;
            nameListTxt.y = 298;
            this.addQuiackChild(nameListTxt);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian4472Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian44729ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian4472Rect);
            ui_zhuangshixianquan01_jiemian4472 = new Scale9Image(ui_zhuangshixianquan01_jiemian44729ScaleTexture);
            ui_zhuangshixianquan01_jiemian4472.x = 44;
            ui_zhuangshixianquan01_jiemian4472.y = 72;
            ui_zhuangshixianquan01_jiemian4472.width = 512;
            ui_zhuangshixianquan01_jiemian4472.height = 223;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian4472);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian46365Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian463659ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian46365Rect);
            ui_zhuangshixianquan02_jiemian46365 = new Scale9Image(ui_zhuangshixianquan02_jiemian463659ScaleTexture);
            ui_zhuangshixianquan02_jiemian46365.x = 46;
            ui_zhuangshixianquan02_jiemian46365.y = 365;
            ui_zhuangshixianquan02_jiemian46365.width = 508;
            ui_zhuangshixianquan02_jiemian46365.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian46365);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian46103Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian461039ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian46103Rect);
            ui_zhuangshixianquan02_jiemian46103 = new Scale9Image(ui_zhuangshixianquan02_jiemian461039ScaleTexture);
            ui_zhuangshixianquan02_jiemian46103.x = 46;
            ui_zhuangshixianquan02_jiemian46103.y = 103;
            ui_zhuangshixianquan02_jiemian46103.width = 508;
            ui_zhuangshixianquan02_jiemian46103.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian46103);
            texture =assetMgr.getTexture('ui_caifubang_xiaotaitou_wenzi');
            image = new Image(texture);
            image.x = 261;
            image.y = 33;
            image.width = 78;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            view_2 = new Sprite();
            view_2.x = 48;
            view_2.y = 370;
            view_2.width = 504;
            view_2.height = 181;
            this.addQuiackChild(view_2);
            view_2.name= 'view_2';
            bg_1 = new LastItemRender();
            view_2.addQuiackChild(bg_1);
            bg_2 = new LastItemRender();
            bg_2.y = 38;
            view_2.addQuiackChild(bg_2);
            bg_3 = new LastItemRender();
            bg_3.y = 76;
            view_2.addQuiackChild(bg_3);
            bg_4 = new LastItemRender();
            bg_4.y = 113;
            view_2.addQuiackChild(bg_4);
            bg_5 = new LastItemRender();
            bg_5.y = 151;
            view_2.addQuiackChild(bg_5);
            view_1 = new Sprite();
            view_1.x = 47;
            view_1.y = 109;
            view_1.width = 504;
            view_1.height = 179;
            this.addQuiackChild(view_1);
            view_1.name= 'view_1';
            bg1 = new RichItemRender();
            view_1.addQuiackChild(bg1);
            bg2 = new RichItemRender();
            bg2.y = 37;
            view_1.addQuiackChild(bg2);
            bg3 = new RichItemRender();
            bg3.y = 75;
            view_1.addQuiackChild(bg3);
            bg4 = new RichItemRender();
            bg4.y = 112;
            view_1.addQuiackChild(bg4);
            bg5 = new RichItemRender();
            bg5.y = 149;
            view_1.addQuiackChild(bg5);
            userNameTxt = new TextField(152,28,'','',20,0xCCCCCC,false);
            userNameTxt.touchable = false;
            userNameTxt.hAlign= 'center';
            userNameTxt.text= '';
            userNameTxt.x = 58;
            userNameTxt.y = 74;
            this.addQuiackChild(userNameTxt);
            starTxt = new TextField(152,28,'','',20,0xCCCCCC,false);
            starTxt.touchable = false;
            starTxt.hAlign= 'center';
            starTxt.text= '';
            starTxt.x = 219;
            starTxt.y = 74;
            this.addQuiackChild(starTxt);
            valueTxt = new TextField(152,28,'','',20,0xCCCCCC,false);
            valueTxt.touchable = false;
            valueTxt.hAlign= 'center';
            valueTxt.text= '';
            valueTxt.x = 390;
            valueTxt.y = 74;
            this.addQuiackChild(valueTxt);
            nTxt = new TextField(196,28,'','',20,0xCCCCCC,false);
            nTxt.touchable = false;
            nTxt.hAlign= 'center';
            nTxt.text= '';
            nTxt.x = 53;
            nTxt.y = 335;
            this.addQuiackChild(nTxt);
            rewardTxt = new TextField(248,28,'','',20,0xCCCCCC,false);
            rewardTxt.touchable = false;
            rewardTxt.hAlign= 'center';
            rewardTxt.text= '';
            rewardTxt.x = 299;
            rewardTxt.y = 335;
            this.addQuiackChild(rewardTxt);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 548;
            image.y = 46;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 52;
            image.y = 46;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            bg_1.dispose();
            bg_2.dispose();
            bg_3.dispose();
            bg_4.dispose();
            bg_5.dispose();
            view_2.dispose();
            bg1.dispose();
            bg2.dispose();
            bg3.dispose();
            bg4.dispose();
            bg5.dispose();
            view_1.dispose();
            super.dispose();
        
}
    }
}
