package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.controls.List;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.view.View;

    public class MagicSwallowViewBase extends View
    {
        public var ui_zhuangshixianquan03_jiemian51588:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian529102:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian533373:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian533138:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian533374:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian533139:Scale9Image;
        public var bgImage1:Scale9Image;
        public var bgImage2:Scale9Image;
        public var cancel_Scale9Button:Scale9Button;
        public var SelectQuality:Image;
        public var SelectQuality1:Image;
        public var bgImage0:Scale9Image;
        public var ok_Scale9Button:Scale9Button;
        public var Select_Scale9Button:Scale9Button;
        public var list_Swall:List;
        public var nextExpBar:Sprite;
        public var currentExpBar:Sprite;
        public var selectIcon:Image;
        public var selectIcon1:Image;
        public var text_Lv1:TextField;
        public var text_currentProperty:TextField;
        public var text_Lv2:TextField;
        public var text_nextProperty:TextField;
        public var text_currentExp:TextField;
        public var text_money:TextField;
        public var text_useup:TextField;
        public var text_attack1:TextField;
        public var text_attack2:TextField;

        public function MagicSwallowViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_zhuangshixianquan03_jiemian');
            var ui_zhuangshixianquan03_jiemian51588Rect:Rectangle = new Rectangle(30,30,10,10);
            var ui_zhuangshixianquan03_jiemian515889ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan03_jiemian51588Rect);
            ui_zhuangshixianquan03_jiemian51588 = new Scale9Image(ui_zhuangshixianquan03_jiemian515889ScaleTexture);
            ui_zhuangshixianquan03_jiemian51588.x = 515;
            ui_zhuangshixianquan03_jiemian51588.y = 88;
            ui_zhuangshixianquan03_jiemian51588.width = 422;
            ui_zhuangshixianquan03_jiemian51588.height = 384;
            this.addQuiackChild(ui_zhuangshixianquan03_jiemian51588);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian529102Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian5291029ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian529102Rect);
            ui_zhuangshixianquan01_jiemian529102 = new Scale9Image(ui_zhuangshixianquan01_jiemian5291029ScaleTexture);
            ui_zhuangshixianquan01_jiemian529102.x = 529;
            ui_zhuangshixianquan01_jiemian529102.y = 102;
            ui_zhuangshixianquan01_jiemian529102.width = 394;
            ui_zhuangshixianquan01_jiemian529102.height = 322;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian529102);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 538;
            image.y = 105;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 914;
            image.y = 105;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian533373Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian5333739ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian533373Rect);
            ui_zhuangshixianquan02_jiemian533373 = new Scale9Image(ui_zhuangshixianquan02_jiemian5333739ScaleTexture);
            ui_zhuangshixianquan02_jiemian533373.x = 533;
            ui_zhuangshixianquan02_jiemian533373.y = 373;
            ui_zhuangshixianquan02_jiemian533373.width = 386;
            ui_zhuangshixianquan02_jiemian533373.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian533373);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian533138Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian5331389ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian533138Rect);
            ui_zhuangshixianquan02_jiemian533138 = new Scale9Image(ui_zhuangshixianquan02_jiemian5331389ScaleTexture);
            ui_zhuangshixianquan02_jiemian533138.x = 533;
            ui_zhuangshixianquan02_jiemian533138.y = 138;
            ui_zhuangshixianquan02_jiemian533138.width = 386;
            ui_zhuangshixianquan02_jiemian533138.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian533138);
            texture =assetMgr.getTexture('ui_tunshi_xiaotaitou_wenzi');
            image = new Image(texture);
            image.x = 699;
            image.y = 107;
            image.width = 54;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 551;
            image.y = 195;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 709;
            image.y = 195;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 550;
            image.y = 318;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 710;
            image.y = 318;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 630;
            image.y = 360;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 630;
            image.y = 360;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 630;
            image.y = 152;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 630;
            image.y = 152;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 822;
            image.y = 360;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 822;
            image.y = 360;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 822;
            image.y = 152;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 822;
            image.y = 152;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhishijiantou01_tubiao');
            image = new Image(texture);
            image.x = 695;
            image.y = 234;
            image.width = 61;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yingxionghundi_jindutiao');
            image = new Image(texture);
            image.x = 589;
            image.y = 381;
            image.width = 273;
            image.height = 38;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_jinbi01_tubiao');
            image = new Image(texture);
            image.x = 792;
            image.y = 428;
            image.width = 25;
            image.height = 26;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 706;
            image.y = 201;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 911;
            image.y = 111;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 554;
            image.y = 201;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 540;
            image.y = 111;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 554;
            image.y = 311;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 706;
            image.y = 311;
            image.width = 8;
            image.height = 33;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 743;
            image.y = 195;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 901;
            image.y = 195;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 742;
            image.y = 318;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 902;
            image.y = 318;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 898;
            image.y = 201;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 746;
            image.y = 201;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 746;
            image.y = 311;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 898;
            image.y = 311;
            image.width = 8;
            image.height = 33;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian533374Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian5333749ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian533374Rect);
            ui_zhuangshixianquan02_jiemian533374 = new Scale9Image(ui_zhuangshixianquan02_jiemian5333749ScaleTexture);
            ui_zhuangshixianquan02_jiemian533374.x = 533;
            ui_zhuangshixianquan02_jiemian533374.y = 374;
            ui_zhuangshixianquan02_jiemian533374.width = 386;
            ui_zhuangshixianquan02_jiemian533374.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian533374);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian533139Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian5331399ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian533139Rect);
            ui_zhuangshixianquan02_jiemian533139 = new Scale9Image(ui_zhuangshixianquan02_jiemian5331399ScaleTexture);
            ui_zhuangshixianquan02_jiemian533139.x = 533;
            ui_zhuangshixianquan02_jiemian533139.y = 139;
            ui_zhuangshixianquan02_jiemian533139.width = 386;
            ui_zhuangshixianquan02_jiemian533139.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian533139);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage1Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage19ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage1Rect);
            bgImage1 = new Scale9Image(bgImage19ScaleTexture);
            bgImage1.x = 531;
            bgImage1.y = 154;
            bgImage1.width = 390;
            bgImage1.height = 38;
            this.addQuiackChild(bgImage1);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage2Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage29ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage2Rect);
            bgImage2 = new Scale9Image(bgImage29ScaleTexture);
            bgImage2.x = 531;
            bgImage2.y = 321;
            bgImage2.width = 390;
            bgImage2.height = 38;
            this.addQuiackChild(bgImage2);
            texture =assetMgr.getTexture('ui_daojukuangdi');
            image = new Image(texture);
            image.x = 581;
            image.y = 208;
            image.width = 98;
            image.height = 98;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_daojukuangdi');
            image = new Image(texture);
            image.x = 773;
            image.y = 208;
            image.width = 98;
            image.height = 98;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_hong02_01_anniu');
            var cancel_Scale9ButtonRect:Rectangle = new Rectangle(25,10,50,20);
            cancel_Scale9Button = new Scale9Button(texture,cancel_Scale9ButtonRect);
            cancel_Scale9Button.x = 549;
            cancel_Scale9Button.y = 486;
            cancel_Scale9Button.width = 150;
            cancel_Scale9Button.height = 39;
            this.addQuiackChild(cancel_Scale9Button);
            cancel_Scale9Button.name = 'cancel_Scale9Button';
            cancel_Scale9Button.text= 'lable';
            cancel_Scale9Button.fontColor= 0xFFFFFFB4;
            cancel_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_daojukuang01')
            SelectQuality = new Image(texture);
            SelectQuality.x = 581;
            SelectQuality.y = 208;
            SelectQuality.width = 98;
            SelectQuality.height = 98;
            this.addQuiackChild(SelectQuality);
            SelectQuality.touchable = false;
            texture = assetMgr.getTexture('ui_daojukuang01')
            SelectQuality1 = new Image(texture);
            SelectQuality1.x = 773;
            SelectQuality1.y = 208;
            SelectQuality1.width = 98;
            SelectQuality1.height = 98;
            this.addQuiackChild(SelectQuality1);
            SelectQuality1.touchable = false;
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage0Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage09ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage0Rect);
            bgImage0 = new Scale9Image(bgImage09ScaleTexture);
            bgImage0.x = 170;
            bgImage0.y = 92;
            bgImage0.width = 340;
            bgImage0.height = 440;
            this.addQuiackChild(bgImage0);
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var ok_Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            ok_Scale9Button = new Scale9Button(texture,ok_Scale9ButtonRect);
            ok_Scale9Button.x = 723;
            ok_Scale9Button.y = 474;
            ok_Scale9Button.width = 186;
            ok_Scale9Button.height = 70;
            this.addQuiackChild(ok_Scale9Button);
            ok_Scale9Button.name = 'ok_Scale9Button';
            ok_Scale9Button.text= 'lable';
            ok_Scale9Button.fontColor= 0xFFFFFF;
            ok_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_lan03_01_anniu');
            var Select_Scale9ButtonRect:Rectangle = new Rectangle(29,16,58,31);
            Select_Scale9Button = new Scale9Button(texture,Select_Scale9ButtonRect);
            Select_Scale9Button.x = 633;
            Select_Scale9Button.y = 474;
            Select_Scale9Button.width = 186;
            Select_Scale9Button.height = 70;
            this.addQuiackChild(Select_Scale9Button);
            Select_Scale9Button.name = 'Select_Scale9Button';
            Select_Scale9Button.text= 'lable';
            Select_Scale9Button.fontColor= 0xFFFFFF;
            Select_Scale9Button.fontSize= 24;
            list_Swall = new List();
            list_Swall.x = 181;
            list_Swall.y = 103;
            list_Swall.width = 318;
            list_Swall.height = 419;
            this.addQuiackChild(list_Swall);
            nextExpBar = new Sprite();
            nextExpBar.x = 589;
            nextExpBar.y = 381;
            nextExpBar.width = 273;
            nextExpBar.height = 38;
            this.addQuiackChild(nextExpBar);
            nextExpBar.name= 'nextExpBar';
            texture =assetMgr.getTexture('ui_yingxionghunding02_jindutiao');
            image = new Image(texture);
            image.width = 273;
            image.height = 38;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            nextExpBar.addQuiackChild(image);
            currentExpBar = new Sprite();
            currentExpBar.x = 589;
            currentExpBar.y = 381;
            currentExpBar.width = 273;
            currentExpBar.height = 38;
            this.addQuiackChild(currentExpBar);
            currentExpBar.name= 'currentExpBar';
            texture =assetMgr.getTexture('ui_yingxionghunding_jindutiao');
            image = new Image(texture);
            image.width = 273;
            image.height = 38;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            currentExpBar.addQuiackChild(image);
            texture = assetMgr.getTexture('icon_1208')
            selectIcon = new Image(texture);
            selectIcon.x = 585;
            selectIcon.y = 211;
            selectIcon.width = 89;
            selectIcon.height = 89;
            this.addQuiackChild(selectIcon);
            selectIcon.touchable = false;
            texture = assetMgr.getTexture('icon_1208')
            selectIcon1 = new Image(texture);
            selectIcon1.x = 777;
            selectIcon1.y = 211;
            selectIcon1.width = 89;
            selectIcon1.height = 89;
            this.addQuiackChild(selectIcon1);
            selectIcon1.touchable = false;
            text_Lv1 = new TextField(184,32,'','',24,0x33CC00,false);
            text_Lv1.touchable = false;
            text_Lv1.hAlign= 'center';
            text_Lv1.text= '';
            text_Lv1.x = 539;
            text_Lv1.y = 157;
            this.addQuiackChild(text_Lv1);
            text_currentProperty = new TextField(125,31,'','',22,0xFFFFFF,false);
            text_currentProperty.touchable = false;
            text_currentProperty.hAlign= 'center';
            text_currentProperty.text= '';
            text_currentProperty.x = 591;
            text_currentProperty.y = 324;
            this.addQuiackChild(text_currentProperty);
            text_Lv2 = new TextField(184,32,'','',24,0x33CC00,false);
            text_Lv2.touchable = false;
            text_Lv2.hAlign= 'center';
            text_Lv2.text= '';
            text_Lv2.x = 730;
            text_Lv2.y = 157;
            this.addQuiackChild(text_Lv2);
            text_nextProperty = new TextField(140,31,'','',22,0x33CC00,false);
            text_nextProperty.touchable = false;
            text_nextProperty.hAlign= 'center';
            text_nextProperty.text= '';
            text_nextProperty.x = 780;
            text_nextProperty.y = 324;
            this.addQuiackChild(text_nextProperty);
            text_currentExp = new TextField(244,27,'','',21,0xFFFFFF,false);
            text_currentExp.touchable = false;
            text_currentExp.hAlign= 'center';
            text_currentExp.text= '';
            text_currentExp.x = 604;
            text_currentExp.y = 384;
            this.addQuiackChild(text_currentExp);
            text_money = new TextField(100,32,'','',24,0xFFFFFF,false);
            text_money.touchable = false;
            text_money.hAlign= 'center';
            text_money.text= '';
            text_money.x = 688;
            text_money.y = 426;
            this.addQuiackChild(text_money);
            text_useup = new TextField(64,36,'','',24,0xFF0000,false);
            text_useup.touchable = false;
            text_useup.hAlign= 'center';
            text_useup.text= '';
            text_useup.x = 626;
            text_useup.y = 423;
            this.addQuiackChild(text_useup);
            text_attack1 = new TextField(50,31,'','',24,0xFFFFFF,false);
            text_attack1.touchable = false;
            text_attack1.hAlign= 'center';
            text_attack1.text= '';
            text_attack1.x = 539;
            text_attack1.y = 324;
            this.addQuiackChild(text_attack1);
            text_attack2 = new TextField(50,31,'','',24,0x33CC00,false);
            text_attack2.touchable = false;
            text_attack2.hAlign= 'center';
            text_attack2.text= '';
            text_attack2.x = 729;
            text_attack2.y = 324;
            this.addQuiackChild(text_attack2);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            list_Swall.dispose();
            nextExpBar.dispose();
            currentExpBar.dispose();
            super.dispose();
        
}
    }
}
