package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.controls.List;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.view.View;

    public class MainMapFigthViewBase extends View
    {
        public var bgImage3:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian27130:Scale9Image;
        public var bgImage1:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian2482:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian2481:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian50241:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian50242:Scale9Image;
        public var list_monster:List;
        public var list_goods:List;
        public var star_2:Image;
        public var star_0:Image;
        public var star_1:Image;
        public var figthBtn_Scale9Button:Scale9Button;
        public var txt_quangNum:TextField;
        public var noamBtn_Scale9Button:Scale9Button;
        public var emBtn_Scale9Button:Scale9Button;
        public var sdBtn_Scale9Button:Scale9Button;
        public var sdBtns_Scale9Button:Scale9Button;
        public var txt_zheng:TextField;
        public var txt_goods:TextField;
        public var txt_power:TextField;
        public var txt_quang:TextField;
        public var txt_pointName:TextField;
        public var txt_powerNum:TextField;
        public var btn_close:Button;

        public function MainMapFigthViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage3Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage39ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage3Rect);
            bgImage3 = new Scale9Image(bgImage39ScaleTexture);
            bgImage3.width = 880;
            bgImage3.height = 512;
            this.addQuiackChild(bgImage3);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian27130Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian271309ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian27130Rect);
            ui_zhuangshixianquan01_jiemian27130 = new Scale9Image(ui_zhuangshixianquan01_jiemian271309ScaleTexture);
            ui_zhuangshixianquan01_jiemian27130.x = 27;
            ui_zhuangshixianquan01_jiemian27130.y = 130;
            ui_zhuangshixianquan01_jiemian27130.width = 748;
            ui_zhuangshixianquan01_jiemian27130.height = 234;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian27130);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage1Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage19ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage1Rect);
            bgImage1 = new Scale9Image(bgImage19ScaleTexture);
            bgImage1.y = 400;
            bgImage1.width = 880;
            bgImage1.height = 80;
            this.addQuiackChild(bgImage1);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian2482Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian24829ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian2482Rect);
            ui_zhuangshixianquan02_jiemian2482 = new Scale9Image(ui_zhuangshixianquan02_jiemian24829ScaleTexture);
            ui_zhuangshixianquan02_jiemian2482.x = 24;
            ui_zhuangshixianquan02_jiemian2482.y = 82;
            ui_zhuangshixianquan02_jiemian2482.width = 760;
            ui_zhuangshixianquan02_jiemian2482.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian2482);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian2481Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian24819ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian2481Rect);
            ui_zhuangshixianquan02_jiemian2481 = new Scale9Image(ui_zhuangshixianquan02_jiemian24819ScaleTexture);
            ui_zhuangshixianquan02_jiemian2481.x = 24;
            ui_zhuangshixianquan02_jiemian2481.y = 81;
            ui_zhuangshixianquan02_jiemian2481.width = 760;
            ui_zhuangshixianquan02_jiemian2481.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian2481);
            texture =assetMgr.getTexture('ui_tili01_tubiao');
            image = new Image(texture);
            image.x = 217;
            image.y = 94;
            image.width = 25;
            image.height = 26;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian50241Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian502419ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian50241Rect);
            ui_zhuangshixianquan02_jiemian50241 = new Scale9Image(ui_zhuangshixianquan02_jiemian502419ScaleTexture);
            ui_zhuangshixianquan02_jiemian50241.x = 50;
            ui_zhuangshixianquan02_jiemian50241.y = 241;
            ui_zhuangshixianquan02_jiemian50241.width = 700;
            ui_zhuangshixianquan02_jiemian50241.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian50241);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian50242Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian502429ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian50242Rect);
            ui_zhuangshixianquan02_jiemian50242 = new Scale9Image(ui_zhuangshixianquan02_jiemian502429ScaleTexture);
            ui_zhuangshixianquan02_jiemian50242.x = 50;
            ui_zhuangshixianquan02_jiemian50242.y = 242;
            ui_zhuangshixianquan02_jiemian50242.width = 700;
            ui_zhuangshixianquan02_jiemian50242.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian50242);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 36;
            image.y = 133;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 766;
            image.y = 133;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 36;
            image.y = 361;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 766;
            image.y = 361;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            list_monster = new List();
            list_monster.x = 165;
            list_monster.y = 141;
            list_monster.width = 590;
            list_monster.height = 95;
            this.addQuiackChild(list_monster);
            list_goods = new List();
            list_goods.x = 165;
            list_goods.y = 248;
            list_goods.width = 590;
            list_goods.height = 105;
            this.addQuiackChild(list_goods);
            texture = assetMgr.getTexture('zhandoupingxing')
            star_2 = new Image(texture);
            star_2.x = 710;
            star_2.y = 6;
            star_2.width = 73;
            star_2.height = 73;
            this.addQuiackChild(star_2);
            star_2.touchable = false;
            texture = assetMgr.getTexture('zhandoupingxing')
            star_0 = new Image(texture);
            star_0.x = 651;
            star_0.y = 6;
            star_0.width = 73;
            star_0.height = 73;
            this.addQuiackChild(star_0);
            star_0.touchable = false;
            texture = assetMgr.getTexture('zhandoupingxing')
            star_1 = new Image(texture);
            star_1.x = 592;
            star_1.y = 6;
            star_1.width = 73;
            star_1.height = 73;
            this.addQuiackChild(star_1);
            star_1.touchable = false;
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var figthBtn_Scale9ButtonRect:Rectangle = new Rectangle(54,24,6,2);
            figthBtn_Scale9Button = new Scale9Button(texture,figthBtn_Scale9ButtonRect);
            figthBtn_Scale9Button.x = 577;
            figthBtn_Scale9Button.y = 408;
            figthBtn_Scale9Button.width = 186;
            figthBtn_Scale9Button.height = 70;
            this.addQuiackChild(figthBtn_Scale9Button);
            figthBtn_Scale9Button.name = 'figthBtn_Scale9Button';
            figthBtn_Scale9Button.text= 'lable';
            figthBtn_Scale9Button.fontColor= 0xFFFFC9;
            figthBtn_Scale9Button.fontSize= 28;
            txt_quangNum = new TextField(85,38,'','',30,0xFFFFFF,false);
            txt_quangNum.touchable = false;
            txt_quangNum.hAlign= 'center';
            txt_quangNum.text= '';
            txt_quangNum.x = 107;
            txt_quangNum.y = 421;
            this.addQuiackChild(txt_quangNum);
            texture = assetMgr.getTexture('ui_hong03_01_anniu');
            var noamBtn_Scale9ButtonRect:Rectangle = new Rectangle(29,19,58,18);
            noamBtn_Scale9Button = new Scale9Button(texture,noamBtn_Scale9ButtonRect);
            noamBtn_Scale9Button.x = 29;
            noamBtn_Scale9Button.y = 9;
            noamBtn_Scale9Button.width = 186;
            noamBtn_Scale9Button.height = 70;
            this.addQuiackChild(noamBtn_Scale9Button);
            noamBtn_Scale9Button.name = 'noamBtn_Scale9Button';
            noamBtn_Scale9Button.text= 'lable';
            noamBtn_Scale9Button.fontColor= 0xFFFFFF;
            noamBtn_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var emBtn_Scale9ButtonRect:Rectangle = new Rectangle(54,24,6,2);
            emBtn_Scale9Button = new Scale9Button(texture,emBtn_Scale9ButtonRect);
            emBtn_Scale9Button.x = 29;
            emBtn_Scale9Button.y = 9;
            emBtn_Scale9Button.width = 186;
            emBtn_Scale9Button.height = 70;
            this.addQuiackChild(emBtn_Scale9Button);
            emBtn_Scale9Button.name = 'emBtn_Scale9Button';
            emBtn_Scale9Button.text= 'lable';
            emBtn_Scale9Button.fontColor= 0xFFFFC9;
            emBtn_Scale9Button.fontSize= 28;
            texture = assetMgr.getTexture('ui_lan03_01_anniu');
            var sdBtn_Scale9ButtonRect:Rectangle = new Rectangle(54,24,6,2);
            sdBtn_Scale9Button = new Scale9Button(texture,sdBtn_Scale9ButtonRect);
            sdBtn_Scale9Button.x = 384;
            sdBtn_Scale9Button.y = 408;
            sdBtn_Scale9Button.width = 186;
            sdBtn_Scale9Button.height = 70;
            this.addQuiackChild(sdBtn_Scale9Button);
            sdBtn_Scale9Button.name = 'sdBtn_Scale9Button';
            sdBtn_Scale9Button.text= 'lable';
            sdBtn_Scale9Button.fontColor= 0xFFFFC9;
            sdBtn_Scale9Button.fontSize= 28;
            texture = assetMgr.getTexture('ui_lan03_01_anniu');
            var sdBtns_Scale9ButtonRect:Rectangle = new Rectangle(54,24,6,2);
            sdBtns_Scale9Button = new Scale9Button(texture,sdBtns_Scale9ButtonRect);
            sdBtns_Scale9Button.x = 193;
            sdBtns_Scale9Button.y = 408;
            sdBtns_Scale9Button.width = 186;
            sdBtns_Scale9Button.height = 70;
            this.addQuiackChild(sdBtns_Scale9Button);
            sdBtns_Scale9Button.name = 'sdBtns_Scale9Button';
            sdBtns_Scale9Button.text= 'lable';
            sdBtns_Scale9Button.fontColor= 0xFFFFC9;
            sdBtns_Scale9Button.fontSize= 28;
            txt_zheng = new TextField(106,32,'','',24,0xFFCC99,false);
            txt_zheng.touchable = false;
            txt_zheng.hAlign= 'left';
            txt_zheng.text= '';
            txt_zheng.x = 57;
            txt_zheng.y = 178;
            this.addQuiackChild(txt_zheng);
            txt_goods = new TextField(106,32,'','',24,0xFFCC99,false);
            txt_goods.touchable = false;
            txt_goods.hAlign= 'left';
            txt_goods.text= '';
            txt_goods.x = 57;
            txt_goods.y = 282;
            this.addQuiackChild(txt_goods);
            txt_power = new TextField(106,32,'','',24,0xFFCC99,false);
            txt_power.touchable = false;
            txt_power.hAlign= 'center';
            txt_power.text= '';
            txt_power.x = 57;
            txt_power.y = 91;
            this.addQuiackChild(txt_power);
            txt_quang = new TextField(80,32,'','',24,0xFFCC99,false);
            txt_quang.touchable = false;
            txt_quang.hAlign= 'right';
            txt_quang.text= '';
            txt_quang.x = 24;
            txt_quang.y = 424;
            this.addQuiackChild(txt_quang);
            txt_pointName = new TextField(324,38,'','',30,0xFFCC00,false);
            txt_pointName.touchable = false;
            txt_pointName.hAlign= 'center';
            txt_pointName.text= '';
            txt_pointName.x = 278;
            txt_pointName.y = 26;
            this.addQuiackChild(txt_pointName);
            txt_powerNum = new TextField(48,38,'','',30,0xFFFFFF,false);
            txt_powerNum.touchable = false;
            txt_powerNum.hAlign= 'center';
            txt_powerNum.text= '';
            txt_powerNum.x = 166;
            txt_powerNum.y = 88;
            this.addQuiackChild(txt_powerNum);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 764;
            image.y = 138;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 38;
            image.y = 138;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 764;
            image.y = 354;
            image.width = 8;
            image.height = 33;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 38;
            image.y = 354;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_guanbi01_anniu');
            btn_close = new Button(texture);
            btn_close.name= 'btn_close';
            btn_close.x = 839;
            btn_close.y = -26;
            btn_close.width = 72;
            btn_close.height = 76;
            this.addQuiackChild(btn_close);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            list_monster.dispose();
            list_goods.dispose();
            btn_close.dispose();
            super.dispose();
        
}
    }
}
