package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import com.view.View;

    public class Map_world_6Base extends View
    {
        public var bg:Sprite;
        public var point_83:Button;
        public var point_88:Button;
        public var point_89:Button;
        public var point_86:Button;
        public var point_85:Button;
        public var point_76:Button;
        public var point_80:Button;
        public var point_79:Button;
        public var point_77:Button;
        public var point_82:Button;
        public var point_90:Sprite;
        public var point_78:Sprite;
        public var point_87:Sprite;
        public var point_84:Sprite;
        public var point_81:Sprite;
        public var pointname:TextField;

        public function Map_world_6Base()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            bg = new Sprite();
            bg.width = 808;
            bg.height = 510;
            this.addQuiackChild(bg);
            bg.name= 'bg';
            texture =assetMgr.getTexture('ui_ditudi');
            image = new Image(texture);
            image.width = 803;
            image.height = 505;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave2');
            image = new Image(texture);
            image.x = 727;
            image.y = 241;
            image.width = 34;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain7');
            image = new Image(texture);
            image.x = 436;
            image.y = 260;
            image.width = 180;
            image.height = 103;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 526;
            image.y = 149;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 655;
            image.y = 445;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 721;
            image.y = 138;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 738;
            image.y = 160;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 698;
            image.y = 426;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 704;
            image.y = 356;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_rift1');
            image = new Image(texture);
            image.x = 669;
            image.y = 164;
            image.width = 257;
            image.height = 100;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 682;
            image.y = 285;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 712;
            image.y = 333;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 475;
            image.y = 25;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 315;
            image.y = 11;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 406;
            image.y = 26;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 750;
            image.y = 99;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 753;
            image.y = 122;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 747;
            image.y = 10;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 761;
            image.y = 155;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 754;
            image.y = 182;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 750;
            image.y = 208;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 747;
            image.y = 58;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 301;
            image.y = 442;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 741;
            image.y = 389;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 728;
            image.y = 415;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 1;
            image.y = 176;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 515;
            image.y = 144;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave5');
            image = new Image(texture);
            image.x = 178;
            image.y = 159;
            image.width = 181;
            image.height = 129;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave3');
            image = new Image(texture);
            image.x = 32;
            image.y = 219;
            image.width = 45;
            image.height = 42;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave2');
            image = new Image(texture);
            image.x = 157;
            image.y = 325;
            image.width = 34;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 2;
            image.y = 280;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 101;
            image.y = 378;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave3');
            image = new Image(texture);
            image.x = 205;
            image.y = 244;
            image.width = 45;
            image.height = 42;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 128;
            image.y = 339;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 449;
            image.y = 322;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 157;
            image.y = 396;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 183;
            image.y = -5;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 151;
            image.y = 9;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 105;
            image.y = 7;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 136;
            image.y = 34;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 392;
            image.y = 79;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 413;
            image.y = 85;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 426;
            image.y = 106;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 413;
            image.y = 142;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 439;
            image.y = 159;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 459;
            image.y = 71;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 247;
            image.y = 5;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 155;
            image.y = 50;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 254;
            image.y = 286;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 284;
            image.y = 264;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 316;
            image.y = 274;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 207;
            image.y = 278;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 114;
            image.y = 430;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 33;
            image.y = 4;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 10;
            image.y = 19;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 160;
            image.y = 254;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 37;
            image.y = 24;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 112;
            image.y = 60;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 83;
            image.y = 60;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 141;
            image.y = 291;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 207;
            image.y = 434;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 10;
            image.y = 95;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 28;
            image.y = 170;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 60;
            image.y = 88;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 52;
            image.y = 57;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 47;
            image.y = 121;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 477;
            image.y = 126;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 76;
            image.y = -1;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 186;
            image.y = 313;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 502;
            image.y = 65;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 697;
            image.y = 152;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 714;
            image.y = 177;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 481;
            image.y = 347;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 339;
            image.y = 432;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_dong');
            image = new Image(texture);
            image.x = 284;
            image.y = 382;
            image.width = 57;
            image.height = 60;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 231;
            image.y = 82;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 218;
            image.y = 96;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 187;
            image.y = 138;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 248;
            image.y = 76;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 125;
            image.y = 296;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 173;
            image.y = 152;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 125;
            image.y = 315;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 117;
            image.y = 331;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 89;
            image.y = 438;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 96;
            image.y = 454;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 449;
            image.y = 448;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 415;
            image.y = 421;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 430;
            image.y = 437;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 508;
            image.y = 461;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 528;
            image.y = 461;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 672;
            image.y = 298;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 679;
            image.y = 275;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 682;
            image.y = 254;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 421;
            image.y = 314;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 433;
            image.y = 274;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 431;
            image.y = 295;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 370;
            image.y = 139;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 352;
            image.y = 110;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 401;
            image.y = 223;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 624;
            image.y = 112;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 645;
            image.y = 185;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 379;
            image.y = 191;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 386;
            image.y = 208;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 660;
            image.y = 199;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 631;
            image.y = 169;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 155;
            image.y = 158;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 89;
            image.y = 177;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 86;
            image.y = 196;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 101;
            image.y = 162;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 67;
            image.y = 360;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 59;
            image.y = 376;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 59;
            image.y = 394;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 98;
            image.y = 472;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 364;
            image.y = 123;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 549;
            image.y = 457;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 641;
            image.y = 75;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 628;
            image.y = 92;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_biaotilan01');
            image = new Image(texture);
            image.x = 375;
            image.y = 24;
            image.width = 247;
            image.height = 61;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 192;
            image.y = 106;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 118;
            image.y = 146;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 82;
            image.y = 337;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 63;
            image.y = 404;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 413;
            image.y = 233;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 363;
            image.y = 156;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 616;
            image.y = 131;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 668;
            image.y = 215;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 568;
            image.y = 438;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 467;
            image.y = 446;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 606;
            image.y = 428;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 619;
            image.y = 413;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 628;
            image.y = 397;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('yanse_huang');
            image = new Image(texture);
            image.width = 803;
            image.height = 505;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_83 = new Button(texture);
            point_83.name= 'point_83';
            point_83.x = 408;
            point_83.y = 228;
            point_83.width = 41;
            point_83.height = 41;
            this.addQuiackChild(point_83);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_88 = new Button(texture);
            point_88.name= 'point_88';
            point_88.x = 663;
            point_88.y = 210;
            point_88.width = 41;
            point_88.height = 41;
            this.addQuiackChild(point_88);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_89 = new Button(texture);
            point_89.name= 'point_89';
            point_89.x = 611;
            point_89.y = 126;
            point_89.width = 41;
            point_89.height = 41;
            this.addQuiackChild(point_89);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_86 = new Button(texture);
            point_86.name= 'point_86';
            point_86.x = 563;
            point_86.y = 433;
            point_86.width = 41;
            point_86.height = 41;
            this.addQuiackChild(point_86);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_85 = new Button(texture);
            point_85.name= 'point_85';
            point_85.x = 462;
            point_85.y = 441;
            point_85.width = 41;
            point_85.height = 41;
            this.addQuiackChild(point_85);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_76 = new Button(texture);
            point_76.name= 'point_76';
            point_76.x = 58;
            point_76.y = 399;
            point_76.width = 41;
            point_76.height = 41;
            this.addQuiackChild(point_76);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_80 = new Button(texture);
            point_80.name= 'point_80';
            point_80.x = 187;
            point_80.y = 101;
            point_80.width = 41;
            point_80.height = 41;
            this.addQuiackChild(point_80);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_79 = new Button(texture);
            point_79.name= 'point_79';
            point_79.x = 113;
            point_79.y = 141;
            point_79.width = 41;
            point_79.height = 41;
            this.addQuiackChild(point_79);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_77 = new Button(texture);
            point_77.name= 'point_77';
            point_77.x = 77;
            point_77.y = 332;
            point_77.width = 41;
            point_77.height = 41;
            this.addQuiackChild(point_77);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_82 = new Button(texture);
            point_82.name= 'point_82';
            point_82.x = 358;
            point_82.y = 151;
            point_82.width = 41;
            point_82.height = 41;
            this.addQuiackChild(point_82);
            point_90 = new Sprite();
            point_90.x = 655;
            point_90.y = 33;
            point_90.width = 87;
            point_90.height = 104;
            this.addQuiackChild(point_90);
            point_90.name= 'point_90';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_90.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_90.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_03');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_90.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_90.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_90.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_90.addQuiackChild(image);
            image.touchable = false;
            point_78 = new Sprite();
            point_78.x = 68;
            point_78.y = 206;
            point_78.width = 87;
            point_78.height = 104;
            this.addQuiackChild(point_78);
            point_78.name= 'point_78';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_78.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_78.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_78.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_78.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_78.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_78.addQuiackChild(image);
            image.touchable = false;
            point_87 = new Sprite();
            point_87.x = 609;
            point_87.y = 306;
            point_87.width = 87;
            point_87.height = 104;
            this.addQuiackChild(point_87);
            point_87.name= 'point_87';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_87.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_87.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_87.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_87.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_87.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_87.addQuiackChild(image);
            image.touchable = false;
            point_84 = new Sprite();
            point_84.x = 368;
            point_84.y = 329;
            point_84.width = 87;
            point_84.height = 104;
            this.addQuiackChild(point_84);
            point_84.name= 'point_84';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_84.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_84.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_84.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_84.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_84.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_84.addQuiackChild(image);
            image.touchable = false;
            point_81 = new Sprite();
            point_81.x = 266;
            point_81.y = 42;
            point_81.width = 87;
            point_81.height = 104;
            this.addQuiackChild(point_81);
            point_81.name= 'point_81';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_81.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_81.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_81.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_81.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_81.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_81.addQuiackChild(image);
            image.touchable = false;
            pointname = new TextField(246,39,'','',32,0x000000,false);
            pointname.touchable = false;
            pointname.hAlign= 'center';
            pointname.text= '';
            pointname.x = 376;
            pointname.y = 31;
            this.addQuiackChild(pointname);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            bg.dispose();
            point_83.dispose();
            point_88.dispose();
            point_89.dispose();
            point_86.dispose();
            point_85.dispose();
            point_76.dispose();
            point_80.dispose();
            point_79.dispose();
            point_77.dispose();
            point_82.dispose();
            point_90.dispose();
            point_78.dispose();
            point_87.dispose();
            point_84.dispose();
            point_81.dispose();
            super.dispose();
        
}
    }
}
