package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import com.view.View;

    public class Map_world_101Base extends View
    {
        public var bg:Sprite;
        public var pointname:TextField;
        public var point_1001:Button;
        public var point_1002:Button;
        public var point_1003:Button;

        public function Map_world_101Base()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            bg = new Sprite();
            bg.y = -5;
            bg.width = 803;
            bg.height = 506;
            this.addQuiackChild(bg);
            bg.name= 'bg';
            texture =assetMgr.getTexture('ui_ditudi');
            image = new Image(texture);
            image.width = 803;
            image.height = 505;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 6;
            image.y = 88;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 3;
            image.y = 11;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 4;
            image.y = 182;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_rift2');
            image = new Image(texture);
            image.y = 269;
            image.width = 194;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 329;
            image.y = 125;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 317;
            image.y = 63;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain2');
            image = new Image(texture);
            image.x = 269;
            image.y = 5;
            image.width = 134;
            image.height = 91;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain2');
            image = new Image(texture);
            image.x = 231;
            image.y = 55;
            image.width = 134;
            image.height = 91;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 314;
            image.y = 383;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 341;
            image.y = 409;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 377;
            image.y = 433;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 323;
            image.y = 443;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 295;
            image.y = 406;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 262;
            image.y = 393;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 705;
            image.y = 313;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 410;
            image.y = 126;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree10');
            image = new Image(texture);
            image.x = 427;
            image.y = 199;
            image.width = 177;
            image.height = 131;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 453;
            image.y = 421;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_farmland2');
            image = new Image(texture);
            image.x = 532;
            image.y = 434;
            image.width = 72;
            image.height = 54;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 473;
            image.y = 437;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 415;
            image.y = 96;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain9');
            image = new Image(texture);
            image.x = 764;
            image.y = 100;
            image.width = 35;
            image.height = 28;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain9');
            image = new Image(texture);
            image.x = 768;
            image.y = 79;
            image.width = 35;
            image.height = 28;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 739;
            image.y = 368;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 698;
            image.y = 443;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house5');
            image = new Image(texture);
            image.x = 528;
            image.y = 418;
            image.width = 30;
            image.height = 35;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_farmland2');
            image = new Image(texture);
            image.x = 581;
            image.y = 403;
            image.width = 72;
            image.height = 54;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_farmland2');
            image = new Image(texture);
            image.x = 605;
            image.y = 427;
            image.width = 72;
            image.height = 54;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_farmland2');
            image = new Image(texture);
            image.x = 622;
            image.y = 351;
            image.width = 72;
            image.height = 54;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house3');
            image = new Image(texture);
            image.x = 664;
            image.y = 378;
            image.width = 111;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 675;
            image.y = 327;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 675;
            image.y = 443;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 535;
            image.y = 75;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 2;
            image.y = 360;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 234;
            image.y = 428;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 272;
            image.y = 435;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 213;
            image.y = 450;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 283;
            image.y = 366;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 440;
            image.y = 453;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 308;
            image.y = 11;
            image.width = 184;
            image.height = 134;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 682;
            image.y = 249;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 515;
            image.y = 94;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain2');
            image = new Image(texture);
            image.x = 509;
            image.y = 4;
            image.width = 134;
            image.height = 91;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 803;
            image.y = 132;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree10');
            image = new Image(texture);
            image.x = 379;
            image.width = 177;
            image.height = 131;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 493;
            image.y = 116;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 624;
            image.y = 5;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 243;
            image.y = 291;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 252;
            image.y = 303;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 253;
            image.y = 363;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 234;
            image.y = 387;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 118;
            image.y = 459;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 114;
            image.y = 472;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 156;
            image.y = 409;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 144;
            image.y = 418;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 171;
            image.y = 404;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 247;
            image.y = 377;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 113;
            image.y = 486;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 285;
            image.y = 177;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 303;
            image.y = 175;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 331;
            image.y = 192;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 320;
            image.y = 179;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 336;
            image.y = 210;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 355;
            image.y = 326;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 331;
            image.y = 300;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 341;
            image.y = 315;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 650;
            image.y = 304;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 631;
            image.y = 337;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 643;
            image.y = 321;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 567;
            image.y = 384;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 586;
            image.y = 375;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 546;
            image.y = 387;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 615;
            image.y = 223;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 639;
            image.y = 249;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 625;
            image.y = 238;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 565;
            image.y = 144;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 574;
            image.y = 131;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 560;
            image.y = 160;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 124;
            image.y = 443;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 132;
            image.y = 430;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 188;
            image.y = 401;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 204;
            image.y = 399;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 221;
            image.y = 395;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 257;
            image.y = 318;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 261;
            image.y = 334;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 259;
            image.y = 348;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 335;
            image.y = 231;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 327;
            image.y = 265;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 329;
            image.y = 247;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 325;
            image.y = 284;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 650;
            image.y = 265;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 654;
            image.y = 284;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 619;
            image.y = 353;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 602;
            image.y = 364;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_biaotilan01');
            image = new Image(texture);
            image.x = 36;
            image.y = 32;
            image.width = 247;
            image.height = 61;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('yanse_huang');
            image = new Image(texture);
            image.width = 803;
            image.height = 505;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            pointname = new TextField(246,39,'','',32,0x000000,false);
            pointname.touchable = false;
            pointname.hAlign= 'center';
            pointname.text= '';
            pointname.x = 35;
            pointname.y = 34;
            this.addQuiackChild(pointname);
            texture = assetMgr.getTexture('ui_fuben_eyun');
            point_1001 = new Button(texture);
            point_1001.name= 'point_1001';
            point_1001.x = 130;
            point_1001.y = 156;
            point_1001.width = 150;
            point_1001.height = 120;
            this.addQuiackChild(point_1001);
            texture = assetMgr.getTexture('ui_fuben_eyun');
            point_1002 = new Button(texture);
            point_1002.name= 'point_1002';
            point_1002.x = 374;
            point_1002.y = 306;
            point_1002.width = 150;
            point_1002.height = 120;
            this.addQuiackChild(point_1002);
            texture = assetMgr.getTexture('ui_fuben_eyun');
            point_1003 = new Button(texture);
            point_1003.name= 'point_1003';
            point_1003.x = 541;
            point_1003.y = 89;
            point_1003.width = 150;
            point_1003.height = 120;
            this.addQuiackChild(point_1003);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            bg.dispose();
            point_1001.dispose();
            point_1002.dispose();
            point_1003.dispose();
            super.dispose();
        
}
    }
}
