package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import com.view.View;

    public class Map_world_14Base extends View
    {
        public var bg:Sprite;
        public var point_203:Button;
        public var point_206:Button;
        public var point_205:Button;
        public var point_208:Button;
        public var point_196:Button;
        public var point_197:Button;
        public var point_199:Button;
        public var point_209:Button;
        public var point_200:Button;
        public var point_202:Button;
        public var point_210:Sprite;
        public var point_198:Sprite;
        public var point_201:Sprite;
        public var point_207:Sprite;
        public var point_204:Sprite;
        public var pointname:TextField;

        public function Map_world_14Base()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            bg = new Sprite();
            bg.width = 810;
            bg.height = 514;
            this.addQuiackChild(bg);
            bg.name= 'bg';
            texture =assetMgr.getTexture('ui_ditudi');
            image = new Image(texture);
            image.width = 803;
            image.height = 505;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 330;
            image.y = 200;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_rift2');
            image = new Image(texture);
            image.x = 503;
            image.y = 310;
            image.width = 194;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_rift1');
            image = new Image(texture);
            image.x = 368;
            image.y = 185;
            image.width = 257;
            image.height = 100;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 203;
            image.y = 223;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 28;
            image.y = 402;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 235;
            image.y = 368;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_rift2');
            image = new Image(texture);
            image.x = 39;
            image.y = 371;
            image.width = 194;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 363;
            image.y = -5;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.y = 1;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 97;
            image.y = 9;
            image.width = 136;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 231;
            image.y = 2;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 239;
            image.y = 100;
            image.width = 136;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain7');
            image = new Image(texture);
            image.x = 63;
            image.y = 313;
            image.width = 180;
            image.height = 103;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 256;
            image.y = 136;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain9');
            image = new Image(texture);
            image.x = 297;
            image.y = 465;
            image.width = 35;
            image.height = 28;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 512;
            image.y = 1;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 810;
            image.y = 180;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 799;
            image.y = 63;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 792;
            image.y = 112;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 805;
            image.y = 225;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave3');
            image = new Image(texture);
            image.x = 355;
            image.y = 455;
            image.width = 45;
            image.height = 42;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain9');
            image = new Image(texture);
            image.x = 685;
            image.y = 360;
            image.width = 35;
            image.height = 28;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain8');
            image = new Image(texture);
            image.x = 600;
            image.y = 272;
            image.width = 129;
            image.height = 97;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain6');
            image = new Image(texture);
            image.x = 434;
            image.y = 232;
            image.width = 111;
            image.height = 78;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 415;
            image.y = 264;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 769;
            image.y = 152;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 564;
            image.y = 1;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 585;
            image.y = -1;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain7');
            image = new Image(texture);
            image.x = 82;
            image.y = 351;
            image.width = 180;
            image.height = 103;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_biaotilan01');
            image = new Image(texture);
            image.x = 104;
            image.y = 409;
            image.width = 247;
            image.height = 61;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 395;
            image.y = 161;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 377;
            image.y = 170;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 445;
            image.y = 136;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 361;
            image.y = 181;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 231;
            image.y = 245;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 223;
            image.y = 227;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 233;
            image.y = 308;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 246;
            image.y = 319;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 471;
            image.y = 421;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 454;
            image.y = 409;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 448;
            image.y = 392;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 524;
            image.y = 421;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 544;
            image.y = 421;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 566;
            image.y = 431;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 643;
            image.y = 457;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 666;
            image.y = 449;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 320;
            image.y = 218;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 306;
            image.y = 232;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 295;
            image.y = 249;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 500;
            image.y = 294;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 541;
            image.y = 278;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 519;
            image.y = 284;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 604;
            image.y = 155;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 623;
            image.y = 165;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 636;
            image.y = 184;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 616;
            image.y = 250;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 618;
            image.y = 455;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 465;
            image.y = 129;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 486;
            image.y = 125;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 631;
            image.y = 236;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 598;
            image.y = 260;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 221;
            image.y = 210;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 52;
            image.y = 274;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 47;
            image.y = 295;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 44;
            image.y = 313;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 30;
            image.y = 395;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 38;
            image.y = 377;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 16;
            image.y = 413;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 229;
            image.y = 159;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 229;
            image.y = 138;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 224;
            image.y = 119;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 145;
            image.y = 112;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 160;
            image.y = 98;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 180;
            image.y = 92;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 67;
            image.y = 226;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 75;
            image.y = 210;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 212;
            image.y = 174;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 196;
            image.y = 89;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 47;
            image.y = 239;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 33;
            image.y = 335;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 330;
            image.y = 188;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 411;
            image.y = 137;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 630;
            image.y = 200;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 562;
            image.y = 259;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 487;
            image.y = 414;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 580;
            image.y = 437;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('yanse_zi');
            image = new Image(texture);
            image.width = 803;
            image.height = 505;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_203 = new Button(texture);
            point_203.name= 'point_203';
            point_203.x = 406;
            point_203.y = 132;
            point_203.width = 41;
            point_203.height = 41;
            this.addQuiackChild(point_203);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_206 = new Button(texture);
            point_206.name= 'point_206';
            point_206.x = 557;
            point_206.y = 254;
            point_206.width = 41;
            point_206.height = 41;
            this.addQuiackChild(point_206);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_205 = new Button(texture);
            point_205.name= 'point_205';
            point_205.x = 625;
            point_205.y = 195;
            point_205.width = 41;
            point_205.height = 41;
            this.addQuiackChild(point_205);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_208 = new Button(texture);
            point_208.name= 'point_208';
            point_208.x = 482;
            point_208.y = 409;
            point_208.width = 41;
            point_208.height = 41;
            this.addQuiackChild(point_208);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_196 = new Button(texture);
            point_196.name= 'point_196';
            point_196.x = 28;
            point_196.y = 330;
            point_196.width = 41;
            point_196.height = 41;
            this.addQuiackChild(point_196);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_197 = new Button(texture);
            point_197.name= 'point_197';
            point_197.x = 42;
            point_197.y = 234;
            point_197.width = 41;
            point_197.height = 41;
            this.addQuiackChild(point_197);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_199 = new Button(texture);
            point_199.name= 'point_199';
            point_199.x = 191;
            point_199.y = 84;
            point_199.width = 41;
            point_199.height = 41;
            this.addQuiackChild(point_199);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_209 = new Button(texture);
            point_209.name= 'point_209';
            point_209.x = 575;
            point_209.y = 432;
            point_209.width = 41;
            point_209.height = 41;
            this.addQuiackChild(point_209);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_200 = new Button(texture);
            point_200.name= 'point_200';
            point_200.x = 207;
            point_200.y = 169;
            point_200.width = 41;
            point_200.height = 41;
            this.addQuiackChild(point_200);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_202 = new Button(texture);
            point_202.name= 'point_202';
            point_202.x = 325;
            point_202.y = 183;
            point_202.width = 41;
            point_202.height = 41;
            this.addQuiackChild(point_202);
            point_210 = new Sprite();
            point_210.x = 687;
            point_210.y = 371;
            point_210.width = 87;
            point_210.height = 104;
            this.addQuiackChild(point_210);
            point_210.name= 'point_210';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_210.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_210.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_03');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_210.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_210.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_210.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_210.addQuiackChild(image);
            image.touchable = false;
            point_198 = new Sprite();
            point_198.x = 76;
            point_198.y = 115;
            point_198.width = 87;
            point_198.height = 104;
            this.addQuiackChild(point_198);
            point_198.name= 'point_198';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_198.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_198.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_198.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_198.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_198.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_198.addQuiackChild(image);
            image.touchable = false;
            point_201 = new Sprite();
            point_201.x = 223;
            point_201.y = 250;
            point_201.width = 87;
            point_201.height = 104;
            this.addQuiackChild(point_201);
            point_201.name= 'point_201';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_201.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_201.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_201.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_201.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_201.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_201.addQuiackChild(image);
            image.touchable = false;
            point_207 = new Sprite();
            point_207.x = 415;
            point_207.y = 283;
            point_207.width = 87;
            point_207.height = 104;
            this.addQuiackChild(point_207);
            point_207.name= 'point_207';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_207.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_207.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_207.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_207.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_207.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_207.addQuiackChild(image);
            image.touchable = false;
            point_204 = new Sprite();
            point_204.x = 511;
            point_204.y = 83;
            point_204.width = 87;
            point_204.height = 104;
            this.addQuiackChild(point_204);
            point_204.name= 'point_204';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_204.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_204.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_204.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_204.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_204.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_204.addQuiackChild(image);
            image.touchable = false;
            pointname = new TextField(246,39,'','',32,0x000000,false);
            pointname.touchable = false;
            pointname.hAlign= 'center';
            pointname.text= '';
            pointname.x = 103;
            pointname.y = 418;
            this.addQuiackChild(pointname);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            bg.dispose();
            point_203.dispose();
            point_206.dispose();
            point_205.dispose();
            point_208.dispose();
            point_196.dispose();
            point_197.dispose();
            point_199.dispose();
            point_209.dispose();
            point_200.dispose();
            point_202.dispose();
            point_210.dispose();
            point_198.dispose();
            point_201.dispose();
            point_207.dispose();
            point_204.dispose();
            super.dispose();
        
}
    }
}
