package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import com.view.View;

    public class Map_world_4Base extends View
    {
        public var bg:Sprite;
        public var pointname:TextField;
        public var point_53:Button;
        public var point_58:Button;
        public var point_59:Button;
        public var point_56:Button;
        public var point_55:Button;
        public var point_47:Button;
        public var point_46:Button;
        public var point_49:Button;
        public var point_50:Button;
        public var point_52:Button;
        public var point_60:Sprite;
        public var point_48:Sprite;
        public var point_57:Sprite;
        public var point_54:Sprite;
        public var point_51:Sprite;

        public function Map_world_4Base()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            bg = new Sprite();
            bg.width = 811;
            bg.height = 521;
            this.addQuiackChild(bg);
            bg.name= 'bg';
            texture =assetMgr.getTexture('ui_ditudi');
            image = new Image(texture);
            image.width = 803;
            image.height = 505;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 123;
            image.y = 442;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 174;
            image.y = 441;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 165;
            image.y = 433;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree12');
            image = new Image(texture);
            image.x = 394;
            image.y = 20;
            image.width = 43;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 425;
            image.y = 17;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain2');
            image = new Image(texture);
            image.x = 5;
            image.y = 412;
            image.width = 134;
            image.height = 91;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 462;
            image.y = 9;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 233;
            image.y = -5;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 332;
            image.y = 66;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 133;
            image.y = 4;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 401;
            image.y = 41;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree12');
            image = new Image(texture);
            image.x = 5;
            image.y = 280;
            image.width = 43;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 508;
            image.y = 119;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 538;
            image.y = 112;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 596;
            image.y = 57;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 566;
            image.y = 14;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 541;
            image.y = 6;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 509;
            image.y = 1;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 485;
            image.y = 1;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_city3');
            image = new Image(texture);
            image.x = 414;
            image.y = 3;
            image.width = 225;
            image.height = 143;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 401;
            image.y = 71;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 422;
            image.y = 92;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 745;
            image.y = 153;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 619;
            image.y = 178;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 356;
            image.y = 125;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 338;
            image.y = 187;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 394;
            image.y = 177;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 300;
            image.y = 231;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree10');
            image = new Image(texture);
            image.x = 208;
            image.y = 115;
            image.width = 177;
            image.height = 131;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 288;
            image.y = 228;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 380;
            image.y = 295;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 328;
            image.y = 201;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 605;
            image.y = 20;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 642;
            image.y = 5;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 11;
            image.y = 393;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 526;
            image.y = 142;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 141;
            image.y = 451;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 404;
            image.y = 437;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 258;
            image.y = 428;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 309;
            image.y = 442;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 811;
            image.y = 371;
            image.width = 184;
            image.height = 134;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house4');
            image = new Image(texture);
            image.x = 685;
            image.y = 305;
            image.width = 115;
            image.height = 76;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 395;
            image.y = 234;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 481;
            image.y = 425;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 682;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 576;
            image.y = 419;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 475;
            image.y = 442;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 356;
            image.y = 447;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 606;
            image.y = 442;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 535;
            image.y = 442;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.y = 69;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 9;
            image.y = 114;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.y = 167;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree12');
            image = new Image(texture);
            image.x = 22;
            image.y = 289;
            image.width = 43;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 15;
            image.y = 302;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house2');
            image = new Image(texture);
            image.x = 3;
            image.y = 322;
            image.width = 87;
            image.height = 77;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_biaotilan01');
            image = new Image(texture);
            image.x = 188;
            image.y = 17;
            image.width = 247;
            image.height = 61;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 40;
            image.y = 32;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 114;
            image.y = 50;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 127;
            image.y = 62;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 25;
            image.y = 26;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 209;
            image.y = 219;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 159;
            image.y = 264;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 335;
            image.y = 353;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 587;
            image.y = 210;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 237;
            image.y = 344;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 582;
            image.y = 268;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 587;
            image.y = 287;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 267;
            image.y = 325;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 501;
            image.y = 373;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 410;
            image.y = 421;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 445;
            image.y = 422;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 520;
            image.y = 374;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 597;
            image.y = 307;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 593;
            image.y = 191;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 606;
            image.y = 177;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 596;
            image.y = 402;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 616;
            image.y = 396;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 665;
            image.y = 153;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 704;
            image.y = 138;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 59;
            image.y = 35;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 132;
            image.y = 78;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 116;
            image.y = 125;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 113;
            image.y = 143;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 118;
            image.y = 162;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 216;
            image.y = 234;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 140;
            image.y = 266;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 94;
            image.y = 307;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 92;
            image.y = 324;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 97;
            image.y = 342;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 196;
            image.y = 405;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 178;
            image.y = 408;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 207;
            image.y = 391;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 321;
            image.y = 342;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 427;
            image.y = 425;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 485;
            image.y = 382;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 577;
            image.y = 399;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 249;
            image.y = 331;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 79;
            image.y = 28;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 119;
            image.y = 93;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 198;
            image.y = 268;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 104;
            image.y = 274;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 213;
            image.y = 359;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 286;
            image.y = 318;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 457;
            image.y = 394;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 538;
            image.y = 376;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 570;
            image.y = 230;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 623;
            image.y = 152;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 687;
            image.y = 150;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 217;
            image.y = 252;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 179;
            image.y = 270;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('yanse_zi');
            image = new Image(texture);
            image.width = 803;
            image.height = 505;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            pointname = new TextField(246,39,'','',32,0x000000,false);
            pointname.touchable = false;
            pointname.hAlign= 'center';
            pointname.text= '';
            pointname.x = 188;
            pointname.y = 23;
            this.addQuiackChild(pointname);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_53 = new Button(texture);
            point_53.name= 'point_53';
            point_53.x = 281;
            point_53.y = 313;
            point_53.width = 41;
            point_53.height = 41;
            this.addQuiackChild(point_53);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_58 = new Button(texture);
            point_58.name= 'point_58';
            point_58.x = 565;
            point_58.y = 225;
            point_58.width = 41;
            point_58.height = 41;
            this.addQuiackChild(point_58);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_59 = new Button(texture);
            point_59.name= 'point_59';
            point_59.x = 618;
            point_59.y = 147;
            point_59.width = 41;
            point_59.height = 41;
            this.addQuiackChild(point_59);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_56 = new Button(texture);
            point_56.name= 'point_56';
            point_56.x = 533;
            point_56.y = 371;
            point_56.width = 41;
            point_56.height = 41;
            this.addQuiackChild(point_56);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_55 = new Button(texture);
            point_55.name= 'point_55';
            point_55.x = 452;
            point_55.y = 389;
            point_55.width = 41;
            point_55.height = 41;
            this.addQuiackChild(point_55);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_47 = new Button(texture);
            point_47.name= 'point_47';
            point_47.x = 114;
            point_47.y = 88;
            point_47.width = 41;
            point_47.height = 41;
            this.addQuiackChild(point_47);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_46 = new Button(texture);
            point_46.name= 'point_46';
            point_46.x = 74;
            point_46.y = 23;
            point_46.width = 41;
            point_46.height = 41;
            this.addQuiackChild(point_46);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_49 = new Button(texture);
            point_49.name= 'point_49';
            point_49.x = 193;
            point_49.y = 263;
            point_49.width = 41;
            point_49.height = 41;
            this.addQuiackChild(point_49);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_50 = new Button(texture);
            point_50.name= 'point_50';
            point_50.x = 99;
            point_50.y = 269;
            point_50.width = 41;
            point_50.height = 41;
            this.addQuiackChild(point_50);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_52 = new Button(texture);
            point_52.name= 'point_52';
            point_52.x = 208;
            point_52.y = 354;
            point_52.width = 41;
            point_52.height = 41;
            this.addQuiackChild(point_52);
            point_60 = new Sprite();
            point_60.x = 674;
            point_60.y = 47;
            point_60.width = 87;
            point_60.height = 104;
            this.addQuiackChild(point_60);
            point_60.name= 'point_60';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_60.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_60.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_03');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_60.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_60.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_60.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_60.addQuiackChild(image);
            image.touchable = false;
            point_48 = new Sprite();
            point_48.x = 125;
            point_48.y = 145;
            point_48.width = 87;
            point_48.height = 104;
            this.addQuiackChild(point_48);
            point_48.name= 'point_48';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_48.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_48.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_48.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_48.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_48.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_48.addQuiackChild(image);
            image.touchable = false;
            point_57 = new Sprite();
            point_57.x = 601;
            point_57.y = 304;
            point_57.width = 87;
            point_57.height = 104;
            this.addQuiackChild(point_57);
            point_57.name= 'point_57';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_57.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_57.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_57.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_57.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_57.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_57.addQuiackChild(image);
            image.touchable = false;
            point_54 = new Sprite();
            point_54.x = 340;
            point_54.y = 343;
            point_54.width = 87;
            point_54.height = 104;
            this.addQuiackChild(point_54);
            point_54.name= 'point_54';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_54.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_54.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_54.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_54.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_54.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_54.addQuiackChild(image);
            image.touchable = false;
            point_51 = new Sprite();
            point_51.x = 90;
            point_51.y = 348;
            point_51.width = 87;
            point_51.height = 104;
            this.addQuiackChild(point_51);
            point_51.name= 'point_51';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_51.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_51.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_51.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_51.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_51.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_51.addQuiackChild(image);
            image.touchable = false;
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            bg.dispose();
            point_53.dispose();
            point_58.dispose();
            point_59.dispose();
            point_56.dispose();
            point_55.dispose();
            point_47.dispose();
            point_46.dispose();
            point_49.dispose();
            point_50.dispose();
            point_52.dispose();
            point_60.dispose();
            point_48.dispose();
            point_57.dispose();
            point_54.dispose();
            point_51.dispose();
            super.dispose();
        
}
    }
}
