package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import com.view.View;

    public class Map_world_3Base extends View
    {
        public var bg:Sprite;
        public var point_40:Button;
        public var point_38:Button;
        public var point_37:Button;
        public var point_35:Button;
        public var point_34:Button;
        public var point_32:Button;
        public var point_31:Button;
        public var point_44:Button;
        public var point_43:Button;
        public var point_41:Button;
        public var point_45:Sprite;
        public var point_33:Sprite;
        public var point_36:Sprite;
        public var point_39:Sprite;
        public var point_42:Sprite;
        public var pointname:TextField;

        public function Map_world_3Base()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            bg = new Sprite();
            bg.width = 811;
            bg.height = 511;
            this.addQuiackChild(bg);
            bg.name= 'bg';
            texture =assetMgr.getTexture('ui_ditudi');
            image = new Image(texture);
            image.width = 803;
            image.height = 505;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 231;
            image.y = 179;
            image.width = 136;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 302;
            image.y = 193;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_city1');
            image = new Image(texture);
            image.x = 483;
            image.y = 163;
            image.width = 80;
            image.height = 66;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 383;
            image.y = 182;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 440;
            image.y = 205;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 21;
            image.y = 387;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.y = 408;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 223;
            image.y = 433;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_rift1');
            image = new Image(texture);
            image.x = 303;
            image.y = 399;
            image.width = 257;
            image.height = 100;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert7');
            image = new Image(texture);
            image.x = 283;
            image.y = 438;
            image.width = 62;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 16;
            image.y = 444;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 468;
            image.y = 250;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 500;
            image.y = 241;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 517;
            image.y = 205;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 480;
            image.y = 426;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 492;
            image.y = 255;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 492;
            image.y = 281;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 440;
            image.y = 253;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 462;
            image.y = 270;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 420;
            image.y = 241;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 394;
            image.y = 258;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 420;
            image.y = 273;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 362;
            image.y = 248;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 336;
            image.y = 248;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_rift2');
            image = new Image(texture);
            image.x = 184;
            image.y = 196;
            image.width = 194;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert7');
            image = new Image(texture);
            image.x = 266;
            image.y = 221;
            image.width = 62;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert7');
            image = new Image(texture);
            image.x = 165;
            image.y = 203;
            image.width = 62;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert7');
            image = new Image(texture);
            image.x = 172;
            image.y = 258;
            image.width = 62;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain9');
            image = new Image(texture);
            image.x = 393;
            image.y = 246;
            image.width = 35;
            image.height = 28;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.y = 175;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 32;
            image.y = 279;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 7;
            image.y = 323;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 122;
            image.y = 262;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 11;
            image.y = 39;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 470;
            image.y = 15;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 551;
            image.y = 2;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 14;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 85;
            image.y = 10;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 166;
            image.y = -5;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 454;
            image.y = 172;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 492;
            image.y = 137;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 386;
            image.y = 103;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 365;
            image.y = 182;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 637;
            image.y = 6;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 686;
            image.y = 20;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 227;
            image.y = 1;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 299;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 369;
            image.y = 33;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 429;
            image.y = 1;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 660;
            image.y = 432;
            image.width = 136;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 605;
            image.y = 26;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 527;
            image.y = 261;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 637;
            image.y = 47;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 713;
            image.y = 65;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 646;
            image.y = 94;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 801;
            image.y = 113;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 804;
            image.y = 231;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 665;
            image.y = 178;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 695;
            image.y = 318;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 596;
            image.y = 435;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 188;
            image.y = 36;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 104;
            image.y = 103;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 187;
            image.y = 163;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 206;
            image.y = 163;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 21;
            image.y = 134;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 59;
            image.y = 136;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 231;
            image.y = 321;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 286;
            image.y = 372;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 272;
            image.y = 360;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 301;
            image.y = 379;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 426;
            image.y = 361;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 442;
            image.y = 354;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 515;
            image.y = 353;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 194;
            image.y = 318;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 531;
            image.y = 364;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 594;
            image.y = 408;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 684;
            image.y = 306;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 692;
            image.y = 320;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 613;
            image.y = 406;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 517;
            image.y = 123;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 497;
            image.y = 124;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 327;
            image.y = 125;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 431;
            image.y = 149;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 630;
            image.y = 149;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 641;
            image.y = 165;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 347;
            image.y = 127;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 412;
            image.y = 154;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 620;
            image.y = 262;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 620;
            image.y = 244;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 141;
            image.y = 103;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 214;
            image.y = 315;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 171;
            image.y = 153;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 309;
            image.y = 131;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 395;
            image.y = 151;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 479;
            image.y = 129;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 122;
            image.y = 99;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 39;
            image.y = 140;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 641;
            image.y = 186;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 631;
            image.y = 275;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 692;
            image.y = 338;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 575;
            image.y = 402;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 497;
            image.y = 348;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 413;
            image.y = 372;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 150;
            image.y = 370;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 150;
            image.y = 353;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 155;
            image.y = 385;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_biaotilan01');
            image = new Image(texture);
            image.x = 278;
            image.y = 17;
            image.width = 247;
            image.height = 61;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 147;
            image.y = 117;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 71;
            image.y = 110;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 157;
            image.y = 321;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 240;
            image.y = 332;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 459;
            image.y = 339;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 540;
            image.y = 375;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 645;
            image.y = 280;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 359;
            image.y = 131;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 445;
            image.y = 129;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 622;
            image.y = 206;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('yanse_lan');
            image = new Image(texture);
            image.width = 803;
            image.height = 505;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_40 = new Button(texture);
            point_40.name= 'point_40';
            point_40.x = 535;
            point_40.y = 370;
            point_40.width = 41;
            point_40.height = 41;
            this.addQuiackChild(point_40);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_38 = new Button(texture);
            point_38.name= 'point_38';
            point_38.x = 640;
            point_38.y = 275;
            point_38.width = 41;
            point_38.height = 41;
            this.addQuiackChild(point_38);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_37 = new Button(texture);
            point_37.name= 'point_37';
            point_37.x = 617;
            point_37.y = 201;
            point_37.width = 41;
            point_37.height = 41;
            this.addQuiackChild(point_37);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_35 = new Button(texture);
            point_35.name= 'point_35';
            point_35.x = 440;
            point_35.y = 124;
            point_35.width = 41;
            point_35.height = 41;
            this.addQuiackChild(point_35);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_34 = new Button(texture);
            point_34.name= 'point_34';
            point_34.x = 354;
            point_34.y = 126;
            point_34.width = 41;
            point_34.height = 41;
            this.addQuiackChild(point_34);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_32 = new Button(texture);
            point_32.name= 'point_32';
            point_32.x = 142;
            point_32.y = 112;
            point_32.width = 41;
            point_32.height = 41;
            this.addQuiackChild(point_32);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_31 = new Button(texture);
            point_31.name= 'point_31';
            point_31.x = 66;
            point_31.y = 105;
            point_31.width = 41;
            point_31.height = 41;
            this.addQuiackChild(point_31);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_44 = new Button(texture);
            point_44.name= 'point_44';
            point_44.x = 152;
            point_44.y = 316;
            point_44.width = 41;
            point_44.height = 41;
            this.addQuiackChild(point_44);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_43 = new Button(texture);
            point_43.name= 'point_43';
            point_43.x = 235;
            point_43.y = 327;
            point_43.width = 41;
            point_43.height = 41;
            this.addQuiackChild(point_43);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_41 = new Button(texture);
            point_41.name= 'point_41';
            point_41.x = 454;
            point_41.y = 334;
            point_41.width = 41;
            point_41.height = 41;
            this.addQuiackChild(point_41);
            point_45 = new Sprite();
            point_45.x = 123;
            point_45.y = 399;
            point_45.width = 87;
            point_45.height = 104;
            this.addQuiackChild(point_45);
            point_45.name= 'point_45';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_45.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_45.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_03');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_45.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_45.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_45.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_45.addQuiackChild(image);
            image.touchable = false;
            point_33 = new Sprite();
            point_33.x = 222;
            point_33.y = 104;
            point_33.width = 87;
            point_33.height = 104;
            this.addQuiackChild(point_33);
            point_33.name= 'point_33';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_33.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_33.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_33.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_33.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_33.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_33.addQuiackChild(image);
            image.touchable = false;
            point_36 = new Sprite();
            point_36.x = 536;
            point_36.y = 88;
            point_36.width = 87;
            point_36.height = 104;
            this.addQuiackChild(point_36);
            point_36.name= 'point_36';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_36.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_36.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_36.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_36.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_36.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_36.addQuiackChild(image);
            image.touchable = false;
            point_39 = new Sprite();
            point_39.x = 627;
            point_39.y = 344;
            point_39.width = 87;
            point_39.height = 104;
            this.addQuiackChild(point_39);
            point_39.name= 'point_39';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_39.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_39.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_39.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_39.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_39.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_39.addQuiackChild(image);
            image.touchable = false;
            point_42 = new Sprite();
            point_42.x = 320;
            point_42.y = 338;
            point_42.width = 87;
            point_42.height = 104;
            this.addQuiackChild(point_42);
            point_42.name= 'point_42';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_42.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_42.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_42.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_42.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_42.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_42.addQuiackChild(image);
            image.touchable = false;
            pointname = new TextField(246,39,'','',32,0x000000,false);
            pointname.touchable = false;
            pointname.hAlign= 'center';
            pointname.text= '';
            pointname.x = 279;
            pointname.y = 24;
            this.addQuiackChild(pointname);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            bg.dispose();
            point_40.dispose();
            point_38.dispose();
            point_37.dispose();
            point_35.dispose();
            point_34.dispose();
            point_32.dispose();
            point_31.dispose();
            point_44.dispose();
            point_43.dispose();
            point_41.dispose();
            point_45.dispose();
            point_33.dispose();
            point_36.dispose();
            point_39.dispose();
            point_42.dispose();
            super.dispose();
        
}
    }
}
