package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import com.view.View;

    public class Map_world_15Base extends View
    {
        public var bg:Sprite;
        public var point_220:Button;
        public var point_224:Button;
        public var point_223:Button;
        public var point_215:Button;
        public var point_212:Button;
        public var point_211:Button;
        public var point_214:Button;
        public var point_217:Button;
        public var point_218:Button;
        public var point_221:Button;
        public var point_213:Sprite;
        public var point_222:Sprite;
        public var point_219:Sprite;
        public var point_216:Sprite;
        public var point_228:Sprite;
        public var point_225:Sprite;
        public var point_227:Button;
        public var point_226:Button;
        public var pointname:TextField;

        public function Map_world_15Base()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            bg = new Sprite();
            bg.width = 804;
            bg.height = 521;
            this.addQuiackChild(bg);
            bg.name= 'bg';
            texture =assetMgr.getTexture('ui_ditudi');
            image = new Image(texture);
            image.width = 803;
            image.height = 505;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 3;
            image.y = 54;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 111;
            image.y = 365;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree5');
            image = new Image(texture);
            image.x = 297;
            image.y = 272;
            image.width = 86;
            image.height = 43;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree1');
            image = new Image(texture);
            image.x = 434;
            image.y = -5;
            image.width = 237;
            image.height = 155;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 599;
            image.y = 292;
            image.width = 17;
            image.height = 18;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 55;
            image.y = 438;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 522;
            image.y = 61;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_city2');
            image = new Image(texture);
            image.x = 147;
            image.y = 6;
            image.width = 142;
            image.height = 106;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_rift2');
            image = new Image(texture);
            image.x = 307;
            image.y = 302;
            image.width = 194;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 555;
            image.y = 127;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_lake2');
            image = new Image(texture);
            image.x = 346;
            image.y = 148;
            image.width = 130;
            image.height = 126;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_boat');
            image = new Image(texture);
            image.x = 412;
            image.y = 147;
            image.width = 49;
            image.height = 43;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree4');
            image = new Image(texture);
            image.x = 330;
            image.y = 231;
            image.width = 82;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 395;
            image.y = 374;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 305;
            image.y = 341;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 342;
            image.y = 366;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 533;
            image.y = 159;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 518;
            image.y = 211;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.y = 318;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 633;
            image.y = 389;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 351;
            image.y = 268;
            image.width = 17;
            image.height = 18;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 337;
            image.y = 230;
            image.width = 17;
            image.height = 18;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 421;
            image.y = 238;
            image.width = 17;
            image.height = 18;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 374;
            image.y = 245;
            image.width = 17;
            image.height = 18;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 385;
            image.y = 236;
            image.width = 17;
            image.height = 18;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 516;
            image.y = 397;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 108;
            image.y = 137;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_dong');
            image = new Image(texture);
            image.x = 5;
            image.y = 220;
            image.width = 57;
            image.height = 60;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 577;
            image.y = 402;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 804;
            image.y = 318;
            image.width = 116;
            image.height = 114;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 681;
            image.y = 385;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 139;
            image.y = 64;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 178;
            image.y = 137;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 284;
            image.y = 397;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 697;
            image.y = 268;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_city1');
            image = new Image(texture);
            image.x = 173;
            image.y = 225;
            image.width = 80;
            image.height = 66;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_biaotilan01');
            image = new Image(texture);
            image.x = 314;
            image.y = 419;
            image.width = 247;
            image.height = 61;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 262;
            image.y = 282;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 232;
            image.y = 331;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 274;
            image.y = 263;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 359;
            image.y = 86;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 381;
            image.y = 57;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 369;
            image.y = 70;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 421;
            image.y = 69;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 431;
            image.y = 85;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 466;
            image.y = 293;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 467;
            image.y = 314;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 491;
            image.y = 364;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 512;
            image.y = 377;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 618;
            image.y = 379;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 600;
            image.y = 385;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 576;
            image.y = 387;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 501;
            image.y = 181;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 490;
            image.y = 136;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 499;
            image.y = 156;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 312;
            image.y = 191;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 305;
            image.y = 210;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 691;
            image.y = 261;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 703;
            image.y = 209;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 732;
            image.y = 128;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 447;
            image.y = 99;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 687;
            image.y = 279;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 733;
            image.y = 146;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 708;
            image.y = 192;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 224;
            image.y = 352;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 141;
            image.y = 391;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 157;
            image.y = 401;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 102;
            image.y = 326;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 109;
            image.y = 343;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 103;
            image.y = 258;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 99;
            image.y = 273;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 67;
            image.y = 24;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 47;
            image.y = 17;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 26;
            image.y = 17;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 119;
            image.y = 78;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 108;
            image.y = 62;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 130;
            image.y = 151;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 131;
            image.y = 132;
            image.width = 10;
            image.height = 10;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 279;
            image.y = 227;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 233;
            image.y = 296;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 111;
            image.y = 356;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 86;
            image.y = 289;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 117;
            image.y = 96;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 81;
            image.y = 31;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 395;
            image.y = 37;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 458;
            image.y = 108;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 461;
            image.y = 333;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 534;
            image.y = 374;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 688;
            image.y = 224;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ditu_guankajiediandi');
            image = new Image(texture);
            image.x = 714;
            image.y = 162;
            image.width = 31;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture =assetMgr.getTexture('yanse_hong');
            image = new Image(texture);
            image.width = 803;
            image.height = 505;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            bg.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_220 = new Button(texture);
            point_220.name= 'point_220';
            point_220.x = 390;
            point_220.y = 32;
            point_220.width = 41;
            point_220.height = 41;
            this.addQuiackChild(point_220);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_224 = new Button(texture);
            point_224.name= 'point_224';
            point_224.x = 529;
            point_224.y = 369;
            point_224.width = 41;
            point_224.height = 41;
            this.addQuiackChild(point_224);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_223 = new Button(texture);
            point_223.name= 'point_223';
            point_223.x = 456;
            point_223.y = 328;
            point_223.width = 41;
            point_223.height = 41;
            this.addQuiackChild(point_223);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_215 = new Button(texture);
            point_215.name= 'point_215';
            point_215.x = 106;
            point_215.y = 351;
            point_215.width = 41;
            point_215.height = 41;
            this.addQuiackChild(point_215);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_212 = new Button(texture);
            point_212.name= 'point_212';
            point_212.x = 112;
            point_212.y = 91;
            point_212.width = 41;
            point_212.height = 41;
            this.addQuiackChild(point_212);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_211 = new Button(texture);
            point_211.name= 'point_211';
            point_211.x = 76;
            point_211.y = 26;
            point_211.width = 41;
            point_211.height = 41;
            this.addQuiackChild(point_211);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_214 = new Button(texture);
            point_214.name= 'point_214';
            point_214.x = 81;
            point_214.y = 284;
            point_214.width = 41;
            point_214.height = 41;
            this.addQuiackChild(point_214);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_217 = new Button(texture);
            point_217.name= 'point_217';
            point_217.x = 228;
            point_217.y = 291;
            point_217.width = 41;
            point_217.height = 41;
            this.addQuiackChild(point_217);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_218 = new Button(texture);
            point_218.name= 'point_218';
            point_218.x = 274;
            point_218.y = 222;
            point_218.width = 41;
            point_218.height = 41;
            this.addQuiackChild(point_218);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_221 = new Button(texture);
            point_221.name= 'point_221';
            point_221.x = 453;
            point_221.y = 103;
            point_221.width = 41;
            point_221.height = 41;
            this.addQuiackChild(point_221);
            point_213 = new Sprite();
            point_213.x = 86;
            point_213.y = 165;
            point_213.width = 87;
            point_213.height = 104;
            this.addQuiackChild(point_213);
            point_213.name= 'point_213';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_213.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_213.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_213.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_213.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_213.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_213.addQuiackChild(image);
            image.touchable = false;
            point_222 = new Sprite();
            point_222.x = 458;
            point_222.y = 194;
            point_222.width = 87;
            point_222.height = 104;
            this.addQuiackChild(point_222);
            point_222.name= 'point_222';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_222.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_222.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_222.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_222.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_222.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_222.addQuiackChild(image);
            image.touchable = false;
            point_219 = new Sprite();
            point_219.x = 298;
            point_219.y = 92;
            point_219.width = 87;
            point_219.height = 104;
            this.addQuiackChild(point_219);
            point_219.name= 'point_219';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_219.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_219.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_219.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_219.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_219.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_219.addQuiackChild(image);
            image.touchable = false;
            point_216 = new Sprite();
            point_216.x = 177;
            point_216.y = 365;
            point_216.width = 87;
            point_216.height = 104;
            this.addQuiackChild(point_216);
            point_216.name= 'point_216';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_216.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_216.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_216.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_216.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_216.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_216.addQuiackChild(image);
            image.touchable = false;
            point_228 = new Sprite();
            point_228.x = 674;
            point_228.y = 27;
            point_228.width = 87;
            point_228.height = 104;
            this.addQuiackChild(point_228);
            point_228.name= 'point_228';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_228.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_228.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_03');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_228.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_228.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_228.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_228.addQuiackChild(image);
            image.touchable = false;
            point_225 = new Sprite();
            point_225.x = 620;
            point_225.y = 285;
            point_225.width = 87;
            point_225.height = 104;
            this.addQuiackChild(point_225);
            point_225.name= 'point_225';
            texture =assetMgr.getTexture('ui_touxiangdi02_01');
            image = new Image(texture);
            image.x = -1;
            image.y = -2;
            image.width = 86;
            image.height = 84;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            point_225.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_101')
            image = new Image(texture);
            image.name= 'head';
            image.x = 11;
            image.y = 7;
            image.width = 67;
            image.height = 67;
            point_225.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_touxiangdi02_02');
            button = new Button(texture);
            button.name= 'headBtn';
            button.width = 86;
            button.height = 84;
            point_225.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_1';
            image.x = 30;
            image.y = 76;
            image.width = 25;
            image.height = 26;
            point_225.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_2';
            image.x = 59;
            image.y = 64;
            image.width = 25;
            image.height = 26;
            point_225.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_xingyunxing01_tubiao')
            image = new Image(texture);
            image.name= 'star_0';
            image.x = -1;
            image.y = 65;
            image.width = 25;
            image.height = 26;
            point_225.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_227 = new Button(texture);
            point_227.name= 'point_227';
            point_227.x = 709;
            point_227.y = 157;
            point_227.width = 41;
            point_227.height = 41;
            this.addQuiackChild(point_227);
            texture = assetMgr.getTexture('ui_ditu_guankajiedian');
            point_226 = new Button(texture);
            point_226.name= 'point_226';
            point_226.x = 683;
            point_226.y = 219;
            point_226.width = 41;
            point_226.height = 41;
            this.addQuiackChild(point_226);
            pointname = new TextField(246,39,'','',32,0x000000,false);
            pointname.touchable = false;
            pointname.hAlign= 'center';
            pointname.text= '';
            pointname.x = 315;
            pointname.y = 428;
            this.addQuiackChild(pointname);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            bg.dispose();
            point_220.dispose();
            point_224.dispose();
            point_223.dispose();
            point_215.dispose();
            point_212.dispose();
            point_211.dispose();
            point_214.dispose();
            point_217.dispose();
            point_218.dispose();
            point_221.dispose();
            point_213.dispose();
            point_222.dispose();
            point_219.dispose();
            point_216.dispose();
            point_228.dispose();
            point_225.dispose();
            point_227.dispose();
            point_226.dispose();
            super.dispose();
        
}
    }
}
