package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.view.View;

    public class OverallBase extends View
    {
        public var ui_zhuangshixianquan03_jiemian151401:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian165415:Scale9Image;
        public var parBg2:Scale9Image;
        public var parBg4:Scale9Image;
        public var parBg3:Scale9Image;
        public var parBg1:Scale9Image;
        public var par_1:Scale9Image;
        public var par_2:Scale9Image;
        public var par_4:Scale9Image;
        public var par_3:Scale9Image;
        public var Progress1:TextField;
        public var Progress2:TextField;
        public var Progress4:TextField;
        public var Progress3:TextField;
        public var ProgressRate2:TextField;
        public var ProgressRate4:TextField;
        public var ProgressRate3:TextField;
        public var ProgressRate1:TextField;

        public function OverallBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_zhuangshixianquan03_jiemian');
            var ui_zhuangshixianquan03_jiemian151401Rect:Rectangle = new Rectangle(30,30,10,10);
            var ui_zhuangshixianquan03_jiemian1514019ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan03_jiemian151401Rect);
            ui_zhuangshixianquan03_jiemian151401 = new Scale9Image(ui_zhuangshixianquan03_jiemian1514019ScaleTexture);
            ui_zhuangshixianquan03_jiemian151401.x = 151;
            ui_zhuangshixianquan03_jiemian151401.y = 401;
            ui_zhuangshixianquan03_jiemian151401.width = 794;
            ui_zhuangshixianquan03_jiemian151401.height = 144;
            this.addQuiackChild(ui_zhuangshixianquan03_jiemian151401);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian165415Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian1654159ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian165415Rect);
            ui_zhuangshixianquan01_jiemian165415 = new Scale9Image(ui_zhuangshixianquan01_jiemian1654159ScaleTexture);
            ui_zhuangshixianquan01_jiemian165415.x = 165;
            ui_zhuangshixianquan01_jiemian165415.y = 415;
            ui_zhuangshixianquan01_jiemian165415.width = 766;
            ui_zhuangshixianquan01_jiemian165415.height = 116;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian165415);
            texture = assetMgr.getTexture('ui_chengjiu_01_jindutiao');
            var parBg2Rect:Rectangle = new Rectangle(62,0,4,32);
            var parBg29ScaleTexture:Scale9Textures = new Scale9Textures(texture,parBg2Rect);
            parBg2 = new Scale9Image(parBg29ScaleTexture);
            parBg2.x = 270;
            parBg2.y = 456;
            parBg2.width = 273;
            parBg2.height = 32;
            this.addQuiackChild(parBg2);
            texture = assetMgr.getTexture('ui_chengjiu_01_jindutiao');
            var parBg4Rect:Rectangle = new Rectangle(62,0,4,32);
            var parBg49ScaleTexture:Scale9Textures = new Scale9Textures(texture,parBg4Rect);
            parBg4 = new Scale9Image(parBg49ScaleTexture);
            parBg4.x = 270;
            parBg4.y = 491;
            parBg4.width = 273;
            parBg4.height = 32;
            this.addQuiackChild(parBg4);
            texture = assetMgr.getTexture('ui_chengjiu_01_jindutiao');
            var parBg3Rect:Rectangle = new Rectangle(62,0,4,32);
            var parBg39ScaleTexture:Scale9Textures = new Scale9Textures(texture,parBg3Rect);
            parBg3 = new Scale9Image(parBg39ScaleTexture);
            parBg3.x = 644;
            parBg3.y = 456;
            parBg3.width = 273;
            parBg3.height = 32;
            this.addQuiackChild(parBg3);
            texture = assetMgr.getTexture('ui_chengjiu_01_jindutiao');
            var parBg1Rect:Rectangle = new Rectangle(62,0,4,32);
            var parBg19ScaleTexture:Scale9Textures = new Scale9Textures(texture,parBg1Rect);
            parBg1 = new Scale9Image(parBg19ScaleTexture);
            parBg1.x = 270;
            parBg1.y = 422;
            parBg1.width = 646;
            parBg1.height = 32;
            this.addQuiackChild(parBg1);
            texture = assetMgr.getTexture('ui_chengjiu_02_jindutiao');
            var par_1Rect:Rectangle = new Rectangle(32,8,64,16);
            var par_19ScaleTexture:Scale9Textures = new Scale9Textures(texture,par_1Rect);
            par_1 = new Scale9Image(par_19ScaleTexture);
            par_1.x = 270;
            par_1.y = 422;
            par_1.width = 646;
            par_1.height = 32;
            this.addQuiackChild(par_1);
            texture = assetMgr.getTexture('ui_chengjiu_02_jindutiao');
            var par_2Rect:Rectangle = new Rectangle(32,8,64,16);
            var par_29ScaleTexture:Scale9Textures = new Scale9Textures(texture,par_2Rect);
            par_2 = new Scale9Image(par_29ScaleTexture);
            par_2.x = 270;
            par_2.y = 456;
            par_2.width = 273;
            par_2.height = 32;
            this.addQuiackChild(par_2);
            texture = assetMgr.getTexture('ui_chengjiu_02_jindutiao');
            var par_4Rect:Rectangle = new Rectangle(32,8,64,16);
            var par_49ScaleTexture:Scale9Textures = new Scale9Textures(texture,par_4Rect);
            par_4 = new Scale9Image(par_49ScaleTexture);
            par_4.x = 270;
            par_4.y = 491;
            par_4.width = 273;
            par_4.height = 32;
            this.addQuiackChild(par_4);
            texture = assetMgr.getTexture('ui_chengjiu_02_jindutiao');
            var par_3Rect:Rectangle = new Rectangle(32,8,64,16);
            var par_39ScaleTexture:Scale9Textures = new Scale9Textures(texture,par_3Rect);
            par_3 = new Scale9Image(par_39ScaleTexture);
            par_3.x = 644;
            par_3.y = 456;
            par_3.width = 273;
            par_3.height = 32;
            this.addQuiackChild(par_3);
            Progress1 = new TextField(100,31,'','',24,0xFFFFFF,false);
            Progress1.touchable = false;
            Progress1.hAlign= 'center';
            Progress1.text= ' ';
            Progress1.x = 173;
            Progress1.y = 421;
            this.addQuiackChild(Progress1);
            Progress2 = new TextField(100,31,'','',24,0xFFFFFF,false);
            Progress2.touchable = false;
            Progress2.hAlign= 'center';
            Progress2.text= ' ';
            Progress2.x = 173;
            Progress2.y = 456;
            this.addQuiackChild(Progress2);
            Progress4 = new TextField(100,31,'','',24,0xFFFFFF,false);
            Progress4.touchable = false;
            Progress4.hAlign= 'center';
            Progress4.text= '';
            Progress4.x = 173;
            Progress4.y = 491;
            this.addQuiackChild(Progress4);
            Progress3 = new TextField(100,31,'','',24,0xFFFFFF,false);
            Progress3.touchable = false;
            Progress3.hAlign= 'center';
            Progress3.text= '';
            Progress3.x = 548;
            Progress3.y = 456;
            this.addQuiackChild(Progress3);
            ProgressRate2 = new TextField(170,28,'','',21,0xFFFFFF,false);
            ProgressRate2.touchable = false;
            ProgressRate2.hAlign= 'center';
            ProgressRate2.text= '';
            ProgressRate2.x = 321;
            ProgressRate2.y = 457;
            this.addQuiackChild(ProgressRate2);
            ProgressRate4 = new TextField(170,28,'','',21,0xFFFFFF,false);
            ProgressRate4.touchable = false;
            ProgressRate4.hAlign= 'center';
            ProgressRate4.text= '';
            ProgressRate4.x = 321;
            ProgressRate4.y = 492;
            this.addQuiackChild(ProgressRate4);
            ProgressRate3 = new TextField(170,28,'','',21,0xFFFFFF,false);
            ProgressRate3.touchable = false;
            ProgressRate3.hAlign= 'center';
            ProgressRate3.text= '';
            ProgressRate3.x = 693;
            ProgressRate3.y = 457;
            this.addQuiackChild(ProgressRate3);
            ProgressRate1 = new TextField(253,28,'','',21,0xFFFFFF,false);
            ProgressRate1.touchable = false;
            ProgressRate1.hAlign= 'center';
            ProgressRate1.text= '';
            ProgressRate1.x = 430;
            ProgressRate1.y = 423;
            this.addQuiackChild(ProgressRate1);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
    }
}
