package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import com.components.TabButton;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.dialog.TabDialog;

    public class PackDlgBase extends TabDialog
    {
        public var ui_tanchukuangdi01_jiemian11914:Scale9Image;
        public var tab_1:TabButton;
        public var tab_2:TabButton;
        public var tab_3:TabButton;
        public var btn_close:Button;
        public var ui_dicengying01_jiemian415492:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian161471:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian161470:Scale9Image;
        public var page1:Image;
        public var page2:Image;
        public var page5:Image;
        public var page4:Image;
        public var page3:Image;
        public var sell_Scale9Button:Scale9Button;
        public var cancel_Scale9Button:Scale9Button;
        public var ok_Scale9Button:Scale9Button;

        public function PackDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tanchukuangdi01_jiemian');
            var ui_tanchukuangdi01_jiemian11914Rect:Rectangle = new Rectangle(420,240,4,4);
            var ui_tanchukuangdi01_jiemian119149ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tanchukuangdi01_jiemian11914Rect);
            ui_tanchukuangdi01_jiemian11914 = new Scale9Image(ui_tanchukuangdi01_jiemian119149ScaleTexture);
            ui_tanchukuangdi01_jiemian11914.x = 119;
            ui_tanchukuangdi01_jiemian11914.y = 14;
            ui_tanchukuangdi01_jiemian11914.width = 856;
            ui_tanchukuangdi01_jiemian11914.height = 580;
            this.addQuiackChild(ui_tanchukuangdi01_jiemian11914);
            texture =assetMgr.getTexture('ui_taitoudi01_jiemian');
            image = new Image(texture);
            image.x = 187;
            image.y = 10;
            image.width = 720;
            image.height = 56;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            tab_1 = new TabButton(assetMgr.getTexture('ui_TAB02_anniu'),assetMgr.getTexture('ui_TAB01_anniu'));
            tab_1.y = 82;
            tab_1.width = 173;
            tab_1.height = 86;
            this.addQuiackChild(tab_1);
            tab_1.text= 'lable';
            tab_1.fontColor= 0xFFFFFF;
            tab_1.fontSize= 28;
            tab_2 = new TabButton(assetMgr.getTexture('ui_TAB02_anniu'),assetMgr.getTexture('ui_TAB01_anniu'));
            tab_2.y = 158;
            tab_2.width = 173;
            tab_2.height = 86;
            this.addQuiackChild(tab_2);
            tab_2.text= 'lable';
            tab_2.fontColor= 0xFFFFFF;
            tab_2.fontSize= 28;
            tab_3 = new TabButton(assetMgr.getTexture('ui_TAB02_anniu'),assetMgr.getTexture('ui_TAB01_anniu'));
            tab_3.y = 234;
            tab_3.width = 173;
            tab_3.height = 86;
            this.addQuiackChild(tab_3);
            tab_3.text= 'lable';
            tab_3.fontColor= 0xFFFFFF;
            tab_3.fontSize= 28;
            texture =assetMgr.getTexture('ui_mingzidi01');
            image = new Image(texture);
            image.x = 321;
            image.y = 20;
            image.width = 452;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_guanbi01_anniu');
            btn_close = new Button(texture);
            btn_close.name= 'btn_close';
            btn_close.x = 873;
            btn_close.width = 72;
            btn_close.height = 76;
            this.addQuiackChild(btn_close);
            texture = assetMgr.getTexture('ui_dicengying01_jiemian');
            var ui_dicengying01_jiemian415492Rect:Rectangle = new Rectangle(26,17,12,1);
            var ui_dicengying01_jiemian4154929ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_dicengying01_jiemian415492Rect);
            ui_dicengying01_jiemian415492 = new Scale9Image(ui_dicengying01_jiemian4154929ScaleTexture);
            ui_dicengying01_jiemian415492.x = 415;
            ui_dicengying01_jiemian415492.y = 492;
            ui_dicengying01_jiemian415492.width = 280;
            ui_dicengying01_jiemian415492.height = 35;
            this.addQuiackChild(ui_dicengying01_jiemian415492);
            texture =assetMgr.getTexture('ui_beibao_taitou_wenzi');
            image = new Image(texture);
            image.x = 490;
            image.y = 20;
            image.width = 115;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian161471Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian1614719ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian161471Rect);
            ui_zhuangshixianquan02_jiemian161471 = new Scale9Image(ui_zhuangshixianquan02_jiemian1614719ScaleTexture);
            ui_zhuangshixianquan02_jiemian161471.x = 161;
            ui_zhuangshixianquan02_jiemian161471.y = 471;
            ui_zhuangshixianquan02_jiemian161471.width = 772;
            ui_zhuangshixianquan02_jiemian161471.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian161471);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian161470Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian1614709ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian161470Rect);
            ui_zhuangshixianquan02_jiemian161470 = new Scale9Image(ui_zhuangshixianquan02_jiemian1614709ScaleTexture);
            ui_zhuangshixianquan02_jiemian161470.x = 161;
            ui_zhuangshixianquan02_jiemian161470.y = 470;
            ui_zhuangshixianquan02_jiemian161470.width = 772;
            ui_zhuangshixianquan02_jiemian161470.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian161470);
            texture = assetMgr.getTexture('ui_yeqian01_xianshi')
            page1 = new Image(texture);
            page1.x = 447;
            page1.y = 497;
            page1.width = 28;
            page1.height = 25;
            this.addQuiackChild(page1);
            page1.touchable = false;
            texture = assetMgr.getTexture('ui_yeqian02_xianshi')
            page2 = new Image(texture);
            page2.x = 494;
            page2.y = 497;
            page2.width = 28;
            page2.height = 25;
            this.addQuiackChild(page2);
            page2.touchable = false;
            texture = assetMgr.getTexture('ui_yeqian02_xianshi')
            page5 = new Image(texture);
            page5.x = 635;
            page5.y = 497;
            page5.width = 28;
            page5.height = 25;
            this.addQuiackChild(page5);
            page5.touchable = false;
            texture = assetMgr.getTexture('ui_yeqian02_xianshi')
            page4 = new Image(texture);
            page4.x = 588;
            page4.y = 497;
            page4.width = 28;
            page4.height = 25;
            this.addQuiackChild(page4);
            page4.touchable = false;
            texture = assetMgr.getTexture('ui_yeqian02_xianshi')
            page3 = new Image(texture);
            page3.x = 541;
            page3.y = 497;
            page3.width = 28;
            page3.height = 25;
            this.addQuiackChild(page3);
            page3.touchable = false;
            texture = assetMgr.getTexture('ui_hong02_01_anniu');
            var sell_Scale9ButtonRect:Rectangle = new Rectangle(25,10,50,20);
            sell_Scale9Button = new Scale9Button(texture,sell_Scale9ButtonRect);
            sell_Scale9Button.x = 742;
            sell_Scale9Button.y = 489;
            sell_Scale9Button.width = 150;
            sell_Scale9Button.height = 39;
            this.addQuiackChild(sell_Scale9Button);
            sell_Scale9Button.name = 'sell_Scale9Button';
            sell_Scale9Button.text= 'lable';
            sell_Scale9Button.fontColor= 0xFFFFFFB4;
            sell_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_hong02_01_anniu');
            var cancel_Scale9ButtonRect:Rectangle = new Rectangle(25,10,50,20);
            cancel_Scale9Button = new Scale9Button(texture,cancel_Scale9ButtonRect);
            cancel_Scale9Button.x = 712;
            cancel_Scale9Button.y = 489;
            cancel_Scale9Button.width = 100;
            cancel_Scale9Button.height = 39;
            this.addQuiackChild(cancel_Scale9Button);
            cancel_Scale9Button.name = 'cancel_Scale9Button';
            cancel_Scale9Button.text= 'lable';
            cancel_Scale9Button.fontColor= 0xFFFFFFB4;
            cancel_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_hong02_01_anniu');
            var ok_Scale9ButtonRect:Rectangle = new Rectangle(25,10,50,20);
            ok_Scale9Button = new Scale9Button(texture,ok_Scale9ButtonRect);
            ok_Scale9Button.x = 833;
            ok_Scale9Button.y = 489;
            ok_Scale9Button.width = 100;
            ok_Scale9Button.height = 39;
            this.addQuiackChild(ok_Scale9Button);
            ok_Scale9Button.name = 'ok_Scale9Button';
            ok_Scale9Button.text= 'lable';
            ok_Scale9Button.fontColor= 0xFFFFFFB4;
            ok_Scale9Button.fontSize= 24;
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            tab_1.dispose();
            tab_2.dispose();
            tab_3.dispose();
            btn_close.dispose();
            super.dispose();
        
}
    }
}
