package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.controls.List;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.view.View;

    public class RankViewBase extends View
    {
        public var ui_zhuangshixianquan02_jiemian157229:Scale9Image;
        public var ui_zhuangshixianquan03_jiemian43489:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian447102:Scale9Image;
        public var list_hero:List;
        public var huanBtn_Scale9Button:Scale9Button;
        public var zxBtn_Scale9Button:Scale9Button;
        public var txtName:TextField;
        public var txtNumTitle:TextField;
        public var txtNum:TextField;
        public var txtFightNumTitle:TextField;
        public var txtFightNum:TextField;

        public function RankViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian157229Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian1572299ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian157229Rect);
            ui_zhuangshixianquan02_jiemian157229 = new Scale9Image(ui_zhuangshixianquan02_jiemian1572299ScaleTexture);
            ui_zhuangshixianquan02_jiemian157229.x = 157;
            ui_zhuangshixianquan02_jiemian157229.y = 229;
            ui_zhuangshixianquan02_jiemian157229.width = 780;
            ui_zhuangshixianquan02_jiemian157229.height = 2;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian157229);
            texture = assetMgr.getTexture('ui_zhuangshixianquan03_jiemian');
            var ui_zhuangshixianquan03_jiemian43489Rect:Rectangle = new Rectangle(30,30,10,10);
            var ui_zhuangshixianquan03_jiemian434899ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan03_jiemian43489Rect);
            ui_zhuangshixianquan03_jiemian43489 = new Scale9Image(ui_zhuangshixianquan03_jiemian434899ScaleTexture);
            ui_zhuangshixianquan03_jiemian43489.x = 434;
            ui_zhuangshixianquan03_jiemian43489.y = 89;
            ui_zhuangshixianquan03_jiemian43489.width = 212;
            ui_zhuangshixianquan03_jiemian43489.height = 132;
            this.addQuiackChild(ui_zhuangshixianquan03_jiemian43489);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian447102Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian4471029ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian447102Rect);
            ui_zhuangshixianquan01_jiemian447102 = new Scale9Image(ui_zhuangshixianquan01_jiemian4471029ScaleTexture);
            ui_zhuangshixianquan01_jiemian447102.x = 447;
            ui_zhuangshixianquan01_jiemian447102.y = 102;
            ui_zhuangshixianquan01_jiemian447102.width = 186;
            ui_zhuangshixianquan01_jiemian447102.height = 106;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian447102);
            texture =assetMgr.getTexture('ui_iocn_qualifying1');
            image = new Image(texture);
            image.x = 494;
            image.y = 73;
            image.width = 85;
            image.height = 57;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            list_hero = new List();
            list_hero.x = 167;
            list_hero.y = 254;
            list_hero.width = 760;
            list_hero.height = 279;
            this.addQuiackChild(list_hero);
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var huanBtn_Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            huanBtn_Scale9Button = new Scale9Button(texture,huanBtn_Scale9ButtonRect);
            huanBtn_Scale9Button.x = 194;
            huanBtn_Scale9Button.y = 155;
            huanBtn_Scale9Button.width = 200;
            huanBtn_Scale9Button.height = 70;
            this.addQuiackChild(huanBtn_Scale9Button);
            huanBtn_Scale9Button.name = 'huanBtn_Scale9Button';
            huanBtn_Scale9Button.text= 'lable';
            huanBtn_Scale9Button.fontColor= 0xFFFFFF;
            huanBtn_Scale9Button.fontSize= 24;
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var zxBtn_Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            zxBtn_Scale9Button = new Scale9Button(texture,zxBtn_Scale9ButtonRect);
            zxBtn_Scale9Button.x = 700;
            zxBtn_Scale9Button.y = 155;
            zxBtn_Scale9Button.width = 200;
            zxBtn_Scale9Button.height = 70;
            this.addQuiackChild(zxBtn_Scale9Button);
            zxBtn_Scale9Button.name = 'zxBtn_Scale9Button';
            zxBtn_Scale9Button.text= 'lable';
            zxBtn_Scale9Button.fontColor= 0xFFFFFF;
            zxBtn_Scale9Button.fontSize= 24;
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 458;
            image.y = 108;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 621;
            image.y = 108;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 619;
            image.y = 113;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 461;
            image.y = 113;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 458;
            image.y = 202;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 621;
            image.y = 202;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 619;
            image.y = 197;
            image.width = 8;
            image.height = 33;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 461;
            image.y = 197;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txtName = new TextField(192,31,'','',24,0xFFFFFF,false);
            txtName.touchable = false;
            txtName.hAlign= 'center';
            txtName.text= '';
            txtName.x = 444;
            txtName.y = 126;
            this.addQuiackChild(txtName);
            txtNumTitle = new TextField(200,31,'','',24,0xFFFFFF,false);
            txtNumTitle.touchable = false;
            txtNumTitle.hAlign= 'center';
            txtNumTitle.text= ' ';
            txtNumTitle.x = 194;
            txtNumTitle.y = 92;
            this.addQuiackChild(txtNumTitle);
            txtNum = new TextField(200,33,'','',26,0xFF9900,false);
            txtNum.touchable = false;
            txtNum.hAlign= 'center';
            txtNum.text= '';
            txtNum.x = 194;
            txtNum.y = 121;
            this.addQuiackChild(txtNum);
            txtFightNumTitle = new TextField(200,31,'','',24,0xFFFFFF,false);
            txtFightNumTitle.touchable = false;
            txtFightNumTitle.hAlign= 'center';
            txtFightNumTitle.text= '';
            txtFightNumTitle.x = 700;
            txtFightNumTitle.y = 92;
            this.addQuiackChild(txtFightNumTitle);
            txtFightNum = new TextField(200,33,'','',26,0xFF9900,false);
            txtFightNum.touchable = false;
            txtFightNum.hAlign= 'center';
            txtFightNum.text= '';
            txtFightNum.x = 700;
            txtFightNum.y = 121;
            this.addQuiackChild(txtFightNum);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            list_hero.dispose();
            super.dispose();
        
}
    }
}
