package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.dialog.Dialog;

    public class ResignDlgBase extends Dialog
    {
        public var ui_tipstanchukuangdi01_jiemian00:Scale9Image;
        public var txt_info:TextField;
        public var ui_zhuangshixianquan02_jiemian44267:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian4474:Scale9Image;
        public var ok_Scale9Button:Scale9Button;
        public var close_Scale9Button:Scale9Button;

        public function ResignDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian00Rect:Rectangle = new Rectangle(68,64,6,6);
            var ui_tipstanchukuangdi01_jiemian009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian00Rect);
            ui_tipstanchukuangdi01_jiemian00 = new Scale9Image(ui_tipstanchukuangdi01_jiemian009ScaleTexture);
            ui_tipstanchukuangdi01_jiemian00.width = 600;
            ui_tipstanchukuangdi01_jiemian00.height = 386;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian00);
            txt_info = new TextField(512,171,'','',28,0xFFFFFF,false);
            txt_info.touchable = false;
            txt_info.hAlign= 'center';
            txt_info.text= 'lable';
            txt_info.x = 44;
            txt_info.y = 83;
            this.addQuiackChild(txt_info);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian44267Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian442679ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian44267Rect);
            ui_zhuangshixianquan02_jiemian44267 = new Scale9Image(ui_zhuangshixianquan02_jiemian442679ScaleTexture);
            ui_zhuangshixianquan02_jiemian44267.x = 44;
            ui_zhuangshixianquan02_jiemian44267.y = 267;
            ui_zhuangshixianquan02_jiemian44267.width = 512;
            ui_zhuangshixianquan02_jiemian44267.height = 2;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian44267);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian4474Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian44749ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian4474Rect);
            ui_zhuangshixianquan02_jiemian4474 = new Scale9Image(ui_zhuangshixianquan02_jiemian44749ScaleTexture);
            ui_zhuangshixianquan02_jiemian4474.x = 44;
            ui_zhuangshixianquan02_jiemian4474.y = 74;
            ui_zhuangshixianquan02_jiemian4474.width = 512;
            ui_zhuangshixianquan02_jiemian4474.height = 2;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian4474);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 50;
            image.y = 40;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 550;
            image.y = 40;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 247;
            image.y = 73;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 353;
            image.y = 73;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 548;
            image.y = 45;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 52;
            image.y = 45;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_tishi_xiaotaitou_wenzi');
            image = new Image(texture);
            image.x = 273;
            image.y = 37;
            image.width = 54;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var ok_Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            ok_Scale9Button = new Scale9Button(texture,ok_Scale9ButtonRect);
            ok_Scale9Button.x = 334;
            ok_Scale9Button.y = 280;
            ok_Scale9Button.width = 186;
            ok_Scale9Button.height = 70;
            this.addQuiackChild(ok_Scale9Button);
            ok_Scale9Button.name = 'ok_Scale9Button';
            ok_Scale9Button.text= 'lable';
            ok_Scale9Button.fontColor= 0xFFFFFF;
            ok_Scale9Button.fontSize= 28;
            texture = assetMgr.getTexture('ui_lan03_01_anniu');
            var close_Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            close_Scale9Button = new Scale9Button(texture,close_Scale9ButtonRect);
            close_Scale9Button.x = 80;
            close_Scale9Button.y = 280;
            close_Scale9Button.width = 186;
            close_Scale9Button.height = 70;
            this.addQuiackChild(close_Scale9Button);
            close_Scale9Button.name = 'close_Scale9Button';
            close_Scale9Button.text= 'lable';
            close_Scale9Button.fontColor= 0xFFFFC9;
            close_Scale9Button.fontSize= 28;
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
    }
}
