package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.view.View;

    public class RuleViewBase extends View
    {
        public var ui_zhuangshixianquan01_jiemian18291:Scale9Image;
        public var ui_zhuangshixianquan03_jiemian174385:Scale9Image;
        public var text_highestRanking:TextField;
        public var text_strongestKing:TextField;
        public var text_rankAwards:TextField;
        public var text_rankAwards_powe:TextField;
        public var text_rankAwards_diamond:TextField;
        public var text_rules:TextField;
        public var text_rules_1:TextField;
        public var text_rules_2:TextField;
        public var text_rules_title_1:TextField;
        public var text_rules_title_2:TextField;
        public var text_reward:TextField;
        public var text_reward_1:TextField;
        public var text_reward_2:TextField;
        public var text_reward_title_2:TextField;
        public var text_reward_title_1:TextField;
        public var text_reward_3:TextField;
        public var text_reward_title_3:TextField;
        public var ui_zhuangshixianquan02_jiemian192202:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian192471:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian192470:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian192203:Scale9Image;

        public function RuleViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian18291Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian182919ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian18291Rect);
            ui_zhuangshixianquan01_jiemian18291 = new Scale9Image(ui_zhuangshixianquan01_jiemian182919ScaleTexture);
            ui_zhuangshixianquan01_jiemian18291.x = 182;
            ui_zhuangshixianquan01_jiemian18291.y = 91;
            ui_zhuangshixianquan01_jiemian18291.width = 730;
            ui_zhuangshixianquan01_jiemian18291.height = 290;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian18291);
            texture = assetMgr.getTexture('ui_zhuangshixianquan03_jiemian');
            var ui_zhuangshixianquan03_jiemian174385Rect:Rectangle = new Rectangle(30,30,10,10);
            var ui_zhuangshixianquan03_jiemian1743859ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan03_jiemian174385Rect);
            ui_zhuangshixianquan03_jiemian174385 = new Scale9Image(ui_zhuangshixianquan03_jiemian1743859ScaleTexture);
            ui_zhuangshixianquan03_jiemian174385.x = 174;
            ui_zhuangshixianquan03_jiemian174385.y = 385;
            ui_zhuangshixianquan03_jiemian174385.width = 746;
            ui_zhuangshixianquan03_jiemian174385.height = 150;
            this.addQuiackChild(ui_zhuangshixianquan03_jiemian174385);
            text_highestRanking = new TextField(174,32,'','',24,0xFFFFFF,false);
            text_highestRanking.touchable = false;
            text_highestRanking.hAlign= 'left';
            text_highestRanking.text= '';
            text_highestRanking.x = 245;
            text_highestRanking.y = 418;
            this.addQuiackChild(text_highestRanking);
            text_strongestKing = new TextField(168,42,'','',28,0xFFFFFF,false);
            text_strongestKing.touchable = false;
            text_strongestKing.hAlign= 'center';
            text_strongestKing.text= '';
            text_strongestKing.x = 709;
            text_strongestKing.y = 414;
            this.addQuiackChild(text_strongestKing);
            texture =assetMgr.getTexture('ui_iocn_qualifying1');
            image = new Image(texture);
            image.x = 635;
            image.y = 406;
            image.width = 85;
            image.height = 57;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            text_rankAwards = new TextField(165,32,'','',24,0xFFFFFF,false);
            text_rankAwards.touchable = false;
            text_rankAwards.hAlign= 'left';
            text_rankAwards.text= '';
            text_rankAwards.x = 245;
            text_rankAwards.y = 481;
            this.addQuiackChild(text_rankAwards);
            texture =assetMgr.getTexture('ui_rongyuzhi_01_tubiao');
            image = new Image(texture);
            image.x = 670;
            image.y = 480;
            image.width = 27;
            image.height = 39;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            text_rankAwards_powe = new TextField(168,35,'','',28,0xFFFFFF,false);
            text_rankAwards_powe.touchable = false;
            text_rankAwards_powe.hAlign= 'left';
            text_rankAwards_powe.text= '';
            text_rankAwards_powe.x = 709;
            text_rankAwards_powe.y = 481;
            this.addQuiackChild(text_rankAwards_powe);
            text_rankAwards_diamond = new TextField(150,35,'','',28,0xFFFFFF,false);
            text_rankAwards_diamond.touchable = false;
            text_rankAwards_diamond.hAlign= 'left';
            text_rankAwards_diamond.text= '';
            text_rankAwards_diamond.x = 453;
            text_rankAwards_diamond.y = 481;
            this.addQuiackChild(text_rankAwards_diamond);
            text_rules = new TextField(134,31,'','',24,0xFFFFFF,false);
            text_rules.touchable = false;
            text_rules.hAlign= 'left';
            text_rules.text= '';
            text_rules.x = 191;
            text_rules.y = 98;
            this.addQuiackChild(text_rules);
            text_rules_1 = new TextField(682,31,'','',24,0xFFCC99,false);
            text_rules_1.touchable = false;
            text_rules_1.hAlign= 'left';
            text_rules_1.text= '';
            text_rules_1.x = 219;
            text_rules_1.y = 130;
            this.addQuiackChild(text_rules_1);
            text_rules_2 = new TextField(682,31,'','',24,0xFFCC99,false);
            text_rules_2.touchable = false;
            text_rules_2.hAlign= 'left';
            text_rules_2.text= '';
            text_rules_2.x = 219;
            text_rules_2.y = 167;
            this.addQuiackChild(text_rules_2);
            text_rules_title_1 = new TextField(26,32,'','',24,0xFFCC99,false);
            text_rules_title_1.touchable = false;
            text_rules_title_1.hAlign= 'left';
            text_rules_title_1.text= '';
            text_rules_title_1.x = 191;
            text_rules_title_1.y = 130;
            this.addQuiackChild(text_rules_title_1);
            text_rules_title_2 = new TextField(26,32,'','',24,0xFFCC99,false);
            text_rules_title_2.touchable = false;
            text_rules_title_2.hAlign= 'left';
            text_rules_title_2.text= '';
            text_rules_title_2.x = 191;
            text_rules_title_2.y = 167;
            this.addQuiackChild(text_rules_title_2);
            text_reward = new TextField(134,32,'','',24,0xFFFFFF,false);
            text_reward.touchable = false;
            text_reward.hAlign= 'left';
            text_reward.text= '';
            text_reward.x = 191;
            text_reward.y = 211;
            this.addQuiackChild(text_reward);
            text_reward_1 = new TextField(682,31,'','',24,0xFFCC99,false);
            text_reward_1.touchable = false;
            text_reward_1.hAlign= 'left';
            text_reward_1.text= '';
            text_reward_1.x = 219;
            text_reward_1.y = 246;
            this.addQuiackChild(text_reward_1);
            text_reward_2 = new TextField(682,60,'','',24,0xFFCC99,false);
            text_reward_2.touchable = false;
            text_reward_2.hAlign= 'left';
            text_reward_2.text= '';
            text_reward_2.x = 219;
            text_reward_2.y = 281;
            this.addQuiackChild(text_reward_2);
            text_reward_title_2 = new TextField(26,32,'','',24,0xFFCC99,false);
            text_reward_title_2.touchable = false;
            text_reward_title_2.hAlign= 'left';
            text_reward_title_2.text= '';
            text_reward_title_2.x = 191;
            text_reward_title_2.y = 295;
            this.addQuiackChild(text_reward_title_2);
            text_reward_title_1 = new TextField(26,32,'','',24,0xFFCC99,false);
            text_reward_title_1.touchable = false;
            text_reward_title_1.hAlign= 'left';
            text_reward_title_1.text= '';
            text_reward_title_1.x = 191;
            text_reward_title_1.y = 246;
            this.addQuiackChild(text_reward_title_1);
            text_reward_3 = new TextField(682,31,'','',24,0xFFCC99,false);
            text_reward_3.touchable = false;
            text_reward_3.hAlign= 'left';
            text_reward_3.text= '';
            text_reward_3.x = 219;
            text_reward_3.y = 343;
            this.addQuiackChild(text_reward_3);
            text_reward_title_3 = new TextField(26,32,'','',24,0xFFCC99,false);
            text_reward_title_3.touchable = false;
            text_reward_title_3.hAlign= 'left';
            text_reward_title_3.text= '';
            text_reward_title_3.x = 191;
            text_reward_title_3.y = 343;
            this.addQuiackChild(text_reward_title_3);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian192202Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian1922029ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian192202Rect);
            ui_zhuangshixianquan02_jiemian192202 = new Scale9Image(ui_zhuangshixianquan02_jiemian1922029ScaleTexture);
            ui_zhuangshixianquan02_jiemian192202.x = 192;
            ui_zhuangshixianquan02_jiemian192202.y = 202;
            ui_zhuangshixianquan02_jiemian192202.width = 710;
            ui_zhuangshixianquan02_jiemian192202.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian192202);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian192471Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian1924719ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian192471Rect);
            ui_zhuangshixianquan02_jiemian192471 = new Scale9Image(ui_zhuangshixianquan02_jiemian1924719ScaleTexture);
            ui_zhuangshixianquan02_jiemian192471.x = 192;
            ui_zhuangshixianquan02_jiemian192471.y = 471;
            ui_zhuangshixianquan02_jiemian192471.width = 710;
            ui_zhuangshixianquan02_jiemian192471.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian192471);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian192470Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian1924709ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian192470Rect);
            ui_zhuangshixianquan02_jiemian192470 = new Scale9Image(ui_zhuangshixianquan02_jiemian1924709ScaleTexture);
            ui_zhuangshixianquan02_jiemian192470.x = 192;
            ui_zhuangshixianquan02_jiemian192470.y = 470;
            ui_zhuangshixianquan02_jiemian192470.width = 710;
            ui_zhuangshixianquan02_jiemian192470.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian192470);
            texture =assetMgr.getTexture('ui_zuanshi01_tubiao');
            image = new Image(texture);
            image.x = 419;
            image.y = 483;
            image.width = 25;
            image.height = 26;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian192203Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian1922039ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian192203Rect);
            ui_zhuangshixianquan02_jiemian192203 = new Scale9Image(ui_zhuangshixianquan02_jiemian1922039ScaleTexture);
            ui_zhuangshixianquan02_jiemian192203.x = 192;
            ui_zhuangshixianquan02_jiemian192203.y = 203;
            ui_zhuangshixianquan02_jiemian192203.width = 710;
            ui_zhuangshixianquan02_jiemian192203.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian192203);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
    }
}
