package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.dialog.Dialog;

    public class SkillDesDialogBase extends Dialog
    {
        public var ui_tipstanchukuangdi01_jiemian00:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian4272:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian42135:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian42142:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian46179:Scale9Image;
        public var icon:Button;
        public var skillTypeTitle:TextField;
        public var skillType:TextField;
        public var skillDes:TextField;
        public var skilName:TextField;
        public var skillDesTitle:TextField;

        public function SkillDesDialogBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian00Rect:Rectangle = new Rectangle(68,64,6,6);
            var ui_tipstanchukuangdi01_jiemian009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian00Rect);
            ui_tipstanchukuangdi01_jiemian00 = new Scale9Image(ui_tipstanchukuangdi01_jiemian009ScaleTexture);
            ui_tipstanchukuangdi01_jiemian00.width = 440;
            ui_tipstanchukuangdi01_jiemian00.height = 346;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian00);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian4272Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian42729ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian4272Rect);
            ui_zhuangshixianquan02_jiemian4272 = new Scale9Image(ui_zhuangshixianquan02_jiemian42729ScaleTexture);
            ui_zhuangshixianquan02_jiemian4272.x = 42;
            ui_zhuangshixianquan02_jiemian4272.y = 72;
            ui_zhuangshixianquan02_jiemian4272.width = 358;
            ui_zhuangshixianquan02_jiemian4272.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian4272);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 46;
            image.y = 38;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 395;
            image.y = 38;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian42135Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian421359ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian42135Rect);
            ui_zhuangshixianquan02_jiemian42135 = new Scale9Image(ui_zhuangshixianquan02_jiemian421359ScaleTexture);
            ui_zhuangshixianquan02_jiemian42135.x = 42;
            ui_zhuangshixianquan02_jiemian42135.y = 135;
            ui_zhuangshixianquan02_jiemian42135.width = 358;
            ui_zhuangshixianquan02_jiemian42135.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian42135);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian42142Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian421429ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian42142Rect);
            ui_zhuangshixianquan01_jiemian42142 = new Scale9Image(ui_zhuangshixianquan01_jiemian421429ScaleTexture);
            ui_zhuangshixianquan01_jiemian42142.x = 42;
            ui_zhuangshixianquan01_jiemian42142.y = 142;
            ui_zhuangshixianquan01_jiemian42142.width = 358;
            ui_zhuangshixianquan01_jiemian42142.height = 156;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian42142);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian46179Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian461799ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian46179Rect);
            ui_zhuangshixianquan02_jiemian46179 = new Scale9Image(ui_zhuangshixianquan02_jiemian461799ScaleTexture);
            ui_zhuangshixianquan02_jiemian46179.x = 46;
            ui_zhuangshixianquan02_jiemian46179.y = 179;
            ui_zhuangshixianquan02_jiemian46179.width = 350;
            ui_zhuangshixianquan02_jiemian46179.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian46179);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 51;
            image.y = 145;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 391;
            image.y = 145;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 191;
            image.y = 178;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 250;
            image.y = 178;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_jinengkuangdi01');
            icon = new Button(texture);
            icon.name= 'icon';
            icon.x = 46;
            icon.y = 81;
            icon.width = 46;
            icon.height = 46;
            this.addQuiackChild(icon);
            skillTypeTitle = new TextField(109,31,'','',24,0xFFFFFF,false);
            skillTypeTitle.touchable = false;
            skillTypeTitle.hAlign= 'center';
            skillTypeTitle.text= '';
            skillTypeTitle.x = 114;
            skillTypeTitle.y = 87;
            this.addQuiackChild(skillTypeTitle);
            skillType = new TextField(166,31,'','',24,0xFF6600,false);
            skillType.touchable = false;
            skillType.hAlign= 'left';
            skillType.text= '';
            skillType.x = 224;
            skillType.y = 87;
            this.addQuiackChild(skillType);
            skillDes = new TextField(346,106,'','',24,0xFFFFFF,false);
            skillDes.touchable = false;
            skillDes.hAlign= 'center';
            skillDes.text= '';
            skillDes.x = 48;
            skillDes.y = 184;
            this.addQuiackChild(skillDes);
            skilName = new TextField(190,31,'','',24,0xFFFFFF,false);
            skilName.touchable = false;
            skilName.hAlign= 'center';
            skilName.text= '';
            skilName.x = 125;
            skilName.y = 39;
            this.addQuiackChild(skilName);
            skillDesTitle = new TextField(114,31,'','',24,0xFFFFFF,false);
            skillDesTitle.touchable = false;
            skillDesTitle.hAlign= 'center';
            skillDesTitle.text= '';
            skillDesTitle.x = 163;
            skillDesTitle.y = 146;
            this.addQuiackChild(skillDesTitle);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 393;
            image.y = 43;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 389;
            image.y = 150;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 48;
            image.y = 43;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 53;
            image.y = 150;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            icon.dispose();
            super.dispose();
        
}
    }
}
