package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.controls.List;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import game.view.blacksmith.render.EquipContainer;
    import game.view.blacksmith.render.StonePane;
    import com.view.View;

    public class StrengthenBase extends View
    {
        public var list_bag:List;
        public var ui_zhuangshixianquan03_jiemian51486:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian528100:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian532410:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian532243:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian532136:Scale9Image;
        public var bgImage0:Scale9Image;
        public var bgImage1:Scale9Image;
        public var strenthenScale9Button:Scale9Button;
        public var spend1:TextField;
        public var text_useup:TextField;
        public var coin:Image;
        public var stone2:EquipContainer;
        public var stone1:EquipContainer;
        public var stone0:EquipContainer;
        public var equip:EquipContainer;
        public var diamond:Image;
        public var spend2:TextField;
        public var nameLabel:TextField;
        public var successRatioLabel:TextField;
        public var attack:TextField;
        public var addAttack:TextField;
        public var hp:TextField;
        public var addHp:TextField;
        public var hero:TextField;
        public var heroName:TextField;
        public var stonePane:StonePane;
        public var heroTime:TextField;

        public function StrengthenBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            list_bag = new List();
            list_bag.x = 171;
            list_bag.y = 90;
            list_bag.width = 340;
            list_bag.height = 437;
            this.addQuiackChild(list_bag);
            texture = assetMgr.getTexture('ui_zhuangshixianquan03_jiemian');
            var ui_zhuangshixianquan03_jiemian51486Rect:Rectangle = new Rectangle(30,30,10,10);
            var ui_zhuangshixianquan03_jiemian514869ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan03_jiemian51486Rect);
            ui_zhuangshixianquan03_jiemian51486 = new Scale9Image(ui_zhuangshixianquan03_jiemian514869ScaleTexture);
            ui_zhuangshixianquan03_jiemian51486.x = 514;
            ui_zhuangshixianquan03_jiemian51486.y = 86;
            ui_zhuangshixianquan03_jiemian51486.width = 422;
            ui_zhuangshixianquan03_jiemian51486.height = 384;
            this.addQuiackChild(ui_zhuangshixianquan03_jiemian51486);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian528100Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian5281009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian528100Rect);
            ui_zhuangshixianquan01_jiemian528100 = new Scale9Image(ui_zhuangshixianquan01_jiemian5281009ScaleTexture);
            ui_zhuangshixianquan01_jiemian528100.x = 528;
            ui_zhuangshixianquan01_jiemian528100.y = 100;
            ui_zhuangshixianquan01_jiemian528100.width = 394;
            ui_zhuangshixianquan01_jiemian528100.height = 356;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian528100);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 537;
            image.y = 103;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 913;
            image.y = 103;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian532410Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian5324109ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian532410Rect);
            ui_zhuangshixianquan02_jiemian532410 = new Scale9Image(ui_zhuangshixianquan02_jiemian5324109ScaleTexture);
            ui_zhuangshixianquan02_jiemian532410.x = 532;
            ui_zhuangshixianquan02_jiemian532410.y = 410;
            ui_zhuangshixianquan02_jiemian532410.width = 386;
            ui_zhuangshixianquan02_jiemian532410.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian532410);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian532243Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian5322439ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian532243Rect);
            ui_zhuangshixianquan02_jiemian532243 = new Scale9Image(ui_zhuangshixianquan02_jiemian5322439ScaleTexture);
            ui_zhuangshixianquan02_jiemian532243.x = 532;
            ui_zhuangshixianquan02_jiemian532243.y = 243;
            ui_zhuangshixianquan02_jiemian532243.width = 386;
            ui_zhuangshixianquan02_jiemian532243.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian532243);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian532136Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian5321369ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian532136Rect);
            ui_zhuangshixianquan02_jiemian532136 = new Scale9Image(ui_zhuangshixianquan02_jiemian5321369ScaleTexture);
            ui_zhuangshixianquan02_jiemian532136.x = 532;
            ui_zhuangshixianquan02_jiemian532136.y = 136;
            ui_zhuangshixianquan02_jiemian532136.width = 386;
            ui_zhuangshixianquan02_jiemian532136.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian532136);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage0Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage09ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage0Rect);
            bgImage0 = new Scale9Image(bgImage09ScaleTexture);
            bgImage0.x = 699;
            bgImage0.y = 303;
            bgImage0.width = 220;
            bgImage0.height = 30;
            this.addQuiackChild(bgImage0);
            texture =assetMgr.getTexture('ui_gongji01_tubiao');
            image = new Image(texture);
            image.x = 683;
            image.y = 297;
            image.width = 38;
            image.height = 38;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage1Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage19ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage1Rect);
            bgImage1 = new Scale9Image(bgImage19ScaleTexture);
            bgImage1.x = 699;
            bgImage1.y = 340;
            bgImage1.width = 220;
            bgImage1.height = 30;
            this.addQuiackChild(bgImage1);
            texture =assetMgr.getTexture('ui_shengming01_tubiao');
            image = new Image(texture);
            image.x = 683;
            image.y = 335;
            image.width = 38;
            image.height = 38;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_qianghua_xiaotaitou_wenzi');
            image = new Image(texture);
            image.x = 698;
            image.y = 105;
            image.width = 54;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 911;
            image.y = 108;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 539;
            image.y = 108;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var strenthenScale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            strenthenScale9Button = new Scale9Button(texture,strenthenScale9ButtonRect);
            strenthenScale9Button.x = 734;
            strenthenScale9Button.y = 472;
            strenthenScale9Button.width = 186;
            strenthenScale9Button.height = 70;
            this.addQuiackChild(strenthenScale9Button);
            strenthenScale9Button.name = 'strenthenScale9Button';
            strenthenScale9Button.text= 'lable';
            strenthenScale9Button.fontColor= 0xffffff;
            strenthenScale9Button.fontSize= 24;
            spend1 = new TextField(112,31,'','',24,0xffffff,false);
            spend1.touchable = false;
            spend1.hAlign= 'left';
            spend1.text= '';
            spend1.x = 618;
            spend1.y = 472;
            this.addQuiackChild(spend1);
            text_useup = new TextField(60,36,'','',24,0xff0000,false);
            text_useup.touchable = false;
            text_useup.hAlign= 'center';
            text_useup.text= '';
            text_useup.x = 524;
            text_useup.y = 485;
            this.addQuiackChild(text_useup);
            texture = assetMgr.getTexture('ui_jinbi01_tubiao')
            coin = new Image(texture);
            coin.x = 587;
            coin.y = 475;
            coin.width = 25;
            coin.height = 26;
            this.addQuiackChild(coin);
            coin.touchable = false;
            stone2 = new EquipContainer();
            stone2.x = 803;
            stone2.y = 141;
            this.addQuiackChild(stone2);
            stone1 = new EquipContainer();
            stone1.x = 678;
            stone1.y = 141;
            this.addQuiackChild(stone1);
            stone0 = new EquipContainer();
            stone0.x = 552;
            stone0.y = 141;
            this.addQuiackChild(stone0);
            equip = new EquipContainer();
            equip.x = 552;
            equip.y = 286;
            this.addQuiackChild(equip);
            texture = assetMgr.getTexture('ui_zuanshi01_tubiao')
            diamond = new Image(texture);
            diamond.x = 587;
            diamond.y = 509;
            diamond.width = 25;
            diamond.height = 26;
            this.addQuiackChild(diamond);
            diamond.touchable = false;
            spend2 = new TextField(112,31,'','',24,0xffffff,false);
            spend2.touchable = false;
            spend2.hAlign= 'left';
            spend2.text= '';
            spend2.x = 618;
            spend2.y = 506;
            this.addQuiackChild(spend2);
            nameLabel = new TextField(162,32,'','',21,0xff00ff,false);
            nameLabel.touchable = false;
            nameLabel.hAlign= 'center';
            nameLabel.text= '';
            nameLabel.x = 649;
            nameLabel.y = 246;
            this.addQuiackChild(nameLabel);
            successRatioLabel = new TextField(179,28,'','',21,0xff9900,false);
            successRatioLabel.touchable = false;
            successRatioLabel.hAlign= 'left';
            successRatioLabel.text= '';
            successRatioLabel.x = 731;
            successRatioLabel.y = 379;
            this.addQuiackChild(successRatioLabel);
            attack = new TextField(80,26,'','',18,0xffffff,false);
            attack.touchable = false;
            attack.hAlign= 'center';
            attack.text= '';
            attack.x = 719;
            attack.y = 306;
            this.addQuiackChild(attack);
            addAttack = new TextField(112,26,'','',18,0x00ff00,false);
            addAttack.touchable = false;
            addAttack.hAlign= 'center';
            addAttack.text= '';
            addAttack.x = 803;
            addAttack.y = 306;
            this.addQuiackChild(addAttack);
            hp = new TextField(80,26,'','',18,0xffffff,false);
            hp.touchable = false;
            hp.hAlign= 'center';
            hp.text= '';
            hp.x = 719;
            hp.y = 343;
            this.addQuiackChild(hp);
            addHp = new TextField(112,26,'','',18,0x00ff00,false);
            addHp.touchable = false;
            addHp.hAlign= 'center';
            addHp.text= '';
            addHp.x = 803;
            addHp.y = 343;
            this.addQuiackChild(addHp);
            hero = new TextField(114,32,'','',21,0xffffff,false);
            hero.touchable = false;
            hero.hAlign= 'center';
            hero.text= '';
            hero.x = 533;
            hero.y = 418;
            this.addQuiackChild(hero);
            heroName = new TextField(127,32,'','',21,0xff00ff,false);
            heroName.touchable = false;
            heroName.hAlign= 'center';
            heroName.text= '';
            heroName.x = 649;
            heroName.y = 418;
            this.addQuiackChild(heroName);
            stonePane = new StonePane();
            stonePane.x = 173;
            stonePane.y = 101;
            this.addQuiackChild(stonePane);
            heroTime = new TextField(137,32,'','',21,0xff0000,false);
            heroTime.touchable = false;
            heroTime.hAlign= 'center';
            heroTime.text= '';
            heroTime.x = 779;
            heroTime.y = 418;
            this.addQuiackChild(heroTime);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            list_bag.dispose();
            stone2.dispose();
            stone1.dispose();
            stone0.dispose();
            equip.dispose();
            stonePane.dispose();
            super.dispose();
        
}
    }
}
