package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.controls.List;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.dialog.Dialog;

    public class SweepDiaBase extends Dialog
    {
        public var ui_tipstanchukuangdi01_jiemian04:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian4470:Scale9Image;
        public var ok_Scale9Button:Scale9Button;
        public var list_CarryOut:List;
        public var ui_zhuangshixianquan02_jiemian50510:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian50511:Scale9Image;

        public function SweepDiaBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian04Rect:Rectangle = new Rectangle(68,64,6,6);
            var ui_tipstanchukuangdi01_jiemian049ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian04Rect);
            ui_tipstanchukuangdi01_jiemian04 = new Scale9Image(ui_tipstanchukuangdi01_jiemian049ScaleTexture);
            ui_tipstanchukuangdi01_jiemian04.y = -4;
            ui_tipstanchukuangdi01_jiemian04.width = 600;
            ui_tipstanchukuangdi01_jiemian04.height = 618;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian04);
            texture =assetMgr.getTexture('ui_mingzidi01');
            image = new Image(texture);
            image.x = 74;
            image.y = 35;
            image.width = 452;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian4470Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian44709ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian4470Rect);
            ui_zhuangshixianquan02_jiemian4470 = new Scale9Image(ui_zhuangshixianquan02_jiemian44709ScaleTexture);
            ui_zhuangshixianquan02_jiemian4470.x = 44;
            ui_zhuangshixianquan02_jiemian4470.y = 70;
            ui_zhuangshixianquan02_jiemian4470.width = 512;
            ui_zhuangshixianquan02_jiemian4470.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian4470);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 50;
            image.y = 36;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 550;
            image.y = 36;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 247;
            image.y = 69;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 353;
            image.y = 69;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_saodang_xiaotaitou_wenzi');
            image = new Image(texture);
            image.x = 273;
            image.y = 39;
            image.width = 54;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhezhaoyinyingdi');
            image = new Image(texture);
            image.x = 30;
            image.y = 517;
            image.width = 540;
            image.height = 22;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhezhaoyinyingdi');
            image = new Image(texture);
            image.x = 30;
            image.y = 93;
            image.width = 540;
            image.height = 22;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 548;
            image.y = 41;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 52;
            image.y = 41;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var ok_Scale9ButtonRect:Rectangle = new Rectangle(29,16,58,31);
            ok_Scale9Button = new Scale9Button(texture,ok_Scale9ButtonRect);
            ok_Scale9Button.x = 207;
            ok_Scale9Button.y = 515;
            ok_Scale9Button.width = 186;
            ok_Scale9Button.height = 70;
            this.addQuiackChild(ok_Scale9Button);
            ok_Scale9Button.name = 'ok_Scale9Button';
            ok_Scale9Button.text= 'lable';
            ok_Scale9Button.fontColor= 0xFFFFC9;
            ok_Scale9Button.fontSize= 28;
            list_CarryOut = new List();
            list_CarryOut.x = 42;
            list_CarryOut.y = 82;
            list_CarryOut.width = 516;
            list_CarryOut.height = 422;
            this.addQuiackChild(list_CarryOut);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian50510Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian505109ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian50510Rect);
            ui_zhuangshixianquan02_jiemian50510 = new Scale9Image(ui_zhuangshixianquan02_jiemian505109ScaleTexture);
            ui_zhuangshixianquan02_jiemian50510.x = 50;
            ui_zhuangshixianquan02_jiemian50510.y = 510;
            ui_zhuangshixianquan02_jiemian50510.width = 500;
            ui_zhuangshixianquan02_jiemian50510.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian50510);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian50511Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian505119ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian50511Rect);
            ui_zhuangshixianquan02_jiemian50511 = new Scale9Image(ui_zhuangshixianquan02_jiemian505119ScaleTexture);
            ui_zhuangshixianquan02_jiemian50511.x = 50;
            ui_zhuangshixianquan02_jiemian50511.y = 511;
            ui_zhuangshixianquan02_jiemian50511.width = 500;
            ui_zhuangshixianquan02_jiemian50511.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian50511);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            list_CarryOut.dispose();
            super.dispose();
        
}
    }
}
