package game.view.viewBase {
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.dialog.TabDialog;

    public class TaskDialogBase extends TabDialog {
        public var ui_tanchukuangdi01_jiemian013:Scale9Image;
        public var bgImage0:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian26398:Scale9Image;
        public var btn_close:Button;
        public var bgImage1:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian279257:Scale9Image;
        public var bgImage2:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian652257:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian279377:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian651377:Scale9Image;
        public var taskButton_Scale9Button:Scale9Button;
        public var ui_zhuangshixianquan01_jiemian52108:Scale9Image;
        public var ui_zhuangshixianquan03_jiemian3694:Scale9Image;
        public var taskContent:TextField;
        public var targetName_1:TextField;
        public var targetName_2:TextField;
        public var targetName_3:TextField;

        public function TaskDialogBase() {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tanchukuangdi01_jiemian');
            var ui_tanchukuangdi01_jiemian013Rect:Rectangle = new Rectangle(420, 240, 4, 4);
            var ui_tanchukuangdi01_jiemian0139ScaleTexture:Scale9Textures = new Scale9Textures(texture, ui_tanchukuangdi01_jiemian013Rect);
            ui_tanchukuangdi01_jiemian013 = new Scale9Image(ui_tanchukuangdi01_jiemian0139ScaleTexture);
            ui_tanchukuangdi01_jiemian013.y = 13;
            ui_tanchukuangdi01_jiemian013.width = 960;
            ui_tanchukuangdi01_jiemian013.height = 580;
            this.addQuiackChild(ui_tanchukuangdi01_jiemian013);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage0Rect:Rectangle = new Rectangle(12, 12, 20, 20);
            var bgImage09ScaleTexture:Scale9Textures = new Scale9Textures(texture, bgImage0Rect);
            bgImage0 = new Scale9Image(bgImage09ScaleTexture);
            bgImage0.x = 46;
            bgImage0.y = 100;
            bgImage0.width = 210;
            bgImage0.height = 412;
            this.addQuiackChild(bgImage0);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian26398Rect:Rectangle = new Rectangle(12, 12, 20, 20);
            var ui_zhuangshixianquan01_jiemian263989ScaleTexture:Scale9Textures = new Scale9Textures(texture, ui_zhuangshixianquan01_jiemian26398Rect);
            ui_zhuangshixianquan01_jiemian26398 = new Scale9Image(ui_zhuangshixianquan01_jiemian263989ScaleTexture);
            ui_zhuangshixianquan01_jiemian26398.x = 263;
            ui_zhuangshixianquan01_jiemian26398.y = 98;
            ui_zhuangshixianquan01_jiemian26398.width = 658;
            ui_zhuangshixianquan01_jiemian26398.height = 416;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian26398);
            texture = assetMgr.getTexture('ui_taitoudi01_jiemian');
            image = new Image(texture);
            image.x = 120;
            image.y = 9;
            image.width = 720;
            image.height = 56;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_mingzidi01');
            image = new Image(texture);
            image.x = 254;
            image.y = 19;
            image.width = 452;
            image.height = 37;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_guanbi01_anniu');
            btn_close = new Button(texture);
            btn_close.name = 'btn_close';
            btn_close.x = 866;
            btn_close.width = 72;
            btn_close.height = 76;
            this.addQuiackChild(btn_close);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage1Rect:Rectangle = new Rectangle(12, 12, 20, 20);
            var bgImage19ScaleTexture:Scale9Textures = new Scale9Textures(texture, bgImage1Rect);
            bgImage1 = new Scale9Image(bgImage19ScaleTexture);
            bgImage1.x = 269;
            bgImage1.y = 107;
            bgImage1.width = 644;
            bgImage1.height = 131;
            this.addQuiackChild(bgImage1);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian279257Rect:Rectangle = new Rectangle(3, 0, 3, 1);
            var ui_zhuangshixianquan02_jiemian2792579ScaleTexture:Scale9Textures = new Scale9Textures(texture, ui_zhuangshixianquan02_jiemian279257Rect);
            ui_zhuangshixianquan02_jiemian279257 = new Scale9Image(ui_zhuangshixianquan02_jiemian2792579ScaleTexture);
            ui_zhuangshixianquan02_jiemian279257.x = 279;
            ui_zhuangshixianquan02_jiemian279257.y = 257;
            ui_zhuangshixianquan02_jiemian279257.width = 252;
            ui_zhuangshixianquan02_jiemian279257.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian279257);
            texture = assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 274;
            image.y = 103;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 908;
            image.y = 103;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage2Rect:Rectangle = new Rectangle(12, 12, 20, 20);
            var bgImage29ScaleTexture:Scale9Textures = new Scale9Textures(texture, bgImage2Rect);
            bgImage2 = new Scale9Image(bgImage29ScaleTexture);
            bgImage2.x = 270;
            bgImage2.y = 354;
            bgImage2.width = 644;
            bgImage2.height = 154;
            this.addQuiackChild(bgImage2);
            texture = assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 649;
            image.y = 258;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 533;
            image.y = 258;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian652257Rect:Rectangle = new Rectangle(3, 0, 3, 1);
            var ui_zhuangshixianquan02_jiemian6522579ScaleTexture:Scale9Textures = new Scale9Textures(texture, ui_zhuangshixianquan02_jiemian652257Rect);
            ui_zhuangshixianquan02_jiemian652257 = new Scale9Image(ui_zhuangshixianquan02_jiemian6522579ScaleTexture);
            ui_zhuangshixianquan02_jiemian652257.x = 652;
            ui_zhuangshixianquan02_jiemian652257.y = 257;
            ui_zhuangshixianquan02_jiemian652257.width = 252;
            ui_zhuangshixianquan02_jiemian652257.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian652257);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian279377Rect:Rectangle = new Rectangle(3, 0, 3, 1);
            var ui_zhuangshixianquan02_jiemian2793779ScaleTexture:Scale9Textures = new Scale9Textures(texture, ui_zhuangshixianquan02_jiemian279377Rect);
            ui_zhuangshixianquan02_jiemian279377 = new Scale9Image(ui_zhuangshixianquan02_jiemian2793779ScaleTexture);
            ui_zhuangshixianquan02_jiemian279377.x = 279;
            ui_zhuangshixianquan02_jiemian279377.y = 377;
            ui_zhuangshixianquan02_jiemian279377.width = 252;
            ui_zhuangshixianquan02_jiemian279377.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian279377);
            texture = assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 649;
            image.y = 378;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 533;
            image.y = 378;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian651377Rect:Rectangle = new Rectangle(3, 0, 3, 1);
            var ui_zhuangshixianquan02_jiemian6513779ScaleTexture:Scale9Textures = new Scale9Textures(texture, ui_zhuangshixianquan02_jiemian651377Rect);
            ui_zhuangshixianquan02_jiemian651377 = new Scale9Image(ui_zhuangshixianquan02_jiemian6513779ScaleTexture);
            ui_zhuangshixianquan02_jiemian651377.x = 651;
            ui_zhuangshixianquan02_jiemian651377.y = 377;
            ui_zhuangshixianquan02_jiemian651377.width = 252;
            ui_zhuangshixianquan02_jiemian651377.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian651377);
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var taskButton_Scale9ButtonRect:Rectangle = new Rectangle(35, 18, 44, 18);
            taskButton_Scale9Button = new Scale9Button(texture, taskButton_Scale9ButtonRect);
            taskButton_Scale9Button.x = 724;
            taskButton_Scale9Button.y = 410;
            taskButton_Scale9Button.width = 180;
            taskButton_Scale9Button.height = 62;
            this.addQuiackChild(taskButton_Scale9Button);
            taskButton_Scale9Button.name = 'taskButton_Scale9Button';
            taskButton_Scale9Button.text = 'lable';
            taskButton_Scale9Button.fontColor = 0xFFFFFF;
            taskButton_Scale9Button.fontSize = 24;
            texture = assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 905;
            image.y = 109;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 276;
            image.y = 109;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 274;
            image.y = 351;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 908;
            image.y = 351;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 276;
            image.y = 345;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 905;
            image.y = 345;
            image.width = 8;
            image.height = 33;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian52108Rect:Rectangle = new Rectangle(12, 12, 20, 20);
            var ui_zhuangshixianquan01_jiemian521089ScaleTexture:Scale9Textures = new Scale9Textures(texture, ui_zhuangshixianquan01_jiemian52108Rect);
            ui_zhuangshixianquan01_jiemian52108 = new Scale9Image(ui_zhuangshixianquan01_jiemian521089ScaleTexture);
            ui_zhuangshixianquan01_jiemian52108.x = 52;
            ui_zhuangshixianquan01_jiemian52108.y = 108;
            ui_zhuangshixianquan01_jiemian52108.width = 199;
            ui_zhuangshixianquan01_jiemian52108.height = 396;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian52108);
            texture = assetMgr.getTexture('ui_zhuangshixianquan03_jiemian');
            var ui_zhuangshixianquan03_jiemian3694Rect:Rectangle = new Rectangle(30, 30, 10, 10);
            var ui_zhuangshixianquan03_jiemian36949ScaleTexture:Scale9Textures = new Scale9Textures(texture, ui_zhuangshixianquan03_jiemian3694Rect);
            ui_zhuangshixianquan03_jiemian3694 = new Scale9Image(ui_zhuangshixianquan03_jiemian36949ScaleTexture);
            ui_zhuangshixianquan03_jiemian3694.x = 36;
            ui_zhuangshixianquan03_jiemian3694.y = 94;
            ui_zhuangshixianquan03_jiemian3694.width = 231;
            ui_zhuangshixianquan03_jiemian3694.height = 424;
            this.addQuiackChild(ui_zhuangshixianquan03_jiemian3694);
            texture = assetMgr.getTexture('ui_renwu_taitou_wenzi');
            image = new Image(texture);
            image.x = 423;
            image.y = 19;
            image.width = 115;
            image.height = 37;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            taskContent = new TextField(604, 118, '', '', 24, 0xFFFFFF, false);
            taskContent.touchable = false;
            taskContent.hAlign = 'left';
            taskContent.text = '';
            taskContent.x = 289;
            taskContent.y = 116;
            this.addQuiackChild(taskContent);
            texture = assetMgr.getTexture('ui_renwujieshao_xiaotaitou_wenzi');
            image = new Image(texture);
            image.x = 540;
            image.y = 83;
            image.width = 102;
            image.height = 31;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_renwumubiao_xiaotaitou_wenzi');
            image = new Image(texture);
            image.x = 540;
            image.y = 236;
            image.width = 102;
            image.height = 31;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            targetName_1 = new TextField(305, 31, '', '', 24, 0xFFFFFF, false);
            targetName_1.touchable = false;
            targetName_1.hAlign = 'left';
            targetName_1.text = '';
            targetName_1.x = 278;
            targetName_1.y = 259;
            this.addQuiackChild(targetName_1);
            targetName_2 = new TextField(305, 31, '', '', 24, 0xFFFFFF, false);
            targetName_2.touchable = false;
            targetName_2.hAlign = 'left';
            targetName_2.text = '';
            targetName_2.x = 278;
            targetName_2.y = 289;
            this.addQuiackChild(targetName_2);
            texture = assetMgr.getTexture('ui_renwujiangli_xiaotaitou_wenzi');
            image = new Image(texture);
            image.x = 540;
            image.y = 356;
            image.width = 102;
            image.height = 31;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            targetName_3 = new TextField(305, 31, '', '', 24, 0xFFFFFF, false);
            targetName_3.touchable = false;
            targetName_3.hAlign = 'left';
            targetName_3.text = '';
            targetName_3.x = 278;
            targetName_3.y = 320;
            this.addQuiackChild(targetName_3);
            init();
        }

        public function get assetMgr():AssetManager {
            return AssetMgr.instance;
        }

        override public function dispose():void {
            btn_close.dispose();
            super.dispose();

        }
    }
}
