package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import feathers.controls.TextInput;
    import com.dialog.Dialog;

    public class UserRegisterDlgBase extends Dialog
    {
        public var ui_tipstanchukuangdi01_jiemian029:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian45342:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian6889:Scale9Image;
        public var bgImage0:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian68187:Scale9Image;
        public var bgImage1:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian68248:Scale9Image;
        public var bgImage2:Scale9Image;
        public var tag2:Image;
        public var tag1:Image;
        public var tag0:Image;
        public var cancel_Scale9Button:Scale9Button;
        public var ok_Scale9Button:Scale9Button;
        public var txt_tip:TextField;
        public var input_user:TextInput;
        public var input_pwd1:TextInput;
        public var input_pwd2:TextInput;
        public var txt_error:TextField;
        public var userRegistTitle:TextField;

        public function UserRegisterDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian029Rect:Rectangle = new Rectangle(68,64,6,6);
            var ui_tipstanchukuangdi01_jiemian0299ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian029Rect);
            ui_tipstanchukuangdi01_jiemian029 = new Scale9Image(ui_tipstanchukuangdi01_jiemian0299ScaleTexture);
            ui_tipstanchukuangdi01_jiemian029.y = 29;
            ui_tipstanchukuangdi01_jiemian029.width = 496;
            ui_tipstanchukuangdi01_jiemian029.height = 430;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian029);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian45342Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian453429ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian45342Rect);
            ui_zhuangshixianquan02_jiemian45342 = new Scale9Image(ui_zhuangshixianquan02_jiemian453429ScaleTexture);
            ui_zhuangshixianquan02_jiemian45342.x = 45;
            ui_zhuangshixianquan02_jiemian45342.y = 342;
            ui_zhuangshixianquan02_jiemian45342.width = 406;
            ui_zhuangshixianquan02_jiemian45342.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian45342);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian6889Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian68899ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian6889Rect);
            ui_zhuangshixianquan01_jiemian6889 = new Scale9Image(ui_zhuangshixianquan01_jiemian68899ScaleTexture);
            ui_zhuangshixianquan01_jiemian6889.x = 68;
            ui_zhuangshixianquan01_jiemian6889.y = 89;
            ui_zhuangshixianquan01_jiemian6889.width = 332;
            ui_zhuangshixianquan01_jiemian6889.height = 44;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian6889);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage0Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage09ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage0Rect);
            bgImage0 = new Scale9Image(bgImage09ScaleTexture);
            bgImage0.x = 70;
            bgImage0.y = 91;
            bgImage0.width = 328;
            bgImage0.height = 40;
            this.addQuiackChild(bgImage0);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian68187Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian681879ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian68187Rect);
            ui_zhuangshixianquan01_jiemian68187 = new Scale9Image(ui_zhuangshixianquan01_jiemian681879ScaleTexture);
            ui_zhuangshixianquan01_jiemian68187.x = 68;
            ui_zhuangshixianquan01_jiemian68187.y = 187;
            ui_zhuangshixianquan01_jiemian68187.width = 332;
            ui_zhuangshixianquan01_jiemian68187.height = 44;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian68187);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage1Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage19ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage1Rect);
            bgImage1 = new Scale9Image(bgImage19ScaleTexture);
            bgImage1.x = 70;
            bgImage1.y = 189;
            bgImage1.width = 328;
            bgImage1.height = 40;
            this.addQuiackChild(bgImage1);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian68248Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian682489ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian68248Rect);
            ui_zhuangshixianquan01_jiemian68248 = new Scale9Image(ui_zhuangshixianquan01_jiemian682489ScaleTexture);
            ui_zhuangshixianquan01_jiemian68248.x = 68;
            ui_zhuangshixianquan01_jiemian68248.y = 248;
            ui_zhuangshixianquan01_jiemian68248.width = 332;
            ui_zhuangshixianquan01_jiemian68248.height = 44;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian68248);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var bgImage2Rect:Rectangle = new Rectangle(12,12,20,20);
            var bgImage29ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgImage2Rect);
            bgImage2 = new Scale9Image(bgImage29ScaleTexture);
            bgImage2.x = 70;
            bgImage2.y = 250;
            bgImage2.width = 328;
            bgImage2.height = 40;
            this.addQuiackChild(bgImage2);
            texture =assetMgr.getTexture('ui_mingzidi01');
            image = new Image(texture);
            image.x = 27;
            image.width = 452;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_kexuanzhuangtai2')
            tag2 = new Image(texture);
            tag2.x = 410;
            tag2.y = 254;
            tag2.width = 38;
            tag2.height = 34;
            this.addQuiackChild(tag2);
            tag2.touchable = false;
            texture = assetMgr.getTexture('ui_kexuanzhuangtai2')
            tag1 = new Image(texture);
            tag1.x = 410;
            tag1.y = 194;
            tag1.width = 38;
            tag1.height = 34;
            this.addQuiackChild(tag1);
            tag1.touchable = false;
            texture = assetMgr.getTexture('ui_kexuanzhuangtai2')
            tag0 = new Image(texture);
            tag0.x = 410;
            tag0.y = 95;
            tag0.width = 38;
            tag0.height = 34;
            this.addQuiackChild(tag0);
            tag0.touchable = false;
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 48;
            image.y = 69;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 444;
            image.y = 69;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 442;
            image.y = 75;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 50;
            image.y = 75;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_lan03_01_anniu');
            var cancel_Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            cancel_Scale9Button = new Scale9Button(texture,cancel_Scale9ButtonRect);
            cancel_Scale9Button.x = 45;
            cancel_Scale9Button.y = 355;
            cancel_Scale9Button.width = 186;
            cancel_Scale9Button.height = 62;
            this.addQuiackChild(cancel_Scale9Button);
            cancel_Scale9Button.name = 'cancel_Scale9Button';
            cancel_Scale9Button.text= 'lable';
            cancel_Scale9Button.fontColor= 0xFFFFC9;
            cancel_Scale9Button.fontSize= 28;
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var ok_Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            ok_Scale9Button = new Scale9Button(texture,ok_Scale9ButtonRect);
            ok_Scale9Button.x = 265;
            ok_Scale9Button.y = 355;
            ok_Scale9Button.width = 186;
            ok_Scale9Button.height = 62;
            this.addQuiackChild(ok_Scale9Button);
            ok_Scale9Button.name = 'ok_Scale9Button';
            ok_Scale9Button.text= 'lable';
            ok_Scale9Button.fontColor= 0xFFFFC9;
            ok_Scale9Button.fontSize= 28;
            txt_tip = new TextField(380,53,'','',21,0xFF9933,false);
            txt_tip.touchable = false;
            txt_tip.hAlign= 'center';
            txt_tip.text= '';
            txt_tip.x = 43;
            txt_tip.y = 134;
            this.addQuiackChild(txt_tip);
            input_user = new TextInput();
            input_user.textEditorProperties.fontSize = 28;
            input_user.text = '';
            input_user.textEditorProperties.color = 0xFFFFFF;
            input_user.x = 72;
            input_user.y = 93;
            input_user.width = 322;
            input_user.height = 36;
            this.addQuiackChild(input_user);
            input_pwd1 = new TextInput();
            input_pwd1.textEditorProperties.fontSize = 28;
            input_pwd1.text = '';
            input_pwd1.textEditorProperties.color = 0xFFFFFF;
            input_pwd1.x = 72;
            input_pwd1.y = 191;
            input_pwd1.width = 322;
            input_pwd1.height = 36;
            this.addQuiackChild(input_pwd1);
            input_pwd2 = new TextInput();
            input_pwd2.textEditorProperties.fontSize = 28;
            input_pwd2.text = '';
            input_pwd2.textEditorProperties.color = 0xFFFFFF;
            input_pwd2.x = 72;
            input_pwd2.y = 252;
            input_pwd2.width = 322;
            input_pwd2.height = 36;
            this.addQuiackChild(input_pwd2);
            txt_error = new TextField(380,40,'','',21,0xE8201B,false);
            txt_error.touchable = false;
            txt_error.hAlign= 'center';
            txt_error.text= '';
            txt_error.x = 43;
            txt_error.y = 296;
            this.addQuiackChild(txt_error);
            userRegistTitle = new TextField(322,32,'','',24,0xFFFFFF,false);
            userRegistTitle.touchable = false;
            userRegistTitle.hAlign= 'center';
            userRegistTitle.text= '';
            userRegistTitle.x = 92;
            userRegistTitle.y = 2;
            this.addQuiackChild(userRegistTitle);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            input_user.dispose();
            input_pwd1.dispose();
            input_pwd2.dispose();
            super.dispose();
        
}
    }
}
