package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import feathers.controls.TextInput;
    import com.dialog.Dialog;

    public class UserLoginDlgBase extends Dialog
    {
        public var ui_tipstanchukuangdi01_jiemian029:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian45256:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian82102:Scale9Image;
        public var ui_zhuangshixianquan01_jiemian82190:Scale9Image;
        public var ok_Scale9Button:Scale9Button;
        public var back_Scale9Button:Scale9Button;
        public var userImage:Scale9Image;
        public var passwordImage:Scale9Image;
        public var userInput:TextInput;
        public var psw1Input:TextInput;
        public var userTitleTxt:TextField;
        public var userTipTxt:TextField;
        public var text_des:TextField;

        public function UserLoginDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian029Rect:Rectangle = new Rectangle(68,64,6,6);
            var ui_tipstanchukuangdi01_jiemian0299ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian029Rect);
            ui_tipstanchukuangdi01_jiemian029 = new Scale9Image(ui_tipstanchukuangdi01_jiemian0299ScaleTexture);
            ui_tipstanchukuangdi01_jiemian029.y = 29;
            ui_tipstanchukuangdi01_jiemian029.width = 496;
            ui_tipstanchukuangdi01_jiemian029.height = 346;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian029);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian45256Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian452569ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian45256Rect);
            ui_zhuangshixianquan02_jiemian45256 = new Scale9Image(ui_zhuangshixianquan02_jiemian452569ScaleTexture);
            ui_zhuangshixianquan02_jiemian45256.x = 45;
            ui_zhuangshixianquan02_jiemian45256.y = 256;
            ui_zhuangshixianquan02_jiemian45256.width = 406;
            ui_zhuangshixianquan02_jiemian45256.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian45256);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 48;
            image.y = 69;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 444;
            image.y = 69;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_mingzidi01');
            image = new Image(texture);
            image.x = 22;
            image.width = 452;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian82102Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian821029ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian82102Rect);
            ui_zhuangshixianquan01_jiemian82102 = new Scale9Image(ui_zhuangshixianquan01_jiemian821029ScaleTexture);
            ui_zhuangshixianquan01_jiemian82102.x = 82;
            ui_zhuangshixianquan01_jiemian82102.y = 102;
            ui_zhuangshixianquan01_jiemian82102.width = 332;
            ui_zhuangshixianquan01_jiemian82102.height = 44;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian82102);
            texture = assetMgr.getTexture('ui_zhuangshixianquan01_jiemian');
            var ui_zhuangshixianquan01_jiemian82190Rect:Rectangle = new Rectangle(12,12,20,20);
            var ui_zhuangshixianquan01_jiemian821909ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan01_jiemian82190Rect);
            ui_zhuangshixianquan01_jiemian82190 = new Scale9Image(ui_zhuangshixianquan01_jiemian821909ScaleTexture);
            ui_zhuangshixianquan01_jiemian82190.x = 82;
            ui_zhuangshixianquan01_jiemian82190.y = 190;
            ui_zhuangshixianquan01_jiemian82190.width = 332;
            ui_zhuangshixianquan01_jiemian82190.height = 44;
            this.addQuiackChild(ui_zhuangshixianquan01_jiemian82190);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 442;
            image.y = 75;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 50;
            image.y = 75;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_lv03_01_anniu');
            var ok_Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            ok_Scale9Button = new Scale9Button(texture,ok_Scale9ButtonRect);
            ok_Scale9Button.x = 265;
            ok_Scale9Button.y = 269;
            ok_Scale9Button.width = 186;
            ok_Scale9Button.height = 70;
            this.addQuiackChild(ok_Scale9Button);
            ok_Scale9Button.name = 'ok_Scale9Button';
            ok_Scale9Button.text= 'lable';
            ok_Scale9Button.fontColor= 0xFFFFC9;
            ok_Scale9Button.fontSize= 28;
            texture = assetMgr.getTexture('ui_lan03_01_anniu');
            var back_Scale9ButtonRect:Rectangle = new Rectangle(56,24,4,2);
            back_Scale9Button = new Scale9Button(texture,back_Scale9ButtonRect);
            back_Scale9Button.x = 45;
            back_Scale9Button.y = 269;
            back_Scale9Button.width = 186;
            back_Scale9Button.height = 70;
            this.addQuiackChild(back_Scale9Button);
            back_Scale9Button.name = 'back_Scale9Button';
            back_Scale9Button.text= 'lable';
            back_Scale9Button.fontColor= 0xFFFFC9;
            back_Scale9Button.fontSize= 28;
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var userImageRect:Rectangle = new Rectangle(12,12,20,20);
            var userImage9ScaleTexture:Scale9Textures = new Scale9Textures(texture,userImageRect);
            userImage = new Scale9Image(userImage9ScaleTexture);
            userImage.x = 84;
            userImage.y = 104;
            userImage.width = 328;
            userImage.height = 40;
            this.addQuiackChild(userImage);
            texture = assetMgr.getTexture('ui_dicengying02_jiemian');
            var passwordImageRect:Rectangle = new Rectangle(12,12,20,20);
            var passwordImage9ScaleTexture:Scale9Textures = new Scale9Textures(texture,passwordImageRect);
            passwordImage = new Scale9Image(passwordImage9ScaleTexture);
            passwordImage.x = 84;
            passwordImage.y = 192;
            passwordImage.width = 328;
            passwordImage.height = 40;
            this.addQuiackChild(passwordImage);
            userInput = new TextInput();
            userInput.textEditorProperties.fontSize = 28;
            userInput.text = '';
            userInput.textEditorProperties.color = 0x999999;
            userInput.x = 86;
            userInput.y = 104;
            userInput.width = 322;
            userInput.height = 42;
            this.addQuiackChild(userInput);
            psw1Input = new TextInput();
            psw1Input.textEditorProperties.fontSize = 28;
            psw1Input.text = '';
            psw1Input.textEditorProperties.color = 0x999999;
            psw1Input.x = 86;
            psw1Input.y = 194;
            psw1Input.width = 322;
            psw1Input.height = 36;
            this.addQuiackChild(psw1Input);
            userTitleTxt = new TextField(322,32,'','',24,0xFFFFFF,false);
            userTitleTxt.touchable = false;
            userTitleTxt.hAlign= 'center';
            userTitleTxt.text= '';
            userTitleTxt.x = 87;
            userTitleTxt.y = 2;
            this.addQuiackChild(userTitleTxt);
            userTipTxt = new TextField(322,36,'','',28,0x999999,false);
            userTipTxt.touchable = false;
            userTipTxt.hAlign= 'center';
            userTipTxt.text= '';
            userTipTxt.x = 86;
            userTipTxt.y = 106;
            this.addQuiackChild(userTipTxt);
            text_des = new TextField(428,33,'','',24,0xFFFFFF,false);
            text_des.touchable = false;
            text_des.hAlign= 'center';
            text_des.text= '';
            text_des.x = 34;
            text_des.y = 152;
            this.addQuiackChild(text_des);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            userInput.dispose();
            psw1Input.dispose();
            super.dispose();
        
}
    }
}
