package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.controls.List;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import game.view.vip.VipInfoView;
    import com.dialog.TabDialog;

    public class VipDlgBase extends TabDialog
    {
        public var ui_tanchukuangdi01_jiemian014:Scale9Image;
        public var vipInfo:VipInfoView;
        public var ui_zhuangshixianquan03_jiemian3682:Scale9Image;
        public var txt_currlv:TextField;
        public var text_addRecharge:TextField;
        public var bg:Scale9Image;
        public var exp_curr:Scale9Image;
        public var exp_curr_txt:TextField;
        public var text_Canbecome:TextField;
        public var diamand:TextField;
        public var txt_nextlv:TextField;
        public var btn_look_Scale9Button:Scale9Button;
        public var btn_close:Button;
        public var list_charge:List;

        public function VipDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tanchukuangdi01_jiemian');
            var ui_tanchukuangdi01_jiemian014Rect:Rectangle = new Rectangle(420,240,4,4);
            var ui_tanchukuangdi01_jiemian0149ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tanchukuangdi01_jiemian014Rect);
            ui_tanchukuangdi01_jiemian014 = new Scale9Image(ui_tanchukuangdi01_jiemian0149ScaleTexture);
            ui_tanchukuangdi01_jiemian014.y = 14;
            ui_tanchukuangdi01_jiemian014.width = 960;
            ui_tanchukuangdi01_jiemian014.height = 580;
            this.addQuiackChild(ui_tanchukuangdi01_jiemian014);
            vipInfo = new VipInfoView();
            vipInfo.y = 194;
            this.addQuiackChild(vipInfo);
            texture =assetMgr.getTexture('ui_taitoudi01_jiemian');
            image = new Image(texture);
            image.x = 120;
            image.y = 10;
            image.width = 720;
            image.height = 56;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_mingzidi01');
            image = new Image(texture);
            image.x = 254;
            image.y = 20;
            image.width = 452;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuangshixianquan03_jiemian');
            var ui_zhuangshixianquan03_jiemian3682Rect:Rectangle = new Rectangle(30,30,10,10);
            var ui_zhuangshixianquan03_jiemian36829ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan03_jiemian3682Rect);
            ui_zhuangshixianquan03_jiemian3682 = new Scale9Image(ui_zhuangshixianquan03_jiemian36829ScaleTexture);
            ui_zhuangshixianquan03_jiemian3682.x = 36;
            ui_zhuangshixianquan03_jiemian3682.y = 82;
            ui_zhuangshixianquan03_jiemian3682.width = 888;
            ui_zhuangshixianquan03_jiemian3682.height = 100;
            this.addQuiackChild(ui_zhuangshixianquan03_jiemian3682);
            texture =assetMgr.getTexture('ui_vipzuoshang01_tubiao');
            image = new Image(texture);
            image.x = 60;
            image.y = 102;
            image.width = 50;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_currlv = new TextField(50,31,'','',24,0xFFFFFF,false);
            txt_currlv.touchable = false;
            txt_currlv.hAlign= 'center';
            txt_currlv.text= '';
            txt_currlv.x = 60;
            txt_currlv.y = 118;
            this.addQuiackChild(txt_currlv);
            text_addRecharge = new TextField(78,37,'','',24,0xFFFFFF,false);
            text_addRecharge.touchable = false;
            text_addRecharge.hAlign= 'right';
            text_addRecharge.text= ' ';
            text_addRecharge.x = 533;
            text_addRecharge.y = 115;
            this.addQuiackChild(text_addRecharge);
            texture = assetMgr.getTexture('ui_chengjiu_01_jindutiao');
            var bgRect:Rectangle = new Rectangle(62,0,4,32);
            var bg9ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgRect);
            bg = new Scale9Image(bg9ScaleTexture);
            bg.x = 123;
            bg.y = 119;
            bg.width = 409;
            bg.height = 32;
            this.addQuiackChild(bg);
            texture = assetMgr.getTexture('ui_chengjiu_02_jindutiao');
            var exp_currRect:Rectangle = new Rectangle(62,4,4,22);
            var exp_curr9ScaleTexture:Scale9Textures = new Scale9Textures(texture,exp_currRect);
            exp_curr = new Scale9Image(exp_curr9ScaleTexture);
            exp_curr.x = 122;
            exp_curr.y = 119;
            exp_curr.width = 410;
            exp_curr.height = 32;
            this.addQuiackChild(exp_curr);
            exp_curr_txt = new TextField(210,28,'','',21,0xFFFFFF,false);
            exp_curr_txt.touchable = false;
            exp_curr_txt.hAlign= 'center';
            exp_curr_txt.text= '';
            exp_curr_txt.x = 227;
            exp_curr_txt.y = 119;
            this.addQuiackChild(exp_curr_txt);
            text_Canbecome = new TextField(119,37,'','',24,0xFFFFFF,false);
            text_Canbecome.touchable = false;
            text_Canbecome.hAlign= 'center';
            text_Canbecome.text= '';
            text_Canbecome.x = 725;
            text_Canbecome.y = 115;
            this.addQuiackChild(text_Canbecome);
            diamand = new TextField(88,37,'','',24,0x00CCFF,false);
            diamand.touchable = false;
            diamand.hAlign= 'center';
            diamand.text= '';
            diamand.x = 611;
            diamand.y = 115;
            this.addQuiackChild(diamand);
            texture =assetMgr.getTexture('ui_zuanshi01_tubiao');
            image = new Image(texture);
            image.x = 699;
            image.y = 119;
            image.width = 25;
            image.height = 26;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_vipzuoshang01_tubiao');
            image = new Image(texture);
            image.x = 845;
            image.y = 102;
            image.width = 50;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_nextlv = new TextField(50,31,'','',24,0xFFFFFF,false);
            txt_nextlv.touchable = false;
            txt_nextlv.hAlign= 'center';
            txt_nextlv.text= '';
            txt_nextlv.x = 845;
            txt_nextlv.y = 118;
            this.addQuiackChild(txt_nextlv);
            texture = assetMgr.getTexture('ui_hong02_01_anniu');
            var btn_look_Scale9ButtonRect:Rectangle = new Rectangle(46,1,4,35);
            btn_look_Scale9Button = new Scale9Button(texture,btn_look_Scale9ButtonRect);
            btn_look_Scale9Button.x = 668;
            btn_look_Scale9Button.y = 19;
            btn_look_Scale9Button.width = 150;
            btn_look_Scale9Button.height = 39;
            this.addQuiackChild(btn_look_Scale9Button);
            btn_look_Scale9Button.name = 'btn_look_Scale9Button';
            btn_look_Scale9Button.text= 'lable';
            btn_look_Scale9Button.fontColor= 0xFFFFFFB4;
            btn_look_Scale9Button.fontSize= 21;
            texture =assetMgr.getTexture('ui_chongzhi_taitou_wenzi');
            image = new Image(texture);
            image.x = 423;
            image.y = 20;
            image.width = 115;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_guanbi01_anniu');
            btn_close = new Button(texture);
            btn_close.name= 'btn_close';
            btn_close.x = 866;
            btn_close.width = 72;
            btn_close.height = 76;
            this.addQuiackChild(btn_close);
            list_charge = new List();
            list_charge.x = 42;
            list_charge.y = 191;
            list_charge.width = 876;
            list_charge.height = 339;
            this.addQuiackChild(list_charge);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            vipInfo.dispose();
            btn_close.dispose();
            list_charge.dispose();
            super.dispose();
        
}
    }
}
