package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.utils.AssetManager;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.components.Scale9Button;
    import com.dialog.TabDialog;

    public class WelfareViewBase extends TabDialog
    {
        public var ui_tipstanchukuangdi01_jiemian00:Scale9Image;
        public var ui_zhuangshixianquan02_jiemian4375:Scale9Image;
        public var txt_title:TextField;
        public var btn_first:Button;
        public var btn_lucky:Button;
        public var btn_share:Button;
        public var btn_rank:Button;
        public var btn_new:Button;
        public var btn_vip:Button;
        public var btn_month:Button;
        public var btn_sign:Button;
        public var btn_reward:Button;

        public function WelfareViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            texture = assetMgr.getTexture('ui_tipstanchukuangdi01_jiemian');
            var ui_tipstanchukuangdi01_jiemian00Rect:Rectangle = new Rectangle(68,64,6,6);
            var ui_tipstanchukuangdi01_jiemian009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_tipstanchukuangdi01_jiemian00Rect);
            ui_tipstanchukuangdi01_jiemian00 = new Scale9Image(ui_tipstanchukuangdi01_jiemian009ScaleTexture);
            ui_tipstanchukuangdi01_jiemian00.width = 600;
            ui_tipstanchukuangdi01_jiemian00.height = 350;
            this.addQuiackChild(ui_tipstanchukuangdi01_jiemian00);
            texture = assetMgr.getTexture('ui_zhuangshixianquan02_jiemian');
            var ui_zhuangshixianquan02_jiemian4375Rect:Rectangle = new Rectangle(3,0,3,1);
            var ui_zhuangshixianquan02_jiemian43759ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_zhuangshixianquan02_jiemian4375Rect);
            ui_zhuangshixianquan02_jiemian4375 = new Scale9Image(ui_zhuangshixianquan02_jiemian43759ScaleTexture);
            ui_zhuangshixianquan02_jiemian4375.x = 43;
            ui_zhuangshixianquan02_jiemian4375.y = 75;
            ui_zhuangshixianquan02_jiemian4375.width = 512;
            ui_zhuangshixianquan02_jiemian4375.height = 1;
            this.addQuiackChild(ui_zhuangshixianquan02_jiemian4375);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 50;
            image.y = 41;
            image.width = 33;
            image.height = 8;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 550;
            image.y = 41;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 207;
            image.y = 74;
            image.width = 33;
            image.height = 8;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen01_jiemian');
            image = new Image(texture);
            image.x = 383;
            image.y = 74;
            image.width = 33;
            image.height = 8;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 545;
            image.y = 48;
            image.width = 8;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuangshihuawen02_jiemian');
            image = new Image(texture);
            image.x = 53;
            image.y = 48;
            image.width = 8;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_title = new TextField(104,38,'','',30,0xFFFFFF,false);
            txt_title.touchable = false;
            txt_title.hAlign= 'center';
            txt_title.text= '福利';
            txt_title.x = 242;
            txt_title.y = 35;
            this.addQuiackChild(txt_title);
            texture = assetMgr.getTexture('ui_button_city_shouchong');
            btn_first = new Button(texture);
            btn_first.name= 'btn_first';
            btn_first.x = 54;
            btn_first.y = 105;
            btn_first.width = 65;
            btn_first.height = 65;
            this.addQuiackChild(btn_first);
            texture = assetMgr.getTexture('ui_button_city_choujiang');
            btn_lucky = new Button(texture);
            btn_lucky.name= 'btn_lucky';
            btn_lucky.x = 161;
            btn_lucky.y = 105;
            btn_lucky.width = 65;
            btn_lucky.height = 65;
            this.addQuiackChild(btn_lucky);
            texture = assetMgr.getTexture('ui_button_city_fenxiang');
            btn_share = new Button(texture);
            btn_share.name= 'btn_share';
            btn_share.x = 267;
            btn_share.y = 105;
            btn_share.width = 65;
            btn_share.height = 65;
            this.addQuiackChild(btn_share);
            texture = assetMgr.getTexture('ui_button_city_paihang');
            btn_rank = new Button(texture);
            btn_rank.name= 'btn_rank';
            btn_rank.x = 374;
            btn_rank.y = 105;
            btn_rank.width = 65;
            btn_rank.height = 65;
            this.addQuiackChild(btn_rank);
            texture = assetMgr.getTexture('ui_button_city_xinshou');
            btn_new = new Button(texture);
            btn_new.name= 'btn_new';
            btn_new.x = 480;
            btn_new.y = 105;
            btn_new.width = 65;
            btn_new.height = 65;
            this.addQuiackChild(btn_new);
            texture = assetMgr.getTexture('ui_button_city_viplibao');
            btn_vip = new Button(texture);
            btn_vip.name= 'btn_vip';
            btn_vip.x = 50;
            btn_vip.y = 217;
            btn_vip.width = 65;
            btn_vip.height = 65;
            this.addQuiackChild(btn_vip);
            texture = assetMgr.getTexture('ui_iocn_month_card');
            btn_month = new Button(texture);
            btn_month.name= 'btn_month';
            btn_month.x = 161;
            btn_month.y = 217;
            btn_month.width = 65;
            btn_month.height = 65;
            this.addQuiackChild(btn_month);
            texture = assetMgr.getTexture('ui_button_city_qiandao');
            btn_sign = new Button(texture);
            btn_sign.name= 'btn_sign';
            btn_sign.x = 267;
            btn_sign.y = 217;
            btn_sign.width = 65;
            btn_sign.height = 65;
            this.addQuiackChild(btn_sign);
            texture = assetMgr.getTexture('ui_button_city_chengjiu');
            btn_reward = new Button(texture);
            btn_reward.name= 'btn_reward';
            btn_reward.x = 374;
            btn_reward.y = 217;
            btn_reward.width = 65;
            btn_reward.height = 65;
            this.addQuiackChild(btn_reward);
            init();
        }
        public function get assetMgr():AssetManager{return AssetMgr.instance;}
        override public function dispose():void
        {
            btn_first.dispose();
            btn_lucky.dispose();
            btn_share.dispose();
            btn_rank.dispose();
            btn_new.dispose();
            btn_vip.dispose();
            btn_month.dispose();
            btn_sign.dispose();
            btn_reward.dispose();
            super.dispose();
        
}
    }
}
